### ISSUE TITLE
Optimize Navbar on smaller screens

### ISSUE THREAD

**Issue by lucasvo** [centrifuge/apps#10]
There are a few changes we should make to improve the usability of the navbar especially at smaller screen sizes (970px width already renders the mobile view). The design changes are reflected on [figma](https://www.figma.com/file/EWziKt1qCFdHGhWdnkrcKf/Tinlake-UI?node-id=1030%3A1822). 

Changes on all screens:
* Remove the vertical lines separating sections

Small screen optimizations (between 500 and 1000 px width):
* We should only show the full logo on the dashboard, when the pool dropdown is rendered, we should just show the blue shape with the T.

Mobile screen:
* The account icon should not be in the in the top bar, only the hamburger menu. The wallet should be a menu item in the hamburger menu that the user can click on to render the account overview in the hamburger menu. This then should replace the full screen hamburger menu with a full screen rendering of the wallet details
* The hamburger menu is currently broken (makes you scroll the page on iphone sized screens) -> we should make it render full screen

**Comment by denniswell** [comment]
Additional small screen optimization (behaviour when resizing window):
Drop the "Pool Selection" component, before switching from tabs to hamburger menu
Nice to have: The web3 wallet component could shrink to only showing icon and chevron and hide the address before switching from tabs to hamburger menu

**Comment by onnovisser** [comment]
Fixed by #294
