### ISSUE TITLE
Configuration page

### ISSUE THREAD

**Issue by EstherCentrifuge** [centrifuge/apps#1000]
* [Pool configuration (read-only)](https://www.figma.com/file/d1bEBkwllUQe27nQM6VlJu/Centrifuge-app---Version-1-(Master)?node-id=6398%3A117461)
* [Pool configuration (in edit)](https://www.figma.com/file/d1bEBkwllUQe27nQM6VlJu/Centrifuge-app---Version-1-(Master)?node-id=6398%3A117770)

Some key changes since discussion:

- Tranches are only display not editable
- Risk groups are to display, add new, not remove or edit existing
- Write of groups are to display, add new, not remove or edit existing
- min epoch time should be separated in hour and min fields.
- add a penalty interest rate to the write-off groups -> Also udpate Create pool form
- Add initialization button on top.
- Remove write offs from Create pool
- Hide pool in menu logic (see comment below)

Add "Initial pool" action @onnovisser  -> there is no design for it on Figma we can create something for it.

**Comment by EstherCentrifuge** [comment]
hide checkbox option discussion:
When hidden,
-  don't show pool on pool list
- Don't count hidden to toals (Pools, tokens  TVL) 

Example 
10 pools , 3 hidden
Show 7 pools in list
TVL = sum of 7 dissplaybed pools

**Comment by EstherCentrifuge** [comment]
- Add initialization button on top.
- Remove write offs from Create pool

**Comment by EstherCentrifuge** [comment]
Misscommunication on the  tranche updates; [Slack](https://centrifugehq.slack.com/archives/C033T5YUX0W/p1661282225847149)

Sugested chamge:
1.  combining the tranches and epoch time in a single section, e.g. Pool structure/setup (?). This will be saved together. This will also make it easier to display a scheduled change, as it will just apply to this section. 
2.  We don’t allow adding or removing tranches, but we do and should allow updating existing tranches

**Comment by annamehr** [comment]
implemented
