### ISSUE TITLE
CentrifugeJS: send files to pin to IPFS directly in FormData

### ISSUE THREAD

**Issue by sophialittlejohn** [centrifuge/apps#1002]
Right now we convert files to base64 uris to submit to lambda and convert it back to a file in FormData. See [`pinFile.js`](https://github.com/centrifuge/apps/blob/6450bddf39efef1a4d5d923cf17a7ea3f8e56ec3/centrifuge-app/lambda/pinFile.js)

Goal: send the file as an actual `File` to the lambda as `FormData()` to pass through to the pinata pin method.

**Comment by sonam-jo** [comment]
Spoke with Frederik. Ticket is too old to be relevant, also we will use the data protocol in the near future
