### ISSUE TITLE
Public Demo enviornment UI updates

### ISSUE THREAD

**Issue by EstherCentrifuge** [centrifuge/apps#1004]
## Back ground

- We want to have a demo environment where users can invest and try the app and use demo currencies.
(demo.app.centrifuge.io.)  -> this is already working
- This environment needs to have a banner with "this is a demo" warning 
- Need to craete some sort of introduction on how to setup a demo account

## Banner

Text: " Welcome to the demo environment of the Centrifuge App. All data and wallet transactions are not real as this is purely a testing environment." 
We'll need to add a link to "how to get started" or "how to set up a demo account". 
This banner should overlay on every single page.

Design:
![image.png](https://images.zenhubusercontent.com/61fa54b8b520bc58fd924e32/fa4c906c-cdc4-4749-baf3-30f97cf0f213)

## Account setup
Create a how to set up a demo account and request currency -> Esther
Set up a demo Discord channel to request currecy -> Esther

**Comment by EstherCentrifuge** [comment]
@sophialittlejohn assigned this as well to you as it's a very small UI ticket for the demo environment please do it after you fixed the faucet so we can "go live" with this demo environment

**Comment by annamehr** [comment]
@sophialittlejohn do you know if Esther finished these two tasks?

- Create a how to set up a demo account and request currency -> Esther
- Set up a demo Discord channel to request currecy -> Esther

**Comment by denniswell** [comment]
I am not not aware of this. @Sophia Littlejohn ***@***.***> Any
idea?

**Comment by sophialittlejohn** [comment]
@annamehr @denniswell I'm not aware of it either. If, then it may be lost somewhere in HackMD

**Comment by annamehr** [comment]
@sophialittlejohn new Banner text and instructions: 
"Welcome to the demo environment of the Centrifuge App. All data and wallet transactions are not real as this is purely a testing environment. Read [here](https://centrifuge.hackmd.io/@Anna/H1ylqpRQj) how to get started."
