### ISSUE TITLE
Fix weighting of averages in risk group table

### ISSUE THREAD

**Issue by offerijns** [centrifuge/apps#1020]
Average financing fee and average risk adjustment should be weighted based on the outstanding amount of each loan.

**Comment by EstherCentrifuge** [comment]
![image.png](https://images.zenhubusercontent.com/61fa54b8b520bc58fd924e32/e776da14-5392-461b-beb0-94f0f5c78455)

**Comment by annamehr** [comment]
instructions: 
you’ll need to do some math. take a pool with no assets minted yet and with 2 risk groups for example. you could create an asset and finance it with 1 aUSD in risk group 1, create another asset in risk group 2 worth 500 aUSD. Then make sure the avg financing fee and the avg risk adjustment change

**Comment by sirjared** [comment]
Ran through this one based on a few of my active pools in Demo env. I will test again once Dev is ready for me to create more pools. 

Weighted AVG is working. Included workbook as well. 
[Fix weighting of averages in risk group table Fix weighting of averages in risk group table.xlsx](https://github.com/centrifuge/apps/files/10006989/Fix.weighting.of.averages.in.risk.group.table.Fix.weighting.of.averages.in.risk.group.table.xlsx)


Test Case 1: Jays Properties

Calculated Weighted avg: 

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:////Users/jdanzer/Library/Group%20Containers/UBF8T346G9.Office/TemporaryItems/msohtmlclip/clip.htm">
<link rel=File-List
href="file:////Users/jdanzer/Library/Group%20Containers/UBF8T346G9.Office/TemporaryItems/msohtmlclip/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">
<meta charset=utf-8>

<div style='box-sizing: inherit;-webkit-box-align: center;align-items: center;
display:flex;font-variant-ligatures: normal;font-variant-caps: normal;
orphans: 2;text-align:start;widows: 2;-webkit-text-stroke-width: 0px;
text-decoration-thickness: initial;text-decoration-style: initial;text-decoration-color: initial'>



Risk group | Amount | Share | Financing fee | Risk adjustment | WFF | WRA |  
-- | -- | -- | -- | -- | -- | -- | --
AAA | 175333 | 2% | 8.00% | 0.20% |   | 14026.64 | 350.67 |  
AA | 6345435 | 85% | 10.00% | 0.70% |   | 634543.5 | 44418.05 |  
BBB | 173769 | 2% | 12.50% | 1.80% |   | 21721.125 | 3127.84 |  
BB | 755415 | 10% | 15.00% | 1.80% |   | 113312.25 | 13597.47 |  
Total | 7449952 | 99% | Avg. 10.52% | Avg. 0.83% |   | 783603.515 | 61494.023 | SUM
Weighted Avg calc |   |   |   |   |   | 10.52% | 0.83% |  




</body>

</html>


<img width="807" alt="Screenshot 2022-11-14 at 3 14 52 PM" src="https://user-images.githubusercontent.com/82420771/201756937-9e29b1ac-abe0-487e-87cd-f54338c72f83.png">

Test Case 2: JUST LOGISTICS SERIES 3

Calculated Weighted avg: 
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:////Users/jdanzer/Library/Group%20Containers/UBF8T346G9.Office/TemporaryItems/msohtmlclip/clip.htm">
<link rel=File-List
href="file:////Users/jdanzer/Library/Group%20Containers/UBF8T346G9.Office/TemporaryItems/msohtmlclip/clip_filelist.xml">
<style>

</style>
</head>

<meta charset=utf-8>

<div style='box-sizing: inherit;-webkit-box-align: center;align-items: center;
display:flex;font-variant-ligatures: normal;font-variant-caps: normal;
orphans: 2;text-align:start;widows: 2;-webkit-text-stroke-width: 0px;
text-decoration-thickness: initial;text-decoration-style: initial;text-decoration-color: initial'>

<div style='box-sizing: inherit;text-decoration:initial'>

<div style='box-sizing: inherit;-webkit-box-align: center;align-items: center;
display:flex'></div>

</div>

<div style='box-sizing: inherit;text-decoration:initial'>

<div style='box-sizing: inherit;-webkit-box-align: center;align-items: center;
display:flex'></div>

</div>

<div style='box-sizing: inherit;text-decoration:initial'>

<div style='box-sizing: inherit;-webkit-box-align: center;align-items: center;
display:flex'></div>

</div>

<div style='box-sizing: inherit;text-decoration:initial'>

<div style='box-sizing: inherit;-webkit-box-align: center;align-items: center;
display:flex'></div>

</div>

<div style='box-sizing: inherit;text-decoration:initial'>

<div style='box-sizing: inherit;-webkit-box-align: center;align-items: center;
display:flex'></div>

</div>

<div style='box-sizing: inherit;background:initial;display:flex;flex: 1 1 0%;
max-width:100%;-webkit-box-pack: end;justify-content: flex-end'></div>

<div style='box-sizing: inherit;background:initial;display:flex;flex: 1 1 0%;
max-width:100%;-webkit-box-pack: end;justify-content: flex-end'></div>

<div style='box-sizing: inherit;background:initial;display:flex;flex: 1 1 0%;
max-width:100%;-webkit-box-pack: end;justify-content: flex-end'></div>

<div style='box-sizing: inherit;background:initial;display:flex;flex: 1 1 0%;
max-width:100%;-webkit-box-pack: end;justify-content: flex-end'></div>

</div>

<div style='box-sizing: inherit;background:initial;display:flex;flex: 1 1 0%;
max-width:100%;-webkit-box-pack: end;justify-content: flex-end'></div>

<div style='box-sizing: inherit;background:initial;display:flex;flex: 1 1 0%;
max-width:100%;-webkit-box-pack: end;justify-content: flex-end'></div>

<div style='box-sizing: inherit;background:initial;display:flex;flex: 1 1 0%;
max-width:100%;-webkit-box-pack: end;justify-content: flex-end'></div>

<div style='box-sizing: inherit;background:initial;display:flex;flex: 1 1 0%;
max-width:100%;-webkit-box-pack: end;justify-content: flex-end'></div>

</div>

<div style='box-sizing: inherit;background:initial;display:flex;flex: 1 1 0%;
max-width:100%;-webkit-box-pack: end;justify-content: flex-end'></div>

<div style='box-sizing: inherit;background:initial;display:flex;flex: 1 1 0%;
max-width:100%;-webkit-box-pack: end;justify-content: flex-end'></div>

<div style='box-sizing: inherit;background:initial;display:flex;flex: 1 1 0%;
max-width:100%;-webkit-box-pack: end;justify-content: flex-end'></div>

<div style='box-sizing: inherit;background:initial;display:flex;flex: 1 1 0%;
max-width:100%;-webkit-box-pack: end;justify-content: flex-end'></div>

</div>

<div style='box-sizing: inherit;background:initial;display:flex;flex: 1 1 0%;
max-width:100%;-webkit-box-pack: end;justify-content: flex-end'></div>

<div style='box-sizing: inherit;background:initial;display:flex;flex: 1 1 0%;
max-width:100%;-webkit-box-pack: end;justify-content: flex-end'></div>

<div style='box-sizing: inherit;background:initial;display:flex;flex: 1 1 0%;
max-width:100%;-webkit-box-pack: end;justify-content: flex-end'></div>

<div style='box-sizing: inherit;background:initial;display:flex;flex: 1 1 0%;
max-width:100%;-webkit-box-pack: end;justify-content: flex-end'></div>

</div>

<div style='box-sizing: inherit;-webkit-box-align: center;align-items: center;
display:flex;appearance: none;border-image: initial;border-bottom-left-radius: 8px;
border-bottom-right-radius: 8px'>

<div style='box-sizing: inherit;background:initial;display:flex;flex: 1 1 0%;
max-width:100%;-webkit-box-pack: start;justify-content: flex-start'>

<div style='box-sizing: inherit;-webkit-box-align: center;align-items: center;
display:flex;gap: 8px'></div>

</div>

<div style='box-sizing: inherit;background:initial;display:flex;flex: 1 1 0%;
max-width:100%;-webkit-box-pack: end;justify-content: flex-end'></div>

<div style='box-sizing: inherit;background:initial;display:flex;flex: 1 1 0%;
max-width:100%;-webkit-box-pack: end;justify-content: flex-end'></div>

<div style='box-sizing: inherit;background:initial;display:flex;flex: 1 1 0%;
max-width:100%;-webkit-box-pack: end;justify-content: flex-end'></div>

<div style='box-sizing: inherit;background:initial;display:flex;flex: 1 1 0%;
max-width:100%;-webkit-box-pack: end;justify-content: flex-end'></div>

</div>

</div>

<body link="#0563C1" vlink="#954F72">



Risk   group | Amount | Share | Financing fee | Risk adjustment |   | WFF | WRA
-- | -- | -- | -- | -- | -- | -- | --
1 – 1 | 8125938 | 74% | 11% | 0.8% |   | 893853.18 | 65007.50
2 – 2 | 1364989 | 12% | 13% | 5% |   | 177448.57 | 68249.45
3 – 3 | 1547310 | 14% | 17% | 9% |   | 263042.7 | 139257.90
Total | 11,038,238 | 100% | Avg. 12.09% | Avg. 2.47% |   | 1334344.45 | 272514.854
Weighted Avg calc |   |   |   |   |   | 12.09% | 2.47%



</body>

</html>

<img width="799" alt="Screenshot 2022-11-14 at 3 47 56 PM" src="https://user-images.githubusercontent.com/82420771/201762514-11924a9e-3af7-4417-ac4d-4bd3cd6846df.png">

Test case 3: Bridge loan Company Series 1

Weighted Avg Calcs: 
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:////Users/jdanzer/Library/Group%20Containers/UBF8T346G9.Office/TemporaryItems/msohtmlclip/clip.htm">
<link rel=File-List
href="file:////Users/jdanzer/Library/Group%20Containers/UBF8T346G9.Office/TemporaryItems/msohtmlclip/clip_filelist.xml">
<style>

</style>
</head>

<meta charset=utf-8>

<div style='box-sizing: inherit;-webkit-box-align: center;align-items: center;
display:flex;font-variant-ligatures: normal;font-variant-caps: normal;
orphans: 2;text-align:start;widows: 2;-webkit-text-stroke-width: 0px;
text-decoration-thickness: initial;text-decoration-style: initial;text-decoration-color: initial'>

<div style='box-sizing: inherit;text-decoration:initial'>

<div style='box-sizing: inherit;-webkit-box-align: center;align-items: center;
display:flex'></div>

</div>

<div style='box-sizing: inherit;text-decoration:initial'>

<div style='box-sizing: inherit;-webkit-box-align: center;align-items: center;
display:flex'></div>

</div>

<div style='box-sizing: inherit;text-decoration:initial'>

<div style='box-sizing: inherit;-webkit-box-align: center;align-items: center;
display:flex'></div>

</div>

<div style='box-sizing: inherit;text-decoration:initial'>

<div style='box-sizing: inherit;-webkit-box-align: center;align-items: center;
display:flex'></div>

</div>

<div style='box-sizing: inherit;text-decoration:initial'>

<div style='box-sizing: inherit;-webkit-box-align: center;align-items: center;
display:flex'></div>

</div>

<div style='box-sizing: inherit;background:initial;display:flex;flex: 1 1 0%;
max-width:100%;-webkit-box-pack: end;justify-content: flex-end'></div>

<div style='box-sizing: inherit;background:initial;display:flex;flex: 1 1 0%;
max-width:100%;-webkit-box-pack: end;justify-content: flex-end'></div>

<div style='box-sizing: inherit;background:initial;display:flex;flex: 1 1 0%;
max-width:100%;-webkit-box-pack: end;justify-content: flex-end'></div>

<div style='box-sizing: inherit;background:initial;display:flex;flex: 1 1 0%;
max-width:100%;-webkit-box-pack: end;justify-content: flex-end'></div>

</div>

<div style='box-sizing: inherit;background:initial;display:flex;flex: 1 1 0%;
max-width:100%;-webkit-box-pack: end;justify-content: flex-end'></div>

<div style='box-sizing: inherit;background:initial;display:flex;flex: 1 1 0%;
max-width:100%;-webkit-box-pack: end;justify-content: flex-end'></div>

<div style='box-sizing: inherit;background:initial;display:flex;flex: 1 1 0%;
max-width:100%;-webkit-box-pack: end;justify-content: flex-end'></div>

<div style='box-sizing: inherit;background:initial;display:flex;flex: 1 1 0%;
max-width:100%;-webkit-box-pack: end;justify-content: flex-end'></div>

</div>

<div style='box-sizing: inherit;background:initial;display:flex;flex: 1 1 0%;
max-width:100%;-webkit-box-pack: end;justify-content: flex-end'></div>

<div style='box-sizing: inherit;background:initial;display:flex;flex: 1 1 0%;
max-width:100%;-webkit-box-pack: end;justify-content: flex-end'></div>

<div style='box-sizing: inherit;background:initial;display:flex;flex: 1 1 0%;
max-width:100%;-webkit-box-pack: end;justify-content: flex-end'></div>

<div style='box-sizing: inherit;background:initial;display:flex;flex: 1 1 0%;
max-width:100%;-webkit-box-pack: end;justify-content: flex-end'></div>

</div>

<div style='box-sizing: inherit;background:initial;display:flex;flex: 1 1 0%;
max-width:100%;-webkit-box-pack: end;justify-content: flex-end'></div>

<div style='box-sizing: inherit;background:initial;display:flex;flex: 1 1 0%;
max-width:100%;-webkit-box-pack: end;justify-content: flex-end'></div>

<div style='box-sizing: inherit;background:initial;display:flex;flex: 1 1 0%;
max-width:100%;-webkit-box-pack: end;justify-content: flex-end'></div>

<div style='box-sizing: inherit;background:initial;display:flex;flex: 1 1 0%;
max-width:100%;-webkit-box-pack: end;justify-content: flex-end'></div>

</div>

<div style='box-sizing: inherit;-webkit-box-align: center;align-items: center;
display:flex;appearance: none;border-image: initial;border-bottom-left-radius: 8px;
border-bottom-right-radius: 8px'>

<div style='box-sizing: inherit;background:initial;display:flex;flex: 1 1 0%;
max-width:100%;-webkit-box-pack: start;justify-content: flex-start'>

<div style='box-sizing: inherit;-webkit-box-align: center;align-items: center;
display:flex;gap: 8px'></div>

</div>

<div style='box-sizing: inherit;background:initial;display:flex;flex: 1 1 0%;
max-width:100%;-webkit-box-pack: end;justify-content: flex-end'></div>

<div style='box-sizing: inherit;background:initial;display:flex;flex: 1 1 0%;
max-width:100%;-webkit-box-pack: end;justify-content: flex-end'></div>

<div style='box-sizing: inherit;background:initial;display:flex;flex: 1 1 0%;
max-width:100%;-webkit-box-pack: end;justify-content: flex-end'></div>

<div style='box-sizing: inherit;background:initial;display:flex;flex: 1 1 0%;
max-width:100%;-webkit-box-pack: end;justify-content: flex-end'></div>

</div>

</div>

<button tabindex=0
class="DataTable__DataCol-sc-1cwbpyv-1 DataTable__HeaderCol-sc-1cwbpyv-2 fLgYIs didlEl"
style='box-sizing: inherit;background:initial;display:flex;flex: 1 1 0%;
max-width:100%;-webkit-box-pack: start;justify-content: flex-start;-webkit-box-align: center;
align-items: center'>

<div style='box-sizing: inherit;text-decoration:initial'>

<div style='box-sizing: inherit;-webkit-box-align: center;align-items: center;
display:flex'>
<meta charset=utf-8>

<div style='box-sizing: inherit;-webkit-box-align: center;align-items: center;
display:flex;font-variant-ligatures: normal;font-variant-caps: normal;
orphans: 2;text-align:start;widows: 2;-webkit-text-stroke-width: 0px;
text-decoration-thickness: initial;text-decoration-style: initial;text-decoration-color: initial'></div>

</div>

</button>
<button tabindex=0
class="DataTable__DataCol-sc-1cwbpyv-1 DataTable__HeaderCol-sc-1cwbpyv-2 hFHDsX didlEl"
style='box-sizing: inherit;background:initial;display:flex;flex: 1 1 0%;
max-width:100%;-webkit-box-pack: end;justify-content: flex-end;-webkit-box-align: center;
align-items: center'>

<div style='box-sizing: inherit;text-decoration:initial'>

<div style='box-sizing: inherit;-webkit-box-align: center;align-items: center;
display:flex'></div>

</div>

</button>
<button tabindex=0
class="DataTable__DataCol-sc-1cwbpyv-1 DataTable__HeaderCol-sc-1cwbpyv-2 hFHDsX didlEl"
style='box-sizing: inherit;background:initial;display:flex;flex: 1 1 0%;
max-width:100%;-webkit-box-pack: end;justify-content: flex-end;-webkit-box-align: center;
align-items: center'>

<div style='box-sizing: inherit;text-decoration:initial'>

<div style='box-sizing: inherit;-webkit-box-align: center;align-items: center;
display:flex'></div>

</div>

</button>
<button tabindex=0
class="DataTable__DataCol-sc-1cwbpyv-1 DataTable__HeaderCol-sc-1cwbpyv-2 hFHDsX didlEl"
style='box-sizing: inherit;background:initial;display:flex;flex: 1 1 0%;
max-width:100%;-webkit-box-pack: end;justify-content: flex-end;-webkit-box-align: center;
align-items: center'>

<div style='box-sizing: inherit;text-decoration:initial'>

<div style='box-sizing: inherit;-webkit-box-align: center;align-items: center;
display:flex'></div>

</div>

</button>
<button tabindex=0
class="DataTable__DataCol-sc-1cwbpyv-1 DataTable__HeaderCol-sc-1cwbpyv-2 hFHDsX didlEl"
style='box-sizing: inherit;background:initial;display:flex;flex: 1 1 0%;
max-width:100%;-webkit-box-pack: end;justify-content: flex-end;-webkit-box-align: center;
align-items: center'>

<div style='box-sizing: inherit;text-decoration:initial'>

<div style='box-sizing: inherit;-webkit-box-align: center;align-items: center;
display:flex'></div>

</div>

</button>
</div>

<div style='box-sizing: inherit;flex-direction: column;display:flex;font-variant-ligatures: normal;
font-variant-caps: normal;orphans: 2;text-align:start;widows: 2;-webkit-text-stroke-width: 0px;
text-decoration-thickness: initial;text-decoration-style: initial;text-decoration-color: initial'>

<div style='box-sizing: inherit;-webkit-box-align: center;align-items: center;
display:flex;appearance: none;border-image: initial'>

<div style='box-sizing: inherit;background:initial;display:flex;flex: 1 1 0%;
max-width:100%;-webkit-box-pack: start;justify-content: flex-start'>

<div style='box-sizing: inherit;-webkit-box-align: center;align-items: center;
display:flex;gap: 8px'>

<div style='box-sizing: inherit'></div>

</div>

</div>

<div style='box-sizing: inherit;background:initial;display:flex;flex: 1 1 0%;
max-width:100%;-webkit-box-pack: end;justify-content: flex-end'></div>

<div style='box-sizing: inherit;background:initial;display:flex;flex: 1 1 0%;
max-width:100%;-webkit-box-pack: end;justify-content: flex-end'></div>

<div style='box-sizing: inherit;background:initial;display:flex;flex: 1 1 0%;
max-width:100%;-webkit-box-pack: end;justify-content: flex-end'></div>

<div style='box-sizing: inherit;background:initial;display:flex;flex: 1 1 0%;
max-width:100%;-webkit-box-pack: end;justify-content: flex-end'></div>

</div>

<div style='box-sizing: inherit;-webkit-box-align: center;align-items: center;
display:flex;appearance: none;border-image: initial'>

<div style='box-sizing: inherit;background:initial;display:flex;flex: 1 1 0%;
max-width:100%;-webkit-box-pack: start;justify-content: flex-start'>

<div style='box-sizing: inherit;-webkit-box-align: center;align-items: center;
display:flex;gap: 8px'>

<div style='box-sizing: inherit'></div>

</div>

</div>

<div style='box-sizing: inherit;background:initial;display:flex;flex: 1 1 0%;
max-width:100%;-webkit-box-pack: end;justify-content: flex-end'></div>

<div style='box-sizing: inherit;background:initial;display:flex;flex: 1 1 0%;
max-width:100%;-webkit-box-pack: end;justify-content: flex-end'></div>

<div style='box-sizing: inherit;background:initial;display:flex;flex: 1 1 0%;
max-width:100%;-webkit-box-pack: end;justify-content: flex-end'></div>

<div style='box-sizing: inherit;background:initial;display:flex;flex: 1 1 0%;
max-width:100%;-webkit-box-pack: end;justify-content: flex-end'></div>

</div>

<div style='box-sizing: inherit;-webkit-box-align: center;align-items: center;
display:flex;appearance: none;border-image: initial'>

<div style='box-sizing: inherit;background:initial;display:flex;flex: 1 1 0%;
max-width:100%;-webkit-box-pack: start;justify-content: flex-start'>

<div style='box-sizing: inherit;-webkit-box-align: center;align-items: center;
display:flex;gap: 8px'>

<div style='box-sizing: inherit'></div>

</div>

</div>

<div style='box-sizing: inherit;background:initial;display:flex;flex: 1 1 0%;
max-width:100%;-webkit-box-pack: end;justify-content: flex-end'></div>

<div style='box-sizing: inherit;background:initial;display:flex;flex: 1 1 0%;
max-width:100%;-webkit-box-pack: end;justify-content: flex-end'></div>

<div style='box-sizing: inherit;background:initial;display:flex;flex: 1 1 0%;
max-width:100%;-webkit-box-pack: end;justify-content: flex-end'></div>

<div style='box-sizing: inherit;background:initial;display:flex;flex: 1 1 0%;
max-width:100%;-webkit-box-pack: end;justify-content: flex-end'></div>

</div>

<div style='box-sizing: inherit;-webkit-box-align: center;align-items: center;
display:flex;appearance: none;border-image: initial;border-bottom-left-radius: 8px;
border-bottom-right-radius: 8px'>

<div style='box-sizing: inherit;background:initial;display:flex;flex: 1 1 0%;
max-width:100%;-webkit-box-pack: start;justify-content: flex-start'>

<div style='box-sizing: inherit;-webkit-box-align: center;align-items: center;
display:flex;gap: 8px'></div>

</div>

<div style='box-sizing: inherit;background:initial;display:flex;flex: 1 1 0%;
max-width:100%;-webkit-box-pack: end;justify-content: flex-end'></div>

<div style='box-sizing: inherit;background:initial;display:flex;flex: 1 1 0%;
max-width:100%;-webkit-box-pack: end;justify-content: flex-end'></div>

<div style='box-sizing: inherit;background:initial;display:flex;flex: 1 1 0%;
max-width:100%;-webkit-box-pack: end;justify-content: flex-end'></div>

<div style='box-sizing: inherit;background:initial;display:flex;flex: 1 1 0%;
max-width:100%;-webkit-box-pack: end;justify-content: flex-end'><span
style='box-sizing: inherit;text-decoration:initial'></div>

</div>

</span></div>

<body link="#0563C1" vlink="#954F72">



Test Case 3: Bridge Loan Company Series 1 |   |   |   |  
-- | -- | -- | -- | --
Risk group | Amount | Share | Financing fee | Risk adjustment |   | WFF | WRA
1   – A | 45513 | 1% | 9% | 2% |   | 4096.17 | 1092.31
2 – B | 6396613 | 99% | 12% | 3% |   | 767593.56 | 159915.33
3 – C | 0 | 0% | 15% | 4% |   | 0 | 0.00
Total | 6442126 | 100% | Avg. 11.98% | Avg. 2.5% |   | 771689.73 | 161007.637
Weighted Avg calc |   |   |   |   |   | 11.98% | 2.50%



</body>

</html>

On Pools: 
<img width="811" alt="Screenshot 2022-11-14 at 3 49 58 PM" src="https://user-images.githubusercontent.com/82420771/201763444-deb82b9f-0149-4656-8a7b-21a3c17af02a.png">
