### ISSUE TITLE
Centrifuge App: Token price chart on pool detail page

### ISSUE THREAD

**Issue by sophialittlejohn** [centrifuge/apps#1028]
![Screenshot 2022-08-30 at 18.26.55.png](https://images.zenhubusercontent.com/62383c508a17540fc1edb699/9ff53f50-8a67-4485-84a7-9377f3610376)

**Comment by EstherCentrifuge** [comment]
looks ncie please changes as discussed:

4 digets beghind the comma
small range in chart 
from 0.8 to 1.2
see real pricing examples
https://docs.google.com/spreadsheets/d/18jxrGrT8rCXgKfxnMstaqFu0cJDghYMvOnzZ-FIVk6I/edit#gid=1675080861
