### ISSUE TITLE
Public Demo enviornment Faucet

### ISSUE THREAD

**Issue by EstherCentrifuge** [centrifuge/apps#1033]
[HackMd Specs](https://centrifuge.hackmd.io/oXB-xXUzSzO1gKagUiZw1A)
[Slack discussion](https://centrifugehq.slack.com/archives/C7WRB9J4C/p1661337606844779)
[Figma](https://www.figma.com/file/d1bEBkwllUQe27nQM6VlJu/Centrifuge-app---Version-1-(Master)?node-id=6395%3A110171)

## Tech specs

The following setup will be the easiest to deploy since our FE and lambdas are already setup for the cent-app. The only additional deployment necessary will be the firestore db which should cost (basically) nothing.

### UI: Centrifuge-App
Route in cent-app `/faucet` with address input field. No wallet connection, no sidebars, no links, just a plain white page. Will use Fabric components for consistent styling of submit button and address input)

Route will only exist in demo/dev environment

### API: Netlify function (lambda) with Firestore DB connection
- accepts address as input
- creates tx to transfer `1000 DEVEL` and `10'000 aUSD` to supplied address
- submits and signs tx - will require private key to be stored somewhere, gh secret
- handles rate limiting
   - only allow if balance of wallet is smaller than 10 DEVEL and 100 aUSD
   - only allow if DB does not include entry for `walletAddress` and `ipAddress` combo

```json
{
  "timestamp": 123243,
  "walletAddress": "XYZ",
  "ipAddress": "..."
}
```

## UI Spec
The option to "faucet" is available in the toolbar at all times (Global action on every page)
It's stuck to the top, meaning if a 2nd action becames available on a page (like invest/refeem) that action loads below the faucet. 

We should hide the faucet component is the wallet balance is >10 DEVEL and >100 aUSD

![image.png](https://images.zenhubusercontent.com/61fa54b8b520bc58fd924e32/2cd2b252-38b1-4715-9845-2378d7ed0c77)

**Comment by annamehr** [comment]
@sophialittlejohn how can test this? If I go to https://demo.app.centrifuge.io/investments I can still connect to my wallet and don't see the faucet.![Screenshot 2022-10-17 at 12.23.58.png](https://images.zenhubusercontent.com/5af53feb4b5806bc2bd2bad8/f7b17ff9-1bac-40d1-8c2d-44d1bc0f1f17)

**Comment by sophialittlejohn** [comment]
@annamehr some of the deployments were broken, sorry about that! I fixed them so now you should see the `Claim` button 😄

**Comment by annamehr** [comment]
@sophialittlejohn I received this error ![Screenshot 2022-10-18 at 11.19.39.png](https://images.zenhubusercontent.com/5af53feb4b5806bc2bd2bad8/1c97a76d-6777-43ba-98c7-10d629a575e3)

**Comment by annamehr** [comment]
@sophialittlejohn I received this error after clicking on claim button![Screenshot 2022-10-18 at 11.21.37.png](https://images.zenhubusercontent.com/5af53feb4b5806bc2bd2bad8/b93cca2e-319d-44a7-8f4a-d8cf85c82676)

**Comment by annamehr** [comment]
It works now :) created a pool and invested into another pool
