### ISSUE TITLE
Create Asset: Re-prompt user to sign create loan transaction in case it failed

### ISSUE THREAD

**Issue by onnovisser** [centrifuge/apps#1047]
When creating a document and minting an nft, we have the user sign the create loan transaction beforehand, but send it only after the mint completes. This is a bit fragile and the create loan transaction can fail to complete for a few reasons. If the user loses connection or exits the page, the transaction never gets sent. If the job takes too long to complete, the signed transaction expires. If the user does any other transaction while awaiting the job, the signed transaction will no longer be valid. We want to keep track of any pending asset creations and re-prompt the user to sign a new transaction if the original one failed to go through. The idea is to: 
- When clicking Create Asset, execute the actions as normal: create doc, commit and mint, sign loan tx, await commit and mint job, send loan tx
- store the job id and signed tx in local storage
- when the user visits the app again check localstorage for pending loan creations
- if loan creation failed prompt the user to sign again for the loan creation
- same if the loan creation failed while they were still on the page

**Comment by Hornebom** [comment]
Local storage might cut to short here in case the user uses different devices
