### ISSUE TITLE
Update pool & Token list & Add Tinlake details 

### ISSUE THREAD

**Issue by EstherCentrifuge** [centrifuge/apps#1055]
1. The Pool list design are tiles instead of a table we should update this to optimize the mobile view.
[Figma](https://www.figma.com/file/d1bEBkwllUQe27nQM6VlJu/Centrifuge-app---Version-1-(Master)?node-id=12622%3A82847)

2. We want to Remove/hide the capacity column on the token list view
[Figma](https://www.figma.com/file/d1bEBkwllUQe27nQM6VlJu/Centrifuge-app---Version-1-(Master)?node-id=12864%3A84140)
3. Add Tinlake pools and tokens to the lists
[Specs HackMD](https://centrifuge.hackmd.io/qr5ZeoUnS8mKrY0gX1w0mQ#2-Pool-overview-excluding-risk-groups-and-token-price-chart-and-capacity)

Display all tinlake pools on the pool list
Add an indicator that this is an Ethereum pool.
Opon select a pool or token navigate to the pool overview page (same logic as for other pools)
In the design the lower right pool tile has a Ethereum indicator on it. [Figma](https://www.figma.com/file/d1bEBkwllUQe27nQM6VlJu/Centrifuge-app---Version-1-(Master)?node-id=12622%3A82847)

![image.png](https://images.zenhubusercontent.com/61fa54b8b520bc58fd924e32/ddb9e810-584a-4188-b6be-0071d967b0f8)

[Figma Token list](https://www.figma.com/file/d1bEBkwllUQe27nQM6VlJu/Centrifuge-app---Version-1-(Master)?node-id=12864%3A84140)
In the screenshot below you see the bottom tokens have a small Ethereum icon. 
Also note the capacity column is removed/hidden

![image.png](https://images.zenhubusercontent.com/61fa54b8b520bc58fd924e32/bc1a5599-1c50-4011-bc7b-00c227c1c407)

**Comment by annamehr** [comment]
@onnovisser adding the tooltip ticket https://github.com/centrifuge/apps/issues/1164

**Comment by offerijns** [comment]
- It looks like the token price charts are saying “Data unavailable”. Can we just hide this?
- This tooltip is missing: https://github.com/centrifuge/apps/issues/1164
- Can we change Görli to Goerli? :)
- When I cancelled a tx manually in Metamask, the toast got stuck (I can’t close it).
- When trying to redeem, the button just says “Approve BT1TIN”. I would expect an input form here. Why not just show the input first, and then chain Approve + Transfer afterwards? (this is how it works on Tinlake).

**Comment by offerijns** [comment]
Also, we should hide Goerli on production environments of the app. I would add an env var for this, `ENABLE_TEST_NETWORKS`.

**Comment by offerijns** [comment]
The value locked and capacity of Tinlake pools seems to be off, see https://app-demo.k-f.dev/pools

**Comment by annamehr** [comment]
Closing this ticket now. Addressed Jeroen's + my feedback in a seperate issue #1343
