### ISSUE TITLE
J - Suggestion: Ability to create asset template from `.../assets/create`

### ISSUE THREAD

**Issue by sirjared** [centrifuge/apps#1081]
It would be better for Issuers to be able to create asset templates from the create asset page. If the drop down could include the option to "**Create New Template**" would help the issuers to operate more efficiently.

Tag: 

Page Example: https://dev.app.cntrfg.com/issuer/84853979/assets/create

## Current
<kbd><img width="826" alt="Screenshot 2022-11-18 at 3 00 29 PM" src="https://user-images.githubusercontent.com/82420771/202792568-ab82eb7b-d9d1-4585-b479-2ae126e1b654.png"/></kbd>

## Suggestion
<kbd><img width="829" alt="Screenshot 2022-11-18 at 3 00 33 PM" src="https://user-images.githubusercontent.com/82420771/202792618-4987fe4d-da2c-4ef3-9fb9-09e9761b5045.png"></kbd>

**Comment by annamehr** [comment]
Hi Jay, you can create an asset template in the configuration tab

<img width="794" alt="Screenshot 2022-11-21 at 10 58 56" src="https://user-images.githubusercontent.com/31280003/203021536-f5828eb5-e406-4172-a427-96e480418138.png">
<img width="818" alt="Screenshot 2022-11-21 at 10 58 50" src="https://user-images.githubusercontent.com/31280003/203021564-09e01aa2-8add-4160-a9e9-54ff0d71a972.png">
