### ISSUE TITLE
UI fixes 

### ISSUE THREAD

**Issue by annamehr** [centrifuge/apps#1203]
## Background
After a few interviews and a discussion during the product offiste we have found some areas where we can make the app more comprehensible. 

### Pool overview
* Rename `protection` to `subordination`
* Rename tooltip to `The risk protection...` to `The subordination... `

<img width="291" alt="Screenshot 2023-02-17 at 16 55 53" src="https://user-images.githubusercontent.com/31280003/219702901-39a32d18-5192-48a8-869c-ee68f953c5d1.png">

* align the design of the external link. Instead of having four different button style, `View pool account`, `Executive summary`, `Website` and `Email` should be in the same style as Links (Website and Email)

<img width="831" alt="Screenshot 2023-02-28 at 15 32 16" src="https://user-images.githubusercontent.com/31280003/221884703-186d269d-0ae9-4022-a977-b99f57a4f668.png">

### Create pool 

* Rename `min. protection` to `min. subordination`
<img width="877" alt="Screenshot 2023-02-17 at 16 58 57" src="https://user-images.githubusercontent.com/31280003/219703672-eb41734a-a2d5-4dbe-a93d-2bc0c9e5582d.png">

### Pool overview
* change colours of invest buttons to white and hovered with a black shadow instead of highlighting one invest button in orange

<img width="1029" alt="Screenshot 2023-02-20 at 16 20 29" src="https://user-images.githubusercontent.com/31280003/220146705-bcbe4239-5fe0-4b52-9aa2-a3d8056407d5.png">

###  Investment page
* Rename `Investments` to `Pools`
* hide NFTs (left sidebar) tab on Centrifuge network
<img width="1529" alt="Screenshot 2023-02-20 at 16 36 39" src="https://user-images.githubusercontent.com/31280003/220149202-b165610f-3443-4dfa-a882-f87fed82b774.png">

**Comment by Hornebom** [comment]
@annamehr 
pull-request https://github.com/centrifuge/apps/pull/1230
preview https://app-pr1230.k-f.dev/investments

Ticket for renaming 'investments' url is #1229

**Comment by annamehr** [comment]
Thanks Ben! 

One minor comment:
* `Executive summary `font is not as bold as the other options `Email `and `View pool account`. Would it be possible to adjust this? 

<img width="834" alt="Screenshot 2023-03-09 at 17 39 29" src="https://user-images.githubusercontent.com/31280003/224091714-5bebc407-7d6b-41f6-85b1-27a62f34f4d5.png">
