### ISSUE TITLE
Add tooltip and one liner to wallet component

### ISSUE THREAD

**Issue by annamehr** [centrifuge/apps#1241]
[Link to Design](https://www.figma.com/file/9iwvzHuvbjlHXRWlPWRxxc/Centrifuge-app---Version-2-(Branch)?node-id=9580%3A62141&t=TOxzIWFy9ZDJUYj7-0)

## Acceptance Criteria

* As a final touch for the wallet selector, when the user is viewing a pool on a specific network and wants to connect their wallet, the non-supported network options should be greyed out and have a tooltip that says `“This pool does not support investing from the x network.”` The wallet options for the supported network should be visible and for the non-supported network also greyed out.
* Add a one liner below `Need help connecting a wallet? Read our [FAQ](https://docs.centrifuge.io/use/setup-wallet/). `
* Reorganized the wallet order in the dialog

For EVM: Metamask (most used), WalletConnect (second most used), Coinbase
For Polkadot: Talisman, SubConnect, Polkadot.js (least preferred for most users)

## Design
<img width="868" alt="Screenshot 2023-03-13 at 12 16 15" src="https://user-images.githubusercontent.com/31280003/224691573-8d3e9405-2fcb-44a2-9d03-636412e02c0a.png">

**Comment by offerijns** [comment]
@annamehr One small suggestion that I think would make sense to tackle with this ticket: I think it would be better if we reorganized the wallet order in the dialog. My suggestion would be:
- For EVM: Metamask (most used), WalletConnect (second most used), Coinbase
- For Polkadot: Talisman, SubConnect, Polkadot.js (least preferred for most users)

**Comment by annamehr** [comment]
Good point! @offerijns I added your feedback this to the issue
