### ISSUE TITLE
Add proxy support & add verification status in wallet component

### ISSUE THREAD

**Issue by annamehr** [centrifuge/apps#1282]
Originally in the wallet component design the connected address showed the proxied and proxy account, and showed the rights in the dropdown. See first screenshot. Now the component just shows the connected proxy account. 

Design with proxy address and proxy description:
![image](https://user-images.githubusercontent.com/31280003/228355600-e6af54d7-8dd7-42dc-a75a-bd4da9b09fb3.png)

Current design:
![image](https://user-images.githubusercontent.com/31280003/228355707-7e7f1541-5fa8-431b-bdb5-63f27f88ab59.png)

Now that the global onboarding flow is working, we can add the three `Verification status` to the wallet component
* (identity not verified): Verify identity button is visible
* (identity verification in process)
* (identity verification complete)

[Link to Figma Design](https://www.figma.com/file/9iwvzHuvbjlHXRWlPWRxxc/Centrifuge-app---Version-2-(Branch)?node-id=8906-69315&t=DVerWJvMcL1YihpZ-0)

<img width="808" alt="Screenshot 2023-03-28 at 22 15 09" src="https://user-images.githubusercontent.com/31280003/228356529-09297dc7-7893-4883-b06d-814760b72010.png">

**Comment by Hornebom** [comment]
@annamehr Verified status handled in [1309](https://github.com/centrifuge/apps/pull/1309)
