### ISSUE TITLE
Tooltip redesign + add tooltip to wallet selector

### ISSUE THREAD

**Issue by annamehr** [centrifuge/apps#1289]
[Link to Design](https://www.figma.com/file/9iwvzHuvbjlHXRWlPWRxxc/Centrifuge-app---Version-2-(Branch)?node-id=9580%3A62141&t=TOxzIWFy9ZDJUYj7-0)

## Acceptance Criteria

* As a final touch for the wallet selector, when the user is viewing a pool on a specific network and wants to connect their wallet, the non-supported network options should be greyed out and have a tooltip that says “This pool does not support investing from the x network.” The wallet options for the supported network should be visible and for the non-supported network also greyed out.

## Design
<img width="868" alt="Screenshot 2023-03-13 at 12 16 15" src="https://user-images.githubusercontent.com/31280003/224691573-8d3e9405-2fcb-44a2-9d03-636412e02c0a.png">

**Comment by Hornebom** [comment]
@annamehr Resolved in https://github.com/centrifuge/apps/pull/1317
