### ISSUE TITLE
Onboarding subscription document wording change

### ISSUE THREAD

**Issue by annamehr** [centrifuge/apps#1315]
* `Complete subscription agreement` to `Read the subscription agreement and click the box below to automatically e-sign the subscription agreement. You don't need to download and sign manually.`
* ` I hereby agree to the terms of the subscription agreement `to `I hereby sign and agree to the terms of the subscription agreement`

<img width="999" alt="Screenshot 2023-04-18 at 15 42 16" src="https://user-images.githubusercontent.com/31280003/232796713-45ee6ef3-a4dc-4556-8a84-8bb789291b27.png">

**Comment by Hornebom** [comment]
@annamehr Solved here https://github.com/centrifuge/apps/pull/1322
