### ISSUE TITLE
Disable onboarding to RWA Market on Aave

### ISSUE THREAD

**Issue by annamehr** [centrifuge/apps#1325]
* Adapt the[ RWA Market UI](https://rwamarket.io/#/deposit/0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48-0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb480xb953a066377176092879a151c07798b3946eea4b) to not link to the old onboarding flow anymore
* Remove the text and button
* Add the text “Currently, it is not possible to onboard to the RWA market."
* Code can be changed here: https://github.com/centrifuge/aave-ui/blob/master/src/ui-config/branding/PermissionWarning/index.tsx#L78

## Design
<img width="964" alt="Screenshot 2023-04-21 at 18 27 40" src="https://user-images.githubusercontent.com/31280003/233687682-78e40fd0-fcba-4ee4-905c-d02273e96438.png">

**Comment by Hornebom** [comment]
@annamehr I opened a PR: https://github.com/aave/aave-ui/pull/576
