### ISSUE TITLE
Move back button to the left side of the screen

### ISSUE THREAD

**Issue by TimHoub** [centrifuge/apps#1361]
Current implementation of the back button is on the right side but for better UX 
* move back button to the left side of the screen

 
## Design
[Figma link](url)
<img width="973" alt="Screenshot 2023-05-11 at 14 10 49" src="https://github.com/centrifuge/apps/assets/131260516/a82ab250-59b1-4ae9-915d-d2fa68bfb625">

**Comment by TimHoub** [comment]
https://www.figma.com/file/9iwvzHuvbjlHXRWlPWRxxc/Centrifuge-app---Version-2-(Branch)?type=design&node-id=10976%3A78617&t=u7shhTCH3qLppTb4-1

**Comment by annamehr** [comment]
not relevant as of today
