### ISSUE TITLE
Tinlake pools onboarding restrictions

### ISSUE THREAD

**Issue by annamehr** [centrifuge/apps#1371]
## Background
There are different requirements for pools and tranches on Ethereum. 

## Acceptance criteria
* For BT pools (BT1, BT2, BT3, and BT4) disable `invest button` and `onboard/invest/redeem box` for non-members of the TIN tranche
* For BT pools (BT1, BT2, BT3, and BT4) disable `invest button` and do not show `onboard/invest/redeem box` for the DROP tranche 
* Disable invest button for TIN tranches of all pools for and show the following button that links to the issuer's email 
* All emails can be found [here](https://docs.google.com/spreadsheets/d/1diamMcByel1ajFXsW41W2oja7ePvk2OnJBGKDLHsOa0/edit#gid=0)

<img width="761" alt="Screenshot 2023-05-12 at 15 40 49" src="https://github.com/centrifuge/apps/assets/31280003/13011859-1360-4221-8349-0cb5666e2ce0">

**Comment by jpangelle** [comment]
Do we also want to restrict users from onboarding to pools that are closed?

**Comment by annamehr** [comment]
yes please
