### ISSUE TITLE
Bugs 

### ISSUE THREAD

**Issue by annamehr** [centrifuge/apps#1404]
- [x] The issuer name in the executive summary modal is hardcoded to `New Silver 2` but the issuer name is `NS Pool LLC`
![](https://storage.googleapis.com/centrifuge-hackmd/upload_3bf6ecb46388cf262b762d7dd4696073.png)
- [x] The value locked for each pool on the pool list page does not match the value locked on the pool overview page. E.g. BT4 on the pool list is 97M and on the overview 100M.
<img width="270" alt="Screenshot 2023-05-22 at 12 45 02" src="https://github.com/centrifuge/apps/assets/31280003/3c41cbe1-95d5-4629-957c-f8d7e15a4507">

- [x] When you click on the data sharing agreement, this suddenly talks about Shufti Pro without any context. We could add a line above this to introduce it, e.g. "KYC and KYB verifications for this pool are performed by Shufti Pro, a third-party service provider."
![](https://storage.googleapis.com/centrifuge-hackmd/upload_9bce99ed0f6ca4ccab21b0ef9c837949.png)
- [x] Add the pagination component to the assets tab for some of the Tinlake pools the list is very long. 
- [x] Token yields on pool overview page are shown as APYs even though they're currently APRs 
![](https://storage.googleapis.com/centrifuge-hackmd/upload_17952495411a8f6792844af3736e0457.png)
- [x] There's an unnecessary `"` quote in the copy of the first onboarding screen.
![](https://storage.googleapis.com/centrifuge-hackmd/upload_edc68b3e31a5d40e58dec628c67ee747.png)

**Comment by Hornebom** [comment]
Gonna start with 1

**Comment by onnovisser** [comment]
Will pick up nr 4
