### ISSUE TITLE
Add link to documentation 

### ISSUE THREAD

**Issue by annamehr** [centrifuge/apps#1414]
- [ ] Add link to documentation at the bottom  - link: https://docs.centrifuge.io/ 
<img width="177" alt="Screenshot 2023-05-24 at 13 06 00" src="https://github.com/centrifuge/apps/assets/31280003/c0625f84-12fd-4ea0-822a-91fb8eb69065">

**Comment by TimHoub** [comment]
Added it to the main navigation component that I found in figma.
https://www.figma.com/file/d1bEBkwllUQe27nQM6VlJu/Centrifuge-app---Version-1-(Master)?type=design&node-id=3481%3A111851&t=kby1hoV67jtl4uye-1

I did place the documentation link as the first one, can still be discussd, but I thought it would make sense to have this one as a first item.
