### ISSUE TITLE
Improve locking NFT flow

### ISSUE THREAD

**Issue by denniswell** [centrifuge/apps#144]
Ready for dev:
- [x] (i) Display of Lock NFT button
This is confusing for users other than the AO. Only the borrower address should see it, so
Only display lock NFT button when (i) accessed with URL `lockNFT=true` or connected address as a proxy for this pool
- [x] Confirmation for locked NFT
AOs usually stay on the `Lock NFT` page and are confused when nothing happens. When they do stay on the page and an NFT is succesfully locked, we should at least show a message box: "Your NFT is succesfully locked. Please proceed to the [Asset list](link to Asset tab) to finance this NFT. Doesnt need to be pretty, only AOs see it, similar to kovan boxes is fine
- [x] Hide Finance/repay buttons instead of deactivate
I know we had the discussion and I was wrong. After seeing this in action with a few handholdings, it is much clearer if
Until the first financing - Only the Financing button is show, Repay is hidden
After the first financing - Financing button is hidden, value in input field is 0 and only repay button is shown
(iv) Rename and move`close` loan button
Rename `Close` button to `Unlock NFT`. Can remain secondary button. Only display before first borrowing, otherwise hide. The button should be moved into top right corner, where the 'Lock NFT' button is also positioned

**Comment by lucasvo** [comment]
Instead of requiring a feature flag in the URL for "lockNFT" why don't we check if the connected address has a tinlake borrower proxy and can use the pool?

**Comment by denniswell** [comment]
> Instead of requiring a feature flag in the URL for "lockNFT" why don't we check if the connected address has a tinlake borrower proxy and can use the pool?

This is a hen and egg problem for the first NFT, as to create the borrower proxy you need the "lock NFT" button. Thus, for first financing --> feature flag, afterwards --> automatically displayed if proxy exists...
