### ISSUE TITLE
Onboarding bug in step 5

### ISSUE THREAD

**Issue by annamehr** [centrifuge/apps#1465]
Environment: Mac, Brave and Chrome

* User signs subscription document and after a successful signing transaction the user is stuck in step 5 and can't continue without showing an error message. 
* Once the transaction is signed, the user can click on the sign button multiple times. 
* I noticed that the link to chain explorer is directing user to subscan instead of etherscan. 

Expected behaviour:
* User sigs subscription document once and gets redirected to the final step 

<img width="1510" alt="Screenshot 2023-06-16 at 14 51 52" src="https://github.com/centrifuge/apps/assets/31280003/a409f379-6b0c-4a9e-81a8-cb04641d51d8">

**Comment by sophialittlejohn** [comment]
Fixed by uploaded the signature and acceptance page to the cloud bucket.
