### ISSUE TITLE
Integrate Discourse for pool status/updates

### ISSUE THREAD

**Issue by offerijns** [centrifuge/apps#155]
Problem: For investors it is a major pain point, that they have no idea what is currently going on with the pools. When will they be closed for investments? When will the open again? Why are they closing and opening? 

Solution:
We need to find a way for the AOs to communicate about the current and upcoming pool status. Allowing updates e.g. through the pool config is operationally not scalable. Idea is to add updates by integrating a Discourse thread (similar to Twitter feed integration on other apps). This would also lead more users to Discourse

Example of pool update post in Discourse:
https://gov.centrifuge.io/t/issuer-new-silver/401/6

How to display:
We've worked on displaying a twitter feed:
![image.png](https://images.zenhubusercontent.com/5c922180cf9c5c1a350a748b/331587d2-5bad-48e5-b5a7-4b6d1110c397)

Acceptance criteria:
For every pool the UI displays the most recent post of a "Discourse Pool updates thread" 
[RESEARCH] We need to make sure that in this thread only the AO can post
There should be a link to the Discourse thread that opens in a new tab
Nice to have: You can scroll through the posts/updates within the component

Open questions: 
How to make sure, that only AO messages are picked up?

**Comment by lucasvo** [comment]
Discourse offers an API that allows us to get posts. [API Docs here](https://docs.discourse.org/#tag/Topics/paths/~1t~1{id}~1posts.json/get)

We can create a lambda function that authorizes with the discourse API and allows us to pull posts from it without having to authenticate in the frontend and deal with CORS etc.

**Comment by onnovisser** [comment]
Discourse only returns HTML, so If we want to render it, we should something like [DOMPurify](https://github.com/cure53/DOMPurify) to prevent any XSS. Post can also be rather long, so to keep the feed scanable, we could use something like [truncate-html](https://www.npmjs.com/package/truncate-html) to show only a preview.

The pool config already contains discourse links for some pools, but they're not structurally the same. Should each pool have a separate field in their config for a discourse topic where they post updates?
Also if we want to show only posts by the AOs, we should either make sure these topics always have the AO as the original poster (which is currently not always the case), or have an additional field in the pool config for the userId of the AO, so we can filter the messages by that user.
