### ISSUE TITLE
Portfolio - Additional state: when user has investment in tinlake pool → anchor link to tinlake/portfolio

### ISSUE THREAD

**Issue by TimHoub** [centrifuge/apps#1612]
For the portfolio page, we need some kind of notification and anchor link that tells the user he has investments on Tinlake. We’ll send the user back to Tinlake to view their investments.

**Comment by TimHoub** [comment]
Design is final @annamehr 
https://www.figma.com/file/w5svs3Peu6obgsD79tMbQj/Portfolio-MVP---V1?type=design&node-id=1109%3A9764&mode=design&t=OBtTn3isi0xdGZqw-1

**Comment by TimHoub** [comment]
You can move it

**Comment by annamehr** [comment]
closing this design ticket because it is already part of #1594
