### ISSUE TITLE
Show repay input debug flag 

### ISSUE THREAD

**Issue by onnovisser** [centrifuge/apps#1643]
[Slack thread](https://kflabs.slack.com/archives/C04GARZ532T/p1697624178543009)

Add a debug flag to show 2 additional inputs on the loan repay form. When enabled it adds an Interest and Other field (same format, input requirements as the existing input field) to the repayment component. Interest goes to interest, Other to unscheduled amount.

**Comment by mustermeiszer** [comment]
Closed with new asset flows
