### ISSUE TITLE
Update whitelist components

### ISSUE THREAD

**Issue by denniswell** [centrifuge/apps#167]
- Background: Whitelisting will be automated, but manual workarounds may still be required and in particular removing someone from the memberlist needs to be done manually. This can be done through etherscan, but AOs should be also be able to whitelist and more importantly unwhitelist investors soon
- Currently the components only allow to whitelist / dd member (with a date set 10 years into the future
![](https://storage.googleapis.com/centrifuge-hackmd/upload_751fba05121eb19f7992b0f8566a7e02.png)
- Solution: Add secondary button `Remove` member (to the left of `Add`); Header should be Add/remove TIN/DROP member
- Click on `Remove` should call `update member` function with the date set to yesterday

**Comment by jpangelle** [comment]
Currently, the confirmation toast displays: `Add 0xXXXXXX... to TIN/DROP`. Should I update the verbiage to: `Remove 0xXXXXXX... from TIN/DROP` when a member is being removed?

![image](https://user-images.githubusercontent.com/28536523/112044285-a2657980-8b17-11eb-9a1a-65f63ef1d714.png)

**Comment by denniswell** [comment]
Ah, yes, please do. This makes sense
