### ISSUE TITLE
Axelar integration for Liquidity Pools investments

### ISSUE THREAD

**Issue by onnovisser** [centrifuge/apps#1672]
See how hard it would be to integrate estimating and paying gas in the same transaction as a Liquidity Pools transaction that requires bridging.

1. Estimating gas: https://docs.axelar.dev/dev/axelarjs-sdk/axelar-query-api#estimategasfee
2. Paying gas: https://docs.axelar.dev/dev/general-message-passing/gas-services/pay-gas
3. Multicall3 multicall transaction: Should be the same as reads, by calling `aggregate3` without `staticCall`

Actually, multicall won't work, because of the liquidity pool contracts relying on `msg.sender`. So the gas would have to be paid in a separate tx

**Comment by hieronx** [comment]
Replaced by router v2 integration
