### ISSUE TITLE
Transfer debt between assets

### ISSUE THREAD

**Issue by annamehr** [centrifuge/apps#1689]
[Design](https://www.figma.com/file/uGj5xTQRggmzB4NMji9lxo/Assets?type=design&node-id=206-2690&mode=design&t=hZt3KyhWVJ3ac9WW-0)
[Product Specs](https://centrifuge.hackmd.io/nYk3zAG6TlO04XQBKFlojg)

## Background
Anemoy is already live and is our most important issuer. The current infrastructure makes it impossible to price the asset at the correct price. Using`transferdebt` feature will solve to pressing issues for them.

### Correct pricing data for Anemoy
* There is one existing non-interst bearing "Settlement NFT" or "Settlement NFT". This is used with expected parameters to draw down funds, send funds to the broker to buy t-bills, then get the correct pricing data, then mint an asset NFT and then transfer debt from asset 1 to asset 2 with the correct pricing data.

### Transfer debt between assets to circumvent offramp/onramp
* A New Silver pool receives a repayment of a loan in USD in their bank account. They now want to use these USD to give out a new loan. 
* Current flow of funds would be 
1. close the existing loan on chain
2. convert USD to pool currencyrepay onchain (close epoch)
3. re-borrow the same amount on new asset in USDC/DAI
4. Convert this back to USD
5. Transfer to new borrower. 

`Transferdebt` is the easy workaround if no redemption is locked. The issuer keeps the USD, and directly transfer the USDC/DAI debt between the two different assets within the pool. 

There will be two NFTs
* Settlement NFT the first asset that is created.
* Target NFT - the asset where the debt gets transferred to

### Flow
1. First onchain tx - normal borrow transaction
    * Onchain tx: Borrow expected amount from settlement NFT (first asset that is minted) to borrower wallet and buy treasuries off-chain

2. Second transaction - add final settlement price and amount on the correct asset NFT (externally priced) and settle pool accounting.
    * Onchain tx: Transfer funds internally from Settlement account NFT (source) to asset NFT (target) with final parameters with the new UI component. 
    * **This is a batched repay transaction of the settlement NFT and a borrow transaction of the asset NFT that goes internally through the reserve (as a mental model, not in real flows) instead of the issuers wallet** 
    * Onchain input: Repay of source asset (settlement NFT), Principal 
    * Borrow transaction onchain input: quantity
    * The subquery will pick up the`TransferDebt event` and generate loan borrowed and repaid transactions

**Calculations**
* `Principal = (Face Value * Price) / Notional ), Interest = 0, Unscheduled = 0`
* Borrow of target asset
    *  `Quantity = Face Value/Notional`

### Asset Detail page
**Design: copy changes pending**

![](https://storage.googleapis.com/centrifuge-hackmd/upload_b3149f18ef3da3a38f82bd15d6560567.png)

* New action separate from financing & repaying. This should only be shown if debt > 0.
* The `Borrower` (who can also finance and repay) has the right to fulfil this action
* This should call `batch(loans.propose_transfer_debt, loans.apply_transfer_debt)`. Currently there is a restriction that one epoch needs to be closed before this can apply, but protocol will remove this restriction.

**Inputs**
* Dropdown 
    * The dropdown will display all assets that have been financed and are ongoing 
    * Format Asset ID + Asset Name (example: 7 - 912797GQ4)
* Face value
* Settlement price 
    * Face value and Settlement price can have unlimited decimal places (if possible) to not cause any rounding errors
* `Total amount = Face value*Settlement price`
* Display total amount in pool currency
* The UI should make sure that the final transfer amount is smaller then the amount held by the settlement account NFT.

## Out of scope for now  (requires subquery work and Embrio has been briefed)
* Show Transfers in the asset transaction list 
* Outgoing transfers need to be shown as Sale with the same parameters as actual sales/repays
    * Transaction date = Time/date of transfer
    * The calculation of Position needs to include the transfers as well

**Comment by TimHoub** [comment]
![Image](https://github.com/centrifuge/apps/assets/131260516/78f4dccb-7d4c-4d8a-8888-df9aa5a7a5e9)
