### ISSUE TITLE
Follow up Portfolio page overview graph

### ISSUE THREAD

**Issue by annamehr** [centrifuge/apps#1724]
Some minor UI improvements that are a not in line with the design yet.

* Reduce the spacing between composition table and beginning of the grey container to 8px 
* Spacing between  title' holdings and the graph, 24px
* For the active state on the filter, the non active items should have a font weight that is lighter than the active one. 
![Image](https://github.com/centrifuge/apps/assets/31280003/44a89905-1d11-45ff-8c3a-498b5d7987ea)

* The filter alignment should be on the same width as the right side of the graph, now it is bit too much to the right.
![Image](https://github.com/centrifuge/apps/assets/31280003/ba13fdfd-b11f-4a94-9e63-ddc2695fa128)

**Comment by jpangelle** [comment]
addressed
