### ISSUE TITLE
Beta flag for Liquidity Pools wallet selector + Celo

### ISSUE THREAD

**Issue by annamehr** [centrifuge/apps#1731]
* Add beta flag to upcoming Liquidity Pools on Base and Arbitrum
* Add Celo as a new network with beta flag

**Comment by TimHoub** [comment]
<img width="1274" alt="Screenshot 2023-12-06 at 11 20 42" src="https://github.com/centrifuge/apps/assets/131260516/fca24c81-f61e-4c40-b533-c4160c66b7e5">

Proposal for the beta flag.
Same styling as our tags that we use, just a different colour. I looked at other platforms and seems that this pinkish/red colour is pretty common for Beta tags.

Specs:
- Align with top of the chain logo
- 4px to the right
- Height 16 px
- #F81071
- Font size: 10px

**Comment by TimHoub** [comment]
Design file here, I added it next to the Avalanche chain because that was already in the design
https://www.figma.com/file/9iwvzHuvbjlHXRWlPWRxxc/Centrifuge-app---Version-2-(Branch)?type=design&node-id=11702%3A93409&mode=design&t=vf6aMgOl4weWKks7-1
