### ISSUE TITLE
Pool detail page: token cards 

### ISSUE THREAD

**Issue by annamehr** [centrifuge/apps#1738]
[Figma Design](https://www.figma.com/file/ng7qdNcSCXSDA6ZUdWIs6u/Pool-Overview%2F-Pool-Detail?type=design&node-id=979-5342&mode=design&t=UwK1sdWfDYRnUpd8-0)

## Background
The pool token cards are part of the pool detail redesign and can already be implemented in the current page. 

## Requirements
* Token name will be displayed at the top with token name first and then the token symbol in brackets
* Example token name: Anemoy Liquid Treasury Fund 1 (LTF)
* Below the APY of the tranche, if the token is less than 30 days old the APY is not yet available and should be displayed as `N/A`
* Token price 
* Value locked 
* Tooltip for APY junior token: `The 30d junior yield is the effective annualized return of the pool's junior token over the last 30 days.`
* Tooltip APY senior token: `The 30d senior yield is the effective annualized return of the pool's senior token over the last 30 days.`
* Subordination tooltip: `The subordination is the minimum value of the junior token in relation to the pool value. It denotes how much of the pool is always protected by the junior tranche against asset defaults.`
* Invest button leads to the invest slide over and the investment component of the related token 

## Unitranche

![Image](https://github.com/centrifuge/apps/assets/31280003/9e7abf67-fe03-4403-8154-5cfc703d9dbb)

## Two tranches
![Screenshot 2023-12-21 at 11 52 21](https://github.com/centrifuge/apps/assets/31280003/9a988ad1-2b28-47c1-adc2-7cefd37a6ece)

Part of #1741 

![Image](https://github.com/centrifuge/apps/assets/31280003/60c26c0b-71f3-4793-861b-b0098ded53f5)

**Comment by jpangelle** [comment]
blocked, waiting for design decisions

**Comment by TimHoub** [comment]
@jpangelle the final component can be found here: 
https://www.figma.com/file/aGu64OaUlVsss2LXUq2FPk/Components?type=design&node-id=5726%3A1368&mode=design&t=DONTHP2QBCyBHxc9-1
