### ISSUE TITLE
Portfolio bugs

### ISSUE THREAD

**Issue by annamehr** [centrifuge/apps#1757]
- [x]  Transaction history table: Date column is missing a capital D 
![](https://storage.googleapis.com/centrifuge-hackmd/upload_d0e03612bf9d879de50d368d7b2b97d9.png)
- [x] The Portfolio and History tabs don't show up when you're on the Issuer tab
- [x] The Portfolio card on the Pools page should be removed
<img width="570" alt="Screenshot 2023-12-11 at 10 35 05" src="https://github.com/centrifuge/apps/assets/31280003/39d3a72d-67b7-400c-ae76-7a8b7cf13e51">

- [x] Hide sections (e.g. transaction history, history menu item) that can't load if the subquery is down

<img width="301" alt="Screenshot 2023-12-11 at 10 39 17" src="https://github.com/centrifuge/apps/assets/31280003/570f0513-bfba-4201-b148-fbf82216c287">

- [ ]  TVL graph on Pools overview looks different

OLD
![](https://storage.googleapis.com/centrifuge-hackmd/upload_279749a79ee338e641b0f72b36a336f7.png)

NEW
![](https://storage.googleapis.com/centrifuge-hackmd/upload_ff8657e2425239775c94501fe48c3aa0.png)

**Comment by jpangelle** [comment]
> The Portfolio and History tabs don't show up when you're on the Issuer tab
This issue is addressed in this PR #1773

**Comment by jpangelle** [comment]
>  TVL graph on Pools overview looks different

This is a non-issue and is only surfacing on dev chain since values submitted on chain in the past are incorrectly enormous. This is causing issues with the area graph sizing.
