### ISSUE TITLE
Follow up investment slide over

### ISSUE THREAD

**Issue by annamehr** [centrifuge/apps#1775]
[Figma design](https://www.figma.com/file/egKzXqF777A35BZMzPcoYD/Portfolio?type=design&node-id=343-36780&mode=design&t=20zBEvosHDKtVScS-0)

## Requirements
* Add price chart of tranche token
  * Filters: 30 days, 90 days, YTD, All
  * Price is displayed in native pool currency
  * Price increase displayed in percentage and green font colour based on the filter
  * Display tranche token prices with 5 decimals

![Image](https://github.com/centrifuge/apps/assets/31280003/06f4f9be-98da-4d2e-91ce-700779c9320e)

**Comment by hieronx** [comment]
I'd separate 
- Price chart of tranche token
- Display tranche token prices with 5 decimals
- Double check transaction table when subquery is back

And later implement
- Cost basis/Profit

Because that will be technically more complex
