### ISSUE TITLE
Input fields (text area and fileupload)

### ISSUE THREAD

**Issue by annamehr** [centrifuge/apps#1778]
- [Replace file upload button](https://www.figma.com/file/aGu64OaUlVsss2LXUq2FPk/Components?type=design&node-id=5736%3A3380&mode=design&t=JDxi9tqmVZxFRbmW-1)
![Image](https://github.com/centrifuge/apps/assets/31280003/9c9f2208-9ede-4fb7-8e41-804de7ff33f1)

- [Large text input button ](https://www.figma.com/file/aGu64OaUlVsss2LXUq2FPk/Components?type=design&node-id=1397-4080&mode=design&t=RJC64hALaYoc6Xpm-0)

![Image](https://github.com/centrifuge/apps/assets/31280003/0f4400d9-93f0-426a-a594-669e4532ca1a)

**Comment by TimHoub** [comment]
https://www.figma.com/file/aGu64OaUlVsss2LXUq2FPk/Components?type=design&node-id=5736%3A3380&mode=design&t=JDxi9tqmVZxFRbmW-1

Added the 'upload file' - created a separate component for now.
