### ISSUE TITLE
Open CFG/EVM slide over from wallet

### ISSUE THREAD

**Issue by annamehr** [centrifuge/apps#1782]
## Background

In order to create a smoother UX, the user can click on the CFG balance in the wallet and then the slide over will open up with the send component. 

## Requirements
* Make the CFG balance clickable 
* When clicking on the CFG balance, open the CFG EVM slide over (SEND)

## CFG balance in wallet 
![Image](https://github.com/centrifuge/apps/assets/31280003/5400e064-d425-4c94-ac10-2349b3088fdb)

## CFG EVM slide over 
![Image](https://github.com/centrifuge/apps/assets/31280003/976ef38f-0286-4614-a6c1-252052b09da3)

**Comment by TimHoub** [comment]
Few things we can do here. 
- First cue would be to change the cursor image on hover. Atm it changes to a 'test input' style -> this should be a hand to indicate an action can be triggered.
- Second: We can underline the CFG token amount to show an action is behind it. (not sure if needed if we already do the hand on hover icon)
- Third and most obvious is adding an icon or tertiary button below/next to the CFG amount. This would indicate an action can be triggered
