### ISSUE TITLE
Reorder and hide testnets on network selector

### ISSUE THREAD

**Issue by annamehr** [centrifuge/apps#1795]
* Hide testnets (Arbitrum Görli, Base Görli, Celo Aljajores) on mainnet and only display on testnet.
* Put Ethereum first before Centrifuge in network list
* New order (Ethereum, Centrifuge, Base, Arbitrum, Celo)
* Remove Beta labels 

![Image](https://github.com/centrifuge/apps/assets/31280003/806e1ba8-64f6-4fa3-acbc-7157ac7b6a67)

**Comment by onnovisser** [comment]
testnets are already hidden in production by default. they're shown on the prod preview because it's on the k-f.dev domain
