### ISSUE TITLE
Restricted transfer bug

### ISSUE THREAD

**Issue by annamehr** [centrifuge/apps#1818]
The trusted address should be restricted based on the pool currency transferability type. If it’s transferability: XCM  (e.g. for USDC), only parachain and local addresses should be allowed as trusted addresses. If it’s transferability: LP  , only evm addresses on the associated evm chain should be allowed.

**Comment by mustermeiszer** [comment]
Example: 

* AssetHub Restriction &rarr; sets restriction for XCM, which is correct, but only for `LpEthUSDC` not for `USDC` which is the currency that is actually transferable to AssetHub

Info: 
* Restrictions work on a `AccountId`-`CurrencyId`-pair so it would be best to restrict all currencies that are relevant for a pool manager - my best guess would be that these are `PoolCurrency` itself and all currencies that allowed to be used for investments

**Comment by mustermeiszer** [comment]
@onnovisser can you ping me for a possible review on this one here?

**Comment by onnovisser** [comment]
Updated description based on Slack conversation

**Comment by onnovisser** [comment]
@annamehr When adding withdraw addresses on the access tab, it should only allow you to select valid destinations. For the usual pools that would be Centrifuge and Asset Hub. For pools which use a currency from a specific EVM chain, like this pool on demo for example (https://app-demo.k-f.dev/issuer/1234/access) it should allow you to select EVM chains.

@mustermeiszer when the `transferability` is `LiquidityPools` and the `GlobalConsensus` EVM chain id is 5, can it only be transferred to that chain or also to other chains?

**Comment by mustermeiszer** [comment]
>@mustermeiszer when the transferability is LiquidityPools and the GlobalConsensus EVM chain id is 5, can it only be transferred to that chain or also to other chains?

Only to chain id `5`.

**Comment by mustermeiszer** [comment]
Feature Review: 

Pool: 
Deployed to: `Sepolia` - 

### Problems
* Can not select Sepolia address as valid target
![image](https://github.com/centrifuge/apps/assets/28841470/3364ba06-d5d6-416d-b700-0e4af7f924bb)

* Can not set trusted address without setting pod entries
![image](https://github.com/centrifuge/apps/assets/28841470/4ad5eabe-5e9d-44ca-80d7-e377be932caa)

* Call on Centrifuge chain fails to decode
![image](https://github.com/centrifuge/apps/assets/28841470/49125002-5e4a-4b7e-9351-9090de71eb25)
  ```
   createType(Call):: Call: failed decoding transferAllowList.addTransferAllowance:: Struct: failed on args: {"currency_id":"{\"_enum\":{\"All\":\"Null\",\"Specific\":\"CfgTypesTokensCurrencyId\"}}","receiver":"{\"_enum\":{\"Local\":\"AccountId32\",\"XCM\":\"H256\",\"Address\":\"CfgTypesDomainAddress\"}}"}:: Struct: failed on currency_id: {"_enum":{"All":"Null","Specific":"CfgTypesTokensCurrencyId"}}:: Cannot map Enum JSON, unable to find 'LocalAsset' in all, specific
  ```
