### ISSUE TITLE
Pool fees: Centrifuge.js logic + fees UI

### ISSUE THREAD

**Issue by annamehr** [centrifuge/apps#1859]
[Pools fees protocol spec](https://centrifuge.hackmd.io/3DvencHbSJGgkZCaFFiYcw?both)
[Protocol fees on forum](https://gov.centrifuge.io/t/introducing-pool-types-and-modifying-the-pop-and-protocol-fees-to-better-align/5666)
[Figma design](https://www.figma.com/file/cn5CiQsuVDOmieszqcneX2/Pool-management?type=design&node-id=1-9&mode=design&t=ij0Itnam2uke4E5l-0)

## High level summary pool fees
Protocol and pool fees implementation onchain is almost done. While the onchain implementation is rather open in terms of fee options, in the app, there will be basically two fee types to chose from:

* Percentage of Assets Under Management (AUM) / Fixed fees (e.g. protocol fees)
Set an annual fee in bps based on NAV.
The fee is set as parameter on-chain.
It is calculated and disbursed automatically at every epoch.

* Direct charge (e.g. service fees) / Charge lump sum amount up to a certain limit
The limit will be set as parameter on on-chain
Amounts need to be locked by approved address during/ahead of the epoch and will be disbursed automatically at the end of the epoch.
Amounts above the reserve can roll over to the next epoch. 

All charged fees and fixed percentages will be automatically disbursed from the Reserve to assigned addresses given liquidity (if not enough liquidity the pending fees will roll over and be executed the next epoch)

Per address/issuer/service provider there can be one of the above or both options. So an issuer can set an annual fee of 50bps and still charge extraordinatry costs if needed.

Protocol and pool fees sit on top of the waterfall ahead of investments and redemptions.
Protocol fees will always be served first.
Pool fees are represented by an ordered list of the above two fee types with assigned parameters and addresses.
The priority of fees within this list can be defined by the pool admin.

Fees are always **charged in the pool currency**

The reserve and NAV values need to be decreased by the same disbursable fee amount because fees have a negative impact on the pool valuation.

## Specs for implementation
* A new fees tab in the app that displays the fee structure
* small change to the create pool form to include pool fees

**Fees tab** (only pool admin can view and make edits) 
- Show the pool admin the current fee structure, allow to make edits, and charge "chargeable fee" amounts
- The fee structure table consists of:
`Name` (Protocol fee, Priority fee, Management fee, Standard fee)
`Type` (Options “Fixed % of NAV” | “Direct charge”)
`Percentage`
`Pending fees` in pool currency (This shows the currently pending/not executed fees grabbed from onchain data)
`Receiving address`

<img width="533" alt="Screenshot 2024-01-17 at 13 47 33" src="https://github.com/centrifuge/apps/assets/31280003/a1506fd1-adff-42b0-ad29-333c1f017e67">

**Charge fees**
* When clicking on `Charge`, the slide over will slide in and shows a similar UI to the invest/redeem component where the pool admin can enter a USDC amount.
* This is only possible for `Direct charge` fees; Fixed % of NAV will be automatically deducted. 
* Any amount can be entered but not more than the set limit (% of NAV) can get charged with the next epoch, if the amount is higher than the limit, the amount will be split between the upcoming epochs. 
* If pending fees > 0; show current pending fees and option to change or cancel order
* If pending fees 0; create new fee order.  
* Keep the same header, Display Charge + Fee name
* After placing a fee order, fees can be edited and cancelled (similar to investments and redemptions). 
<img width="318" alt="Screenshot 2024-01-18 at 12 34 36" src="https://github.com/centrifuge/apps/assets/31280003/38bd5ae2-25c6-4fb5-bd24-decdab98aed5">
<img width="317" alt="Screenshot 2024-01-18 at 12 34 59" src="https://github.com/centrifuge/apps/assets/31280003/c4559f11-9539-483c-ab87-7042c0d3aec2">

**Calculations**
* Maximum charge: Show USDC amount of 1% of current NAV 
* Pending fees: catch from onchain data, if there are still pending fees.

**Comment by sophialittlejohn** [comment]
Merged into [feature branch](https://github.com/centrifuge/apps/pull/1917) instead of main because it will prevent break in production currently
