### ISSUE TITLE
Add metadata to transactions (onchain remarks)

### ISSUE THREAD

**Issue by annamehr** [centrifuge/apps#1867]
[Protocol specs](https://centrifuge.hackmd.io/FSjABNk2RSW3NNLq9vIINg)
[Product specs](https://centrifuge.hackmd.io/ap9a1JCYSUa7CyEOGAbdIg?both)

## User stories
* As a user (issuer) I want to add a comment to my borrow and repay transactions

## Requirements 
* Add text box to borrow and repay component
* Show notes next to transactions in the detailed view of the asset

In the future:
* Investor to add private notes to investment and redemption transactions
* The investor can see their private notes (something like Etherscan)
* Searching available for notes

**Comment by TimHoub** [comment]
Design to show message in table.
On hover we show a tooltip with the complete message.

https://www.figma.com/file/cn5CiQsuVDOmieszqcneX2/Pool-management?type=design&node-id=812%3A12129&mode=design&t=uAAQlnIzs0H0rtL2-1

**Comment by TimHoub** [comment]
On hold - Will be discussed during design meeting: 7 Feb.
