### ISSUE TITLE
Finance/repay component text box + show overdue asset warning

### ISSUE THREAD

**Issue by annamehr** [centrifuge/apps#1874]
User feedback: 
Below we only give the option to repay (correctly I assume, since it is overdue and thus we don't want to issuer to borrow more), but the way the header of the finance/borrow component is repaid without the input fields is very confusing and feels more like a bug... Instead of showing "To finance the asset, enter face value and settlement price of the transaction." We could perhaps show a warning a la "No borrowing possible because asset is overdue"

## Specs
* when repaying user still sees the finance asset intro text
* possible solution: remove the finance text input box
* show warning that asset is overdue

![Image](https://github.com/centrifuge/apps/assets/31280003/75242b7f-eae7-430b-8bd1-dc4bd1a1da48)

**Comment by TimHoub** [comment]
- Agreed - We can remove the 'finance asset' copy (not needed in this scenario.
- We have our way of messaging when something is important. The light blue box above the CTA. I would just reuse this pattern..

Do we need a design for this?
