### ISSUE TITLE
Pool detail page: Structure component

### ISSUE THREAD

**Issue by annamehr** [centrifuge/apps#1890]
[Figma Design](https://www.figma.com/file/ng7qdNcSCXSDA6ZUdWIs6u/Pool-Overview%2F-Pool-Detail?type=design&node-id=1070-4795&mode=design&t=l0lkbH5U3jqPOj5x-0)

## Prerequisite
[#1918](https://github.com/centrifuge/apps/issues/1918)

## Background
The structure component is part of the pool detail redesign and can already be implemented in the current page. 

## Requirements
* Pool type: can display open or closed (still has to be implemented in the create pool form [#1918](https://github.com/centrifuge/apps/issues/1918); part of this [governance proposal ](https://gov.centrifuge.io/t/introducing-pool-types-and-modifying-the-pop-and-protocol-fees-to-better-align/5666)
* Pool structure: hardcoded to `Revolving pool` with a tooltip: `Investment and redemption orders can come in at any time, and assets can be financed and repaid continuously.`
* Tranche structure:  “Unitranche” for 1 tranches pools, “n tranches” for >1 with a tooltip: `For each tranche, tokens are issued that investors receive, representing interests in the tranches of the pool.`
* First investment: Retrieved based on subquery data, we can get the list of `InvestorTransactions` and find the first `INVEST_EXECUTION`
* Available network: all places where tranches are deployed for LP (multiple networks can be displayed)
* Fees: to be implemented with fees work

![Image](https://github.com/centrifuge/apps/assets/31280003/263bc007-8aa7-4fc1-b75d-a0022acae0c2)

Parent ticket #1741

**Comment by hieronx** [comment]
`Pool type` here should be renamed to `Pool structure`

And a new property should be added:
- `Available networks`: comma separated list of networks that are available (LP networks + Centrifuge)

E.g. for Anemoy:
- Available networks: Ethereum, Celo, Centrifuge

**Comment by jpangelle** [comment]
Blocked until #1953 is merged in order to get the pool fees.

**Comment by jpangelle** [comment]
Will follow up with adding pool fees in a separate ticket.
