### ISSUE TITLE
Archived pools

### ISSUE THREAD

**Issue by annamehr** [centrifuge/apps#1896]
## Background
Pool Management requested the following change.

## Requirements
* Add an additional filter `Archived`
* Hide “Archived” pools by default

The following pools will be marked as archived
* Branch Series 3
* databased.finance 1
* Fortunafi 1
* Fortunafi 2
* 1754 Factory Bling
* Cauris 
* Consol Freight
* Flow Carbon
* Gig economy pool 
* Harbor trade 2
* Reif pool

**Comment by TimHoub** [comment]
What about adding a status to the filter selector?
- Open for investments
- Upcoming
- Maker pool (this one is a bit of weird one imo)
- Closed
- *Archived *

![Image](https://github.com/centrifuge/apps/assets/131260516/b4907af9-f3ef-4227-afd8-525c0c468f50)
