### ISSUE TITLE
LP investment: token dropdown 

### ISSUE THREAD

**Issue by annamehr** [centrifuge/apps#1901]
[Figma design](https://www.figma.com/file/egKzXqF777A35BZMzPcoYD/Portfolio?type=design&node-id=206%3A12743&mode=design&t=CczzSCOEYFTAqBUH-1)
[Flows](https://www.figma.com/file/KGXXH6yUPWRKusf87Uqqk7/User-flow-charts?type=design&node-id=274%3A569&mode=design&t=g9thcfZEmtg0JYix-1)

## Background 
Core feature of liquidity pools that a user can invest with multiple currencies. As a quick fix USDC was set as default. 

## Requirements
* Add currency selector on investment and redemption component to allow multiple currencies
* Always show the token that the user has the highest balance of

![Image](https://github.com/centrifuge/apps/assets/31280003/18f1ad01-7ab4-4886-a778-add6352a00a7)

**Comment by TimHoub** [comment]
As discussed let's go with our standard currency selector inputfield for this one. 

![Image](https://github.com/centrifuge/apps/assets/131260516/202ab4fd-8a3a-405b-b39e-5662a3cde5d9)
