### ISSUE TITLE
Limitations of Transfer Allowlist

### ISSUE THREAD

**Issue by annamehr** [centrifuge/apps#1904]
## Background
The main problem is that pallet-transfer-allowlist in our current setup does not allow to allow a single account to have permissions for all current and future currencies in one run. This gets problematic, as we are adding more foreign domains with currencies to the system in the future, and our pool admins are not protected to mistakenly send tokens there.

## Specs
- This includes a breaking change.
- `TransferAllowlist.addTransferAllowance(`) now takes a new currency as an input
- `All` or `Specific(USUAL_CURRENCY_ID)`
- All existing storage will be migrated to `Specific(ID)`
- The UI should now set a restriction on the AO WALLET of a pool as `TransferAllowlist.addTransferAllowance(All, Local(MULTI_SIG_OF_POOL))` this will
- block all transfers that are NOT going to the multisig of the pool
- Additional allowances, for off-ramping through asset-hub, swapping etc. should be set as `TransferAllowlist.addTransferAllowance(Specific, ..) `on the AO WALLET.
- Summarizing:
- `All` is a value that blocks all current and future currencies to be transferred to the wrong address
- `Specific` is a value that ONLY blocks the specific currency to be send somwhere else. All other will still go through.
- ----
- IMO the most secure setup for any wallet would be
- Set an `All` allowance to the wallet itself - this blocks all transfers besides transferring to the wallet address itself
- NOTE: In case of the AO WALLET the multsi-sig should also be a valid `All` receiver
- Set `Specific(ID) `for specific addresses to receive that currency

**Comment by mustermeiszer** [comment]
Close and already possible.
