### ISSUE TITLE
Settlement account display

### ISSUE THREAD

**Issue by annamehr** [centrifuge/apps#1911]
[Figma design](https://www.figma.com/file/cn5CiQsuVDOmieszqcneX2/Pool-management?type=design&node-id=814%3A12711&mode=design&t=uAAQlnIzs0H0rtL2-1)

## Requirements
* Summary component
    * Onchain reserve ; tooltip: `The onchain reserve represents the amount of available liquidity in the pool available for asset originations and redemptions.`
        * Onchain reserve is the pool reserve
    * Offchain cash; tooltip: `Offchain cash represents funds held in a traditional bank account or custody account.`
        * Offchain cash is the summary of all cash assets
    * Ongoing assets; tooltip: `Number of assets currently being financed in the pool and awaiting repayment.`
    * Total NAV; tooltip: `The total Net Asset Value (NAV) reflects the combined present value of assets, cash held in the onchain reserve of the pool, and cash in the bank account designated as offchain cash. `
* Remove maturity date from cash asset
* Add blue background for numbers
* Display three kinds of assets in the following priority 
     1. Onchain reserve (pinned at the top)
     2. Offchain cash assets (can be multiple, Asset valuation: cash)
     3. All other assets 
*** Highlight cash asset with a special cash account icon that is always displayed when an asset with cash valuation is created.** 

![Image](https://github.com/centrifuge/apps/assets/31280003/0c05ad1a-59cb-49aa-b4ad-a943a8688480)

**Comment by TimHoub** [comment]
![Image](https://github.com/centrifuge/apps/assets/131260516/6b2d5935-8c6e-4515-97c9-d27315f25d71)

**Comment by TimHoub** [comment]
https://www.figma.com/file/cn5CiQsuVDOmieszqcneX2/Pool-management?type=design&node-id=814%3A12711&mode=design&t=mBCBoZsJQy4uQMh0-1

**Comment by TimHoub** [comment]
Updated with icons and tooltip

![Image](https://github.com/centrifuge/apps/assets/131260516/63ad25f3-2df0-4730-abb9-adc2815c6e12)
