### ISSUE TITLE
Create pool: add pool type

### ISSUE THREAD

**Issue by annamehr** [centrifuge/apps#1918]
## Background

[This](https://gov.centrifuge.io/t/introducing-pool-types-and-modifying-the-pop-and-protocol-fees-to-better-align/5666) governance proposal suggested a new pool structure where it introduced open and closed pools.

## Requirements
* Add additional input field with a dropdown in the Details section 
* Name: `Pool type`, Options: `Open` and `closed`
* Tooltip: An open pool allows can have multiple unrelated token holders and can onboard third party investors. A closed pool has very limited distributions and is not available for investment on the app.

![Image](https://github.com/centrifuge/apps/assets/31280003/c3b77027-d147-4859-9ef3-6cd1aa9c8e8d)

**Comment by sophialittlejohn** [comment]
@annamehr it should be fixed now! Turns out the bug happened when we renamed `privateCredit` to `Private credit` and the same for public credit. So just a residual bug that had to be addressed :)
