### ISSUE TITLE
Follow up pool fees

### ISSUE THREAD

**Issue by annamehr** [centrifuge/apps#1928]
After testing the first implementation of the pool fees, here are the follow up todos that need to be fixed before it can be released with the runtime upgrade.

## Create pool form
- [ ] Period separation instead of comma for input field Fees in % of NAV
- [x] When entering a fee % or name all input fields should be on the same line. Currently name and wallet address jump up a few pixels
- [x] Only one fixed protocol fee either Private Credit or Public Securities fee depending on the chosen asset class
Closed(Private) Pools
- Private Credit & Securities fees 0.15%
- Public Securities & Equities fees 0.02%
Open Pools
- Private Credit & Securities fees 0.4%
- Public Securities & Equities fees 0.075%
- [ ] When adding a direct charge fee the % input field ` Fees in % of NAV` should be renamed  `Max fees in % of NAV`
![Image](https://github.com/centrifuge/apps/assets/31280003/5a47bfdd-3e8e-4b11-9b70-1e82a3815766)

## Fee tab
- [x] On the Fees tab, for Fixed % of NAV fees, we could calculate `Pending fees` based on `time since last epoch closed * % fee * current NAV`. Would need to add `~` before the denote it being approximate (as the NAV might not be exactly right)
- [x] `Charge` and `Apply changes` buttons should be in the same style as the holdings tab,
Icon for `Charge`:
Icon for `Apply changes`:
- [x] Only `pool admins` can view and click on `Apply changes` and be able to sign a txn, hide `apply changes `button for non-pool admins
- [x] Display `Charge` button for pool admins and receiving address and hide for all other addresses. Display `Update fee charge` CTA only for pool admin 
- [x] Use tertiary button - [new design ](https://www.figma.com/file/aGu64OaUlVsss2LXUq2FPk/Components?type=design&node-id=5609%3A858&mode=design&t=XpeadhV29uiQhIvH-1) 

![Image](https://github.com/centrifuge/apps/assets/31280003/2f1e20c0-93dc-4039-9d6d-744ee432aa59)

## Edit fee
- [x] When adding a new fee `Current percentage` should be renamed to `Max fees in % of NAV`
- [x] Period separation instead of comma for input field Fees in % of NAV
- [x] When entering a percentage the input field jumps up 

![Image](https://github.com/centrifuge/apps/assets/31280003/5a0c73dc-feec-450d-ad85-84dd2a800577)

## Charge fees
- [x] “Fee charges have been placed. Charging of fees will be finalized by the issuer of the pool when executing orders.” --> “Fee charges have been placed. Fees will be paid when orders are executed and sufficient liquidity is available.” 

- [x] Current flow: If you click `Charge` on a direct charge fee that already has some pending fees, then click `Update charge`, and then `Cancel`, the slideover closes.  
Flow update: If you click `Charge` on a direct charge fee that already has some pending fees, then click `Update charge`, and then `Cancel`, go back to the view you are at before clicking `Update charge`. 

![Image](https://github.com/centrifuge/apps/assets/31280003/06d28d5a-4cb2-4c1b-8df8-7153a41127ab)

**Comment by sophialittlejohn** [comment]
Going to tackle #1918 here since it affects the pool fees

**Comment by sophialittlejohn** [comment]
> Display Charge button for pool admins and receiving address and hide for all other addresses. Display Update fee charge CTA only for pool admin
Just want to make sure you're aware that only the receiving address has permissions to charge fees, I can still show the button to admins and receivers and disable the inputs and form submission for admins as it is now
