### ISSUE TITLE
Flow mapping asset detail page

### ISSUE THREAD

**Issue by annamehr** [centrifuge/apps#1932]
[Figma file](https://www.figma.com/file/KGXXH6yUPWRKusf87Uqqk7/Asset-page-flow-charts?type=design&node-id=0-1&mode=design&t=zTFuWdLhA9ZZJFtg-0)

- [ ] Asset write-off and maturity extension
- [ ]  Cash asset flows

## Asset creation + financing

![Image](https://github.com/centrifuge/apps/assets/31280003/2ffe25dd-6bb4-49ad-9e0f-cf247da3828f)
## Asset repayment

![Image](https://github.com/centrifuge/apps/assets/31280003/776932f8-cddd-4e5b-b263-77a14ea777b2)

## NAV Management flow 

![Image](https://github.com/centrifuge/apps/assets/31280003/56183fb2-b5e5-4cfd-b5de-1f1b4bc7cbc4)

**Comment by mustermeiszer** [comment]
Taken care of by new asset flow and remaining will be handled by liquidity tab redesign
