### ISSUE TITLE
Pool fees UI feedback

### ISSUE THREAD

**Issue by annamehr** [centrifuge/apps#1943]
[Figma design](https://www.figma.com/file/cn5CiQsuVDOmieszqcneX2/Pool-management?type=design&node-id=1043-24802&mode=design&t=AGkd1dcag8z0V6kr-0)

## Fee tab
- [x] Add option to copy receiving address in the fee tab
- [x] Display the address in full column width 
- [x] For direct charges change `0.500% of NAV` to `<0.500% of non-cash NAV`
- [x] Show `Total pending fees`(summary of all pending fees) in the summary banner. 
        Tooltip: `The total pending fees represent the sum of all added fees.`
- [x] Add extra column `Fee position` next to fee type with input `Top of waterfall `
- [x] Display `Action` column only for pool admins and charging address
- [x] Rename column header from `Percentage` --> `Percentage/Limit`
- [x] For Direct charges and their limit, show the current limit in absolut terms (“10,400 USDT”. You can get this value`maxPayable` from the chain side.

![Image](https://github.com/centrifuge/apps/assets/31280003/50c026fd-0658-4590-a9c1-c1cc399329de)

## Create pool section
- [x] Rename the fixed protocol fees to Protocol fee (Public Securities & Equities) or Protocol fee (Private Credit & Securities) 
- [x] Fee type header is dark grey while the rest is light grey -> adjust to light grey so it's aligned with the rest, and add tooltip to fee type: `The protocol fee is mandatory and will be charged every epoch automatically. The fee amount is dependent on the asset class.`
- [x] Add a new column `Fee position` to the table and a dropdown input when creating a fee with one preselected option `Top of waterfall` with a tooltip. This explains the behaviour of the fees, and also shows that we can support other “fee positions” in the future. Tooltip copy: `Fees are settled using available liquidity before investments or redemptions, prioritizing and paying the highest fees first.`
- [x] Copy change: Fee type `Fixed` -> `Fixed %`
- [x] When selecting Fee type `Direct charge`, the column fee percentage column changes to `Max fees in % of NAV`, when selecting fee type `Fixed %` -> Fees in % of NAV
- [x] Fee percentage field it should be possible to enter values from 0.0001%; limit should be 0.0001 to 10% 

![Image](https://github.com/centrifuge/apps/assets/31280003/79f7317a-7a35-42d7-aaa8-1895625eff76)

## Edit fee slide over
* Align wording for direct charge `Max fees in % of NAV` and remove `Limit (% of NAV)`

**Comment by hieronx** [comment]
- [ ] If you select the `Fixed` fee type on the pool creation page, `Max fees in % of NAV` should change to `Fee in % of NAV`
