### ISSUE TITLE
Pool detail page: Issuer details

### ISSUE THREAD

**Issue by annamehr** [centrifuge/apps#1965]
* Use current issuer section and import into the new pool detail page

![Image](https://github.com/centrifuge/apps/assets/31280003/bc185f88-f7d0-4e78-bca7-886c5d591194)
![Image](https://github.com/centrifuge/apps/assets/31280003/bac37ff9-e24b-488c-b64d-a3b71caead6f)

Parent #1741

**Comment by jpangelle** [comment]
Blocked until #1953 is merged
