### ISSUE TITLE
Pool detail page: Asset maturity chart (Pod indexer)

### ISSUE THREAD

**Issue by annamehr** [centrifuge/apps#1972]
[Figma design
](https://www.figma.com/file/ng7qdNcSCXSDA6ZUdWIs6u/Pool-Overview%2F-Pool-Detail?type=design&node-id=1070-4795&mode=design&t=v5WlcpbCsqnsVOjU-0) [Current PR](https://github.com/centrifuge/apps/pull/1959)
## Requirements
* Custom charts for pools with the asset class US treasuries (Anemoy)
* Use term as the main datapoint in the pie chart

![Image](https://github.com/centrifuge/apps/assets/31280003/7e692b46-230b-4506-ac77-3f981f47443a)

## Design
![Image](https://github.com/centrifuge/apps/assets/31280003/9514d906-aedd-4ed8-a90b-98bfb242ba0a)

Parent ticket #1741

**Comment by jpangelle** [comment]
Blocked until POD indexer work is done

**Comment by jpangelle** [comment]
No longer blocked :)
