### ISSUE TITLE
Follow up pool detail page

### ISSUE THREAD

**Issue by annamehr** [centrifuge/apps#1984]
## Structure component

* Remove `Written off assets` for Anemoy
* Only display `Overdue assets` when there are more than 0 overdue assets. 
* Add tooltip to `Open`:  `An open pool that allows for a broader distribution to third-party investors as well as DeFi protocols. These pools have multiple unrelated token holders and can onboard third party investors.`
* Available network -> Available networks

**Comment by jpangelle** [comment]
Done 💯
