### ISSUE TITLE
CFG transfer warning

### ISSUE THREAD

**Issue by annamehr** [centrifuge/apps#1991]
## Background 
After the recent renaming from wCFG to CFG, a lot of user send native CFG to an wCFG address and lost their funds. The idea is to show the user additional warning/notification so they won't loose their funds.

## Requirements
* Currently the app displays the CFG wallet balance without deducting the CFGs locked in vesting. Only displays available amount that are transferable. 
*  If the user enters a 0x address on the centrifuge network, display the text with a warning/error-style colour between wallet balance and send button. 
`Only use this page to transfer native CFG to Centrifuge. Transfers to addresses on other networks or on exchanges could result in loss of funds. If you want to bridge native CFG to Ethereum, go to bridge.centrifuge.io.`

## Design
![Image](https://github.com/centrifuge/apps/assets/31280003/259a24ab-c4cb-43a5-8284-5b8e4a9312ba)

**Comment by TimHoub** [comment]
If the user enters a 0x address on the centrifuge network, display the text with a warning/error-style colour between wallet balance and send button.

-Please only use this page to transfer native CFG to Centrifuge Chain. Transfers to addresses on other networks or on exchanges could result in loss of funds. If you want to bridge native CFG to Ethereum, go to bridge.centrifuge.io.
