### ISSUE TITLE
Pool fees v2

### ISSUE THREAD

**Issue by annamehr** [centrifuge/apps#1993]
[Figma design](https://www.figma.com/file/cn5CiQsuVDOmieszqcneX2/Pool-management?type=design&node-id=1043-24802&mode=design&t=BJOK3rZomiXZliSq-0)

## Background 
This ticket will display fees in the cashflow chart on the pool detail page.

### Pool detail page
- [x] Add fees cashflow chart - [Figma design](https://www.figma.com/file/ng7qdNcSCXSDA6ZUdWIs6u/Pool-Overview%2F-Pool-Detail?type=design&node-id=1070-4795&mode=design&t=eXKPLrvIDNdbZNQF-0)

![Image](https://github.com/centrifuge/apps/assets/31280003/e1b510b8-cbcc-4ccc-a8e4-6b6c8711eaae)

**Comment by TimHoub** [comment]
Added dropdown for 'Fee type''

![Image](https://github.com/centrifuge/apps/assets/131260516/7ff9f958-f3e4-498d-a332-e8e6c67754f1)

**Comment by TimHoub** [comment]
+ link to figma
https://www.figma.com/file/cn5CiQsuVDOmieszqcneX2/Pool-management?type=design&node-id=1759%3A12948&mode=design&t=mWcuinKfi44M3zvv-1
