### ISSUE TITLE
Applied design for Charts (Pool overview) (private credit pools)

### ISSUE THREAD

**Issue by annamehr** [centrifuge/apps#2013]
Deadline: 3 April 24 

[Specs](https://centrifuge.hackmd.io/o9AMVcr-QvCRUh9QNzZWTQ?both#New-Silver)

## Order
* Current value chart + Key Metrics (customizable)
* Pool Tokens
* Customizable Portfolio charts section
* Cashflow Chart
* Risk Mitigation + Covenants
* Analysis
* Issuer Description + Pool Key Details
* Transaction History

## Customizable charts
* Total loan portfolio 
    * Total loan volume = $49,943,904
    * Volume of loans outstanding = $19,800,890
![](https://storage.googleapis.com/centrifuge-hackmd/upload_3f12ab9386d5a0e79668694c82cebaf2.png)
* Loan balance and accrued fees for Centrifuge
![](https://storage.googleapis.com/centrifuge-hackmd/upload_14fa448bf87e97eb0cf5fe95ec4889c0.png)
* Historical loan originations
![](https://storage.googleapis.com/centrifuge-hackmd/upload_d453585ab85056dc8a8e37d73b5a3686.png)

* Average FICO score = 708 (weighted by outstanding debt)
![](https://storage.googleapis.com/centrifuge-hackmd/upload_a667049d479959a93e71bc80426f19b6.png)

![](https://storage.googleapis.com/centrifuge-hackmd/upload_ebac1475f170f1a55f4351a2e91b3236.png)

* Geography: Map of U.S. and then you hover over the different states to see the loan volume for each state or bar chart with states on the x-axis and volume on y-axis 

![](https://storage.googleapis.com/centrifuge-hackmd/upload_d8527d48f26dfdb1ed690be9e9fdcba8.png)

**Comment by TimHoub** [comment]
Colour/ data/ Filter
