### ISSUE TITLE
Onchain account (externally and internally priced assets)

### ISSUE THREAD

**Issue by annamehr** [centrifuge/apps#2014]
It's the same page but depending on the valuation type the the types may differ. For internally priced assets the types are (`Financed`, `Repaid`, `Cash transfer`), for externally priced it's mostly `Cash transfer`. 

### Onchain account assets financed 
![Image](https://github.com/centrifuge/apps/assets/31280003/2409d9b0-b8d1-44ef-be56-56e30a1ba686)

### Transaction history
   * Type (`Financed`, `Repaid`, `Cash transfer`)
   * Transaction date with option to sort from low to high (when you hover of the transaction date, the exact time will be displayed) 
   * Asset: Shows the direction of the fund movement from onchain account to settlement account (onchain account > settlement account and vice versa)
   * Amount
   * View transaction 
   * Download button

**Comment by TimHoub** [comment]
Designs can be found here:

Only open issues: 
1. Cash asset -> view transaction (is this also onchain?)
2. Display settlement account transactions (could you elaborate a bit wath this means, goal of this feature is?) @annamehr 


https://www.figma.com/file/cn5CiQsuVDOmieszqcneX2/Pool-management?type=design&node-id=814%3A12711&mode=design&t=mnter75l6OybXFpK-1

**Comment by TimHoub** [comment]
Latest design can be found here.
https://www.figma.com/design/cn5CiQsuVDOmieszqcneX2/Pool-management?node-id=2551%3A14872&t=mw0ovAW9sSOzue00-1
