### ISSUE TITLE
Fix grid on Asset, liquidity and Reporting tabs

### ISSUE THREAD

**Issue by TimHoub** [centrifuge/apps#2017]

**Comment by TimHoub** [comment]
The grid is not perfect yet on the Asset,Liquidity and Reporting tabs. Would love to have this consistent across the app.

![Image](https://github.com/centrifuge/apps/assets/131260516/7b441c02-8404-4f8f-8396-8f64d0394867)

**Comment by kattylucy** [comment]
Do you know what he meant with "is not perfect"? What adjustment should be done? 

@sophialittlejohn

**Comment by sophialittlejohn** [comment]
@kattylucy not sure anymore to be honest. Closing the ticket for now until further specs can be provided
