### ISSUE TITLE
Website redesign (Marketing)

### ISSUE THREAD

**Issue by annamehr** [centrifuge/apps#2024]
- Home (redesigned)
- Products (new)
- Investors (new)
- Centrifuge Prime (current)
- Asset Managers (current)
- Partners (new)
- Resources (new)
- News (external link)
- Blog (external link)
- Social (new)
- About (new)
- Contributors (redesigned)
- Governance (external link)
- Documentation (external link)

**Comment by sophialittlejohn** [comment]
Close, will create a new ticket when marketing is ready
