### ISSUE TITLE
Pool fees v2 design tasks

### ISSUE THREAD

**Issue by annamehr** [centrifuge/apps#2039]
- [ ] Display absolute amounts of `max fees in % of NAV ` next to percentages e.g. 5400 USDC  - [Figma comment](https://www.figma.com/file/cn5CiQsuVDOmieszqcneX2?node-id=1144:32318&mode=design#743312642) You already designed something similar for charging 
![Image](https://github.com/centrifuge/apps/assets/31280003/18c2f9c7-7b67-4b4a-bc7c-98334df715fa)

![Image](https://github.com/centrifuge/apps/assets/31280003/49153a7d-039f-45c4-b007-658a73e5a364)

- [ ] Add "Total charged" , `Total charged protocol fee` ,`Total charged management fee`, `Total charged service fee` - [Figma comment](https://www.figma.com/file/cn5CiQsuVDOmieszqcneX2?node-id=1043:24802&mode=design#743297968)

**Comment by TimHoub** [comment]
https://www.figma.com/file/cn5CiQsuVDOmieszqcneX2/Pool-management?type=design&node-id=1759%3A12388&mode=design&t=DWaZixxGM5kXxVdL-1
