### ISSUE TITLE
Pool fees v3

### ISSUE THREAD

**Issue by annamehr** [centrifuge/apps#2040]
[Figma design](https://www.figma.com/design/ng7qdNcSCXSDA6ZUdWIs6u/Pool-Overview%2F-Pool-Detail?version-id=5828566989&node-id=1834-33587&t=1K1e1rQd7PeVq50P-0)

### Summary bar 
- [x] Add to the summary section `Total paid fees` 
- [x] Tooltip: `Total paid fees`: `"The total paid fees represent the sum of all paid fees since the inception of the fee system."`

### Link to fee transaction report 
- [x]  New component that leads the user to the fee transaction report of the pool (Anemoy fee tx report: https://app-ff-production.k-f.dev/pools/4139607887/reporting/fee-tx)

![Image](https://github.com/centrifuge/apps/assets/31280003/083b5cec-e963-408e-94e7-9e1565d2ec3f)

### Fee categories
- [x] Add additional column `Category`
- [x]  Categories: Trading, Fund admin, Custodian, Investor onboarding, Auditor, Protocol 

### Edit fee component 
- [x] When adding new fees add additional dropdown for the categories (Protocol, Management Fee, Trading, Fund administration, Custody, Auditing & Accounting) 

## Create pool form requirements
- [x]  Add additional dropdown for the categories (Trading, Fund admin, Custodian, Investor onboarding, Auditor, Protocol)

## Flow

![Image](https://github.com/centrifuge/apps/assets/31280003/8319a19c-0301-4a89-8bdb-d42592017aba)

**Comment by 0x4Graham** [comment]
Looks good to me
