### ISSUE TITLE
NAV Managament: Slide over

### ISSUE THREAD

**Issue by annamehr** [centrifuge/apps#2045]
[Figma Design](https://www.figma.com/file/cn5CiQsuVDOmieszqcneX2/Pool-management?type=design&node-id=1759-11555&mode=design&t=eUamB8sTTIeYoV3q-0)

## Background
Only for t-bills pool. The slide over will be used to confirm the new NAV and execute orders if there are open orders for investments and redemptions

## Flow
* After editing the prices and clicking done, the slide over will open as a summary of the changes
* User can review the changes, clicks update NAV, signs transaction
* After successful update, NAV over view will adapt and displays the previous pending NAV as current NAV. 

## Specs
* Same overview that is displayed on the main page
* Token price update
* Display text when there are open orders for investments and redemptions.
`There are open investment or redemption orders, updating the NAV will trigger the execution of orders.`
* Hide fully repaid assets

### Data source
* New token price = (updated NAV / token supply [which is fixed from chain])

Note: this only works for 1 tranche pools. If there are multiple tranches, the new prices should not be shown.

## State without open orders for investments and redemptions
![Image](https://github.com/centrifuge/apps/assets/31280003/f1bb22d2-7e56-4bc6-b53c-76c6282e3f31)

## State with open orders for investments and redemptions
![Image](https://github.com/centrifuge/apps/assets/31280003/8aa3ec7c-34eb-490f-b11d-ee5182c15cb4)

Parent ticket #1868

**Comment by hieronx** [comment]
Include collecting orders on epoch close, similar to the Liquidity Epoch section (move collecting to closeEpoch/executeEpoch in cent.js)

added to https://github.com/centrifuge/apps/issues/2212

**Comment by 0x4Graham** [comment]
@onnovisser 

Can we add the name of the fund to the top? 

Maybe it's just a demo env issue, but it's hard to know what is the actual fund where you would update the NAV. 



![Image](https://github.com/user-attachments/assets/dbf3eb0e-372f-4ec0-bdf6-6625b64b0445)

**Comment by 0x4Graham** [comment]
This now working as expected 👍
