### ISSUE TITLE
Multichain integrations on pool detail page

### ISSUE THREAD

**Issue by annamehr** [centrifuge/apps#2103]
## Userstory
- As a user I want to see from which chain I can invest into the pool.

## Requirements
- We want to highlight the capabilities of Liquidity pools and that investors can invest from multiple chain. 
- Link these to the Etherscan pages so the contracts are easily discoverable for investors.
-  Logos are clickable and take user to the explorer. When there is a multi tranche pool, the tooltip should show explorer links for Junior and senior tranche.

## Design
- Logo's: 16px height

![Image](https://github.com/centrifuge/apps/assets/31280003/ea45d992-0a84-43b7-b839-35dd735b4225)

**Comment by TimHoub** [comment]
Final design:
Logo's: 16px height
Logo's are clickable and take you to the explorer. When there is a multitranche pool, the tooltip should show explorer links for Junior and senior tranche. 

![Image](https://github.com/centrifuge/apps/assets/131260516/51dd7b65-fa89-43cc-9d96-d200a3766c65)
