### ISSUE TITLE
Onramping funds for issuers

### ISSUE THREAD

**Issue by annamehr** [centrifuge/apps#2126]
[Specs](https://centrifuge.hackmd.io/1ktW6UzaSd6bQOwb2kZXaQ?both)
* Separate from redemptions
* Display redemptions and show where funds are available and where funds need to be added
* Swaps 
* Enter amount for each chain that can be repaid
* Display outstanding amount
* Display amounts that are available on the trusted addresses
* Link to external explorer (Axelar scan) for the repayment transactions
* Add instructions how issuers can move funds from trusted address to AO wallet

**Comment by mustermeiszer** [comment]
Closing: will create a new ticket for this one.
