### ISSUE TITLE
Pool performance chart: Y-axis not displayed correctly

### ISSUE THREAD

**Issue by annamehr** [centrifuge/apps#2133]
- [ ] Can you change the first day of the chart when first investment came in (13 May) instead of 3 April?
- [ ] Display full numbers 

![Image](https://github.com/centrifuge/apps/assets/31280003/2d5d4d4d-c8bc-4365-a6f7-25c1a7d8ce1e)

**Comment by hieronx** [comment]
Fixed in https://github.com/centrifuge/apps/pull/2235
