### ISSUE TITLE
Reporting: Balance sheet + cashflow sheet

### ISSUE THREAD

**Issue by annamehr** [centrifuge/apps#2146]
## Background
This ticket is the first part of the financial reporting feature for the individual pools that was discussed during the offsite.
This aim of this ticket is to build three reports for the reporting tab.

- [x] Balance sheet
- [ ] Cash flow statement
- [ ] Asset stats per day 

## Balance sheet
It provides a snapshot of a company's finances (what it owns and owes) as of the date of publication. The balance sheet adheres to an equation that equates assets with the sum of liabilities and shareholder equity.

### Data
[Spreadsheet with all required data points
](https://docs.google.com/spreadsheets/d/1jJvdrvM1B65YOo_72plBsfsA5bj1xdKwdo_62hz2c2k/edit#gid=896918484)
![Image](https://github.com/centrifuge/apps/assets/31280003/70709f53-1e99-4015-861f-70e8e5b193e9)

### Time filters
* Display on the left the oldest data and on the right the most recent data
* Time filters:  Specific day (day selector), Daily - (display last 30 days), Monthly - last 12 months, Quarterly - last 4 quarters, Yearly - last available years

## Cash flow statement
A cash flow statement is a financial statement that provides aggregate data regarding all cash inflows that a company receives from its ongoing operations and external investment sources. It also includes all cash outflows that pay for business activities and investments during a given period.

### Data

[Spreadsheet with all required data points
](https://docs.google.com/spreadsheets/d/1jJvdrvM1B65YOo_72plBsfsA5bj1xdKwdo_62hz2c2k/edit#gid=1081509942)

![Image](https://github.com/centrifuge/apps/assets/31280003/8b394715-4ca1-439f-8fd6-f8aadd78d946)

```
+ Sales / Repayments
- Purchases / Borrowing
+ Coupon / interest payments
= Gross cash flow 
- Fees / costs
= Net cash flow 
+ Investments
- Redemptions
= Total cash flow
```

### Time filters
* Display on the left the oldest data and on the right the most recent data
* Time filters:  Specific day (day selector), Daily - (display last 30 days), Monthly - last 12 months, Quarterly - last 4 quarters, Yearly - last available years

**Comment by hieronx** [comment]
A few small details I would propose to change

### Balance sheet
- Rename `Settlement account(s)` to `Offchain cash`, to match the naming on the assets page
- Remove bank account(s) row
- If there is only 1 tranche, don't include the name (now for Anemoy it is `1 token supply`, should just be `Token supply`

### Cash flow statement
- Naming here should match the naming on the asset detail page, that depends on the pool asset class. So Sales/Purchases for public credit, Financing (not Borrowings)/Repayments for private credit.
- `Coupon / interest payments` => `Interest payments`
- `Fees / costs` => `Fees`
