### ISSUE TITLE
Tinlake displaying counter-intuitive address information

### ISSUE THREAD

**Issue by r0qs** [centrifuge/apps#216]
Hi,

I believe that this may be an issue with the `tinlake-ui`.

To claim CFG you need to link a centrifuge account to your ethereum account. And as far as I know, you can create a centrifuge account in the portal or importing it using the parity signer. Then you can import your account to the polkadot extension when interacting with tinlake.

As the extension can import accounts, I decided to import a polkadot account using the extension option `attach ledger account` instead of a centrifuge account (I know that centrifuge does not support ledger yet).

Tinlake displayed the account as a valid account to claim the funds, but the address displayed in tinlake was not the same in the extension. And as you can see here: https://github.com/polkadot-js/extension/issues/714, the option to `display address format` and select `centrifuge chain` will not work in this case.

I thought this was a problem with the extension that allowed me to use a wrong address, but actually, as pointed out by @jacogr here: https://github.com/polkadot-js/extension/issues/714#issuecomment-833504817 tinlake should not show the imported account if it points to a different chain. This can lead to users sending funds to wrong accounts.

**Comment by jacogr** [comment]
This is not tinlake ui, this is the polkadot-js repo. :)

**Comment by r0qs** [comment]
Oh, I thought that the problem was with the ui: https://github.com/centrifuge/apps/tree/main/tinlake-ui. Sorry.

**Comment by jacogr** [comment]
Sadly don’t even know about tinlake. Happy to fix issues as reported in this repo for this code base, but cannot control what other do with the code - and cannot debug forks.

**Comment by r0qs** [comment]
Ah, I didn't know that they have a polkadot-js fork. Sorry for the misunderstanding and thanks a lot for the directions :-)

**Comment by denniswell** [comment]
@r0qs Did you try to change the address format in the extension settings as described in the tooltip? Then it should be displayed correctly. Closing it here, if the problem persists, please contact support@centrifuge.io
