### ISSUE TITLE
Fees tab/pool detail page: Historic charged fee chart

### ISSUE THREAD

**Issue by annamehr** [centrifuge/apps#2184]
* This chart should display the pending fees g. Ideally it would display the fee groups or the individual fees. 
 *  x-axis: fee amounts 
 * y-axis: dates
 * Filter: by group and time period (30 days, 90 days, YTD)

![Image](https://github.com/centrifuge/apps/assets/31280003/a6f4c628-a164-4930-820d-7ca56afc5830)

**Comment by sonam-jo** [comment]
Low prio
