### ISSUE TITLE
Bug: Issuer details shown twice 

### ISSUE THREAD

**Issue by annamehr** [centrifuge/apps#2219]
## Bug report
- On the pool detail page, the issuer information section is shown twice.

## Fix
- Remove issuer details from the structure section 

## How to reproduce
- Go to https://app.centrifuge.io/pools/4139607887 

<img width="1455" alt="Screenshot 2024-06-18 at 12 58 32" src="https://github.com/centrifuge/apps/assets/31280003/a585104e-2c3f-496e-ac86-beb2c2f66811">

**Comment by onnovisser** [comment]
@annamehr what about for tinlake or pools that have no pool analysis?
