### ISSUE TITLE
Add cashflow section to asset detail page

### ISSUE THREAD

**Issue by hieronx** [centrifuge/apps#2225]
Design: https://www.figma.com/design/cn5CiQsuVDOmieszqcneX2/Pool-management?node-id=2408-14869&t=5FOUxemgdNB7UiqR-4

<img width="976" alt="Screenshot 2024-06-19 at 09 38 05" src="https://github.com/centrifuge/apps/assets/1748621/ccae9581-a3ea-408b-8431-6bb86607203e">

**Comment by mustermeiszer** [comment]
Should be closed: Actual one is https://github.com/centrifuge/apps/issues/2241
