### ISSUE TITLE
Add asset P&L to Key metrics

### ISSUE THREAD

**Issue by hieronx** [centrifuge/apps#2253]
For assets with `valuation method == oracle`, add Realized P&L and Unrealized P&L to the Key metrics card, above the YTM properties.

Realized P&L: `Asset.sumRealizedProfitFifo` from the subquery
Unrealized P&L: `Asset.unrealizedProfitAtMarketPrice` from the subquery

**Comment by abhiraj-mengade** [comment]
I would like to work on this. @hieronx

**Comment by 0x4Graham** [comment]
Is there a fund I can test this with @kattylucy @hieronx ? I can't seem to find one

**Comment by 0x4Graham** [comment]
Not working for me @kattylucy. 

There seems to be an issue with calculating the Unrealized P&L



![Image](https://github.com/user-attachments/assets/bd94ad96-5f86-45df-b660-6d2f7a184dd5)



https://app-ff-production.k-f.dev/#/pools/4139607887/assets/8

**Comment by kattylucy** [comment]
Good catch! Thankss @0x4Graham

**Comment by 0x4Graham** [comment]
Fixed! Nice work @kattylucy
