### ISSUE TITLE
Asset list report update

### ISSUE THREAD

**Issue by hieronx** [centrifuge/apps#2273]
### Data source
- [x] Move to using the subquery as source of truth, using `AssetSnapshot`s rather than the onchain data
- [x] Add a date picker at the top for the snapshots
- [x] Exclude cash assets

### Columns (public credit pools)
- Name (`asset.name`)
- Market value (`presentValue`)
- Face value (`notional * outstandingQuantity`)
- Quantity (`outstandingQuantity`)
- Market price (`currentPrice`)
- Maturity date (`actualMaturityDate`)
- Unrealized profit (`unrealizedProfitAtMarketPrice`)
- Realized profit (`sumRealizedProfitFifo`)

### Columns (private credit pools)
- Name (`asset.name`)
- Value (`presentValue`)
- Principal outstanding (`outstandingPrincipal`)
- Interest outstanding (`outstandingInterest`)
- Principal repaid (`totalRepaidPrincipal`)
- Interest repaid (`totalRepaidInterest`)
- Additional repaid (`totalRepaidUnscheduled`)
- Origination date (`actualOriginationDate`)
- Maturity date (`actualMaturityDate`)
- Valuation method (`asset.valuationMethod`)
- Advance rate (`asset.advanceRate`)
- Collateral value (`asset.collateralValue`)
- Probability of default (PD) (`asset.probabilityOfDefault`)
- Loss given default (LGD) (`asset.lossGivenDefault`)
- Discount rate (`asset.discountRate`)

**Comment by kattylucy** [comment]
Is the pool credit type always required? I see some pools (on demo) with neither public or private. If this case is possible in some instances, which one should be default? @hieronx

**Comment by hieronx** [comment]
@kattylucy that seems to be an issue with demo pools then, it should always be set to either public or private credit. But if it is not set, I would default to private credit.

**Comment by kattylucy** [comment]
Great. Another question, should we also add a group by field to display a default amount of assets based on this field?

![Image](https://github.com/user-attachments/assets/c5ca8a21-8263-462d-bf0d-74a8ab0f6a7d)

@hieronx

**Comment by hieronx** [comment]
I'm not sure I follow. What would the options in the Group by dropdown be for the asset list report?
