### ISSUE TITLE
Remove "Get Started" from Pools page

### ISSUE THREAD

**Issue by sonam-jo** [centrifuge/apps#2291]
Remove the box with text and get started CTA from the Pools page

![Image](https://github.com/user-attachments/assets/ec84c1b7-cad7-47f9-bd3d-afb2ea112188)

**Comment by 0x4Graham** [comment]
@kattylucy Can we just remove the box and keep the other box the same size please?

**Comment by kattylucy** [comment]
so to keep the <total value locked> box half width of the screen? @0x4Graham

**Comment by 0x4Graham** [comment]
Yes please

**Comment by 0x4Graham** [comment]
Some more context, we will use that other space to provide updates in the future

**Comment by 0x4Graham** [comment]
The sizing looks a bit weird and smaller. 

Prod: 



![Image](https://github.com/user-attachments/assets/fcedb3de-fed0-4b63-ae12-62a3cf3d5d3c)

Pre Pod



![Image](https://github.com/user-attachments/assets/6a3beb7c-1c11-405a-92f0-3226f23993b1)

My preference is the sizing from Prod
