### ISSUE TITLE
Pool Overview: Performance Graph Buggy and doesn't have a set pattern

### ISSUE THREAD

**Issue by 0x4Graham** [centrifuge/apps#2310]
The pool performance chart has some weird behaviors when using. 

1. The x axis is not updating when selecting the date slider. In the following screenshot, it looks like the NAV for the 30 days starts at 0 and then increases 

![Image](https://github.com/user-attachments/assets/bd754c5d-98b7-48aa-bdef-fbd209d18d8c)

2. Months are skipped in some cases when playing around with the graphs/dates. 

![Image](https://github.com/user-attachments/assets/5892fb48-103b-4db4-992a-5d6f0780fc64)

Solution:  Can we bring some behaviour consistency into the charts on the pool performance chart.  

3. The NAV on chart is different to the NAV on the top and the blue box

![Image](https://github.com/user-attachments/assets/3b68dc39-dbcc-4afa-8cbb-1ff5c7328ba3)

**Comment by kattylucy** [comment]
Here are the updates for this ticket when QAing 

Utilize on chain data for token price & nav
Keep only months on graph regarding data length to maintain consistency
Show only one month per internal, do not repeat month or skip months
