### ISSUE TITLE
Include option to download NAV & Token Price csv in Pool Performance Chart

### ISSUE THREAD

**Issue by 0x4Graham** [centrifuge/apps#2311]
Add a download button for NAV and token price in the chart

The download would be a single report with the 
Daily Token price & NAV. Timeframe would be the selected range on the chart

**Comment by kattylucy** [comment]
Do we want this to be similar to the graph/download on liquidity? - @0x4Graham 



![Image](https://github.com/user-attachments/assets/395f4255-b9d9-427a-bc5a-0b75fc24e5c0)

**Comment by 0x4Graham** [comment]
> Do we want this to be similar to the graph/download on liquidity? - @0x4Graham
> 
> ![Image](https://private-user-images.githubusercontent.com/51223655/355494700-395f4255-b9d9-427a-bc5a-0b75fc24e5c0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI5NTY2MjgsIm5iZiI6MTcyMjk1NjMyOCwicGF0aCI6Ii81MTIyMzY1NS8zNTU0OTQ3MDAtMzk1ZjQyNTUtYjlkOS00MjdhLWJjNWEtMGI3NWZjMjRlNWMwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA2VDE0NTg0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJhODE1MzZiODJjZmQ5YzhkMjU5MDE2MzJjYzY0OTc1NzQ2ZTQxMjU1ZDBiNTdiMzRhODliMTZkY2U2OWFmODQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.djuxt2I-9m4GfEs6Lb8xpusqHTX1ZseIPxAa49lfRoU)

Yes please.

Sorry that the ticket wasn't clear!

**Comment by kattylucy** [comment]
Can we confirm this is what we want? @0x4Graham 



![Image](https://github.com/user-attachments/assets/256999ed-5828-47b3-b2c4-05ea1868f542)



![Image](https://github.com/user-attachments/assets/4e945c9c-b954-4144-9ac8-eaf98e3bf49c)

**Comment by 0x4Graham** [comment]
@sonam-jo Can you confirm the above is what is expected please? The download works, just want to make sure the report is good

**Comment by sonam-jo** [comment]
Yes the downloaded data looks good. Let's only do it for the NAV performance chart on the Overview page. We need to rethink the data and charts on the Liquidity page.
