### ISSUE TITLE
Sync Token & NAV Prices: Pool Performance

### ISSUE THREAD

**Issue by 0x4Graham** [centrifuge/apps#2312]
There is a discrepancy in the displayed data for the NAV and token price. The values shown in red are sourced from the subquery, which lags. The green values come directly from the chain and are more accurate. To ensure the most accurate and up-to-date information is displayed, we should use the chain data for the fixed token price and the latest NAV.

![Image](https://github.com/user-attachments/assets/fa62cdde-a498-4739-9140-5dc775c8acef)

Solution: 

- Use the on-chain number for the fixed token price.

- For the latest item in the graph, utilize the most up-to-date chain number for Token Price & NAC

**Comment by kattylucy** [comment]
I realize the currency is also different. do we want to update those?

in the graph is USD and on the button USDC. 

@0x4Graham @sonam-jo

**Comment by 0x4Graham** [comment]
Yes, they should both be USD
