### ISSUE TITLE
Add chain explorer link for Transaction Submission/Pending box

### ISSUE THREAD

**Issue by 0x4Graham** [centrifuge/apps#2318]
![Image](https://github.com/user-attachments/assets/1afc892d-b814-47a9-adc6-87b0a56b87cc)

We need to add a link to the relevant blockchain explorer to view the transaction status within the explorer

**Comment by kattylucy** [comment]
Hey @0x4Graham - I sync with @sophialittlejohn regarding this ticket. It seems the link is currently working on production. Is your idea to make ti work for demo and dev environments as well?

I don't have plenty of context but it doesn't seem to be something really useful. As per my conversation with Sophia.

```
dev and demo chains don’t have subscan links because they’re are ephemeral. Which also means that they don’t have long lasting data. You will only ever see data going forward from the moment you open the link, if you close it you loose all the data and recent events

By the time you click the link the data you will be looking for won’t be there, you would have had to open the link before submitting the tx
```

Can we please clarify what is the goal of the ticket here? Thank you!

**Comment by 0x4Graham** [comment]
Hey! 

This came up in a conversation with Jay.. If this is the case, that the dev & demo links don't have long lasting data then I won't worry about having this



Will close, and thanks for the feedback!
