### ISSUE TITLE
New asset mint: Dates end up with T+1 day entered

### ISSUE THREAD

**Issue by 0x4Graham** [centrifuge/apps#2325]
minted a new asset and the settlement date and the maturity date seem to be T-1 the date I entered

![image](https://github.com/user-attachments/assets/df7ee197-4303-4e3a-8f3b-ad7a10842cdc)

**Comment by kattylucy** [comment]
Do you mind telling me which pool is this? @0x4Graham

**Comment by kattylucy** [comment]
@0x4Graham In the screenshot, can you help me to figure out which one is settlement date?

**Comment by kattylucy** [comment]
I figured! - Thank you!, should be ready for review @0x4Graham

**Comment by 0x4Graham** [comment]
Works for me
