### ISSUE TITLE
Assets list overflow in New Silver 2

### ISSUE THREAD

**Issue by sophialittlejohn** [centrifuge/apps#2326]
The legacy pool New Silver 2 has ~450 assets that are now breaking the UI from loading. To fix this we should paginate the [assets list](https://app.centrifuge.io/pools/0x53b2d22d07E069a3b132BfeaaD275b10273d381E/assets)

Overview tab also won't load: `Error: Issue fetching loans for Tinlake pool 0x53b2d22d07E069a3b132BfeaaD275b10273d381E. Errors: [object Object]`

**Comment by 0x4Graham** [comment]
Works great!
