### ISSUE TITLE
Remove maturity option from cash accounts

### ISSUE THREAD

**Issue by hieronx** [centrifuge/apps#2332]
When selecting the `Cash` asset type on the `Create asset` page, the maturity date should be fixed to `Open-end` and not be shown as an input.

**Comment by kattylucy** [comment]
Does this means we want to disabled the two other options? 

![Image](https://github.com/user-attachments/assets/86656b72-541c-4c47-81aa-760d5ad52b2e)

**Comment by hieronx** [comment]
@kattylucy we should just remove the `Pricing` section including the maturity dropdown entirely.

**Comment by 0x4Graham** [comment]
@kattylucy on the initial request works as expected,

Based on @hieronx comment, it seems that the pricing section still displaying when cash asset selected: 



![Image](https://github.com/user-attachments/assets/39548937-2e98-4624-a756-790e65e33682)

**Comment by kattylucy** [comment]
@0x4Graham Hmm something is not right, Im on develop (local env) and it seems to be working, which link did you check?

**Comment by 0x4Graham** [comment]
https://app-demo.k-f.dev/#/issuer/3521690895/assets/create

**Comment by 0x4Graham** [comment]
Ah, I see on Dev it's working 👍 Sorry!
