### ISSUE TITLE
Reporting: change asset detail report decimals

### ISSUE THREAD

**Issue by hieronx** [centrifuge/apps#2351]
When a user downloads the CSV from an asset detail page, the values should be floating points, not big integers. Like all the reports on the Reporting tab.

**Comment by kattylucy** [comment]
Do we want to have the symbol or without? @hieronx 

![Image](https://github.com/user-attachments/assets/e9ad8057-64e7-43e6-88c0-32f2448c27c9)

**Comment by hieronx** [comment]
Exports shouldn't have the symbol. That way they are easy to parse/analyze in Excel.

**Comment by kattylucy** [comment]
Oh gotcha! Thanks!

**Comment by hieronx** [comment]
@kattylucy I checked the screenshot but hadn't checked the PR preview yet. Two miscommunications I fear:
- The ticket above was meant for the asset detail page, so the report when you click Download on https://app.centrifuge.io/#/pools/4139607887/assets/14.
- We shouldn't add commas into the output of the report. It should be like the existing reports on the Reporting tab, so values look like this:
```
"Asset valuation","2105202.051204","4619208.053028","4659121.767807","9656748.030251","10806411.428107","11863552.86941","12812835.70613","12827981.27332"
```
That way it can easily be analyzed in Excel since the numbers are correct floating points, not strings.

**Comment by kattylucy** [comment]
Ahhh! my bad - Will update the PR, thanks for looking @hieronx

**Comment by kattylucy** [comment]
I believe this is what we are looking for. Let me know otherwise 


![Image](https://github.com/user-attachments/assets/5766d231-f805-4926-a19c-9b5c9682d5f8)
