### ISSUE TITLE
Fees displaying twice in Structure Block in the pool overview

### ISSUE THREAD

**Issue by 0x4Graham** [centrifuge/apps#2366]
![Image](https://github.com/user-attachments/assets/01e588e2-0a3a-41c0-a0f9-7090f0dd2a92)

In the above image from https://app-demo.k-f.dev/#/issuer/980644651

We should on be displaying the type of fees only once

**Comment by onnovisser** [comment]
@0x4Graham After the fix is deployed, you'll need to any fee of the pool that was displaying incorrectly. Only then will the fix be applied. It's because the incorrect fees were already saved in the pool metadata, so the right ones will have to be saved again.
