### ISSUE TITLE
Maturity Date & Financing Date not displaying on Ethereum Pools

### ISSUE THREAD

**Issue by 0x4Graham** [centrifuge/apps#2368]
![Image](https://github.com/user-attachments/assets/92c640d0-a9b1-4cb1-a482-ce274413eb7c)

![Image](https://github.com/user-attachments/assets/4e24ea63-a65b-49a9-8980-132e57f351b1)

It seems that there is an issue in the Ethereum Pools with displaying there Maturity Date & Financing Date of assets. 

See pools here: https://app.centrifuge.io/#/pools/0x53b2d22d07E069a3b132BfeaaD275b10273d381E

**Comment by kattylucy** [comment]
Just FYI for QA - the ticket #2330 ask to remove maturity date, this fix should only apply to financing date.

**Comment by 0x4Graham** [comment]
I made a comment in the the other ticket that Maturity date should be in the table if there is one
