### ISSUE TITLE
Integrate "add member" functionality of new pool admin contracts into UI

### ISSUE THREAD

**Issue by denniswell** [centrifuge/apps#237]
We have build a new pool admin contract for most of the pools which bundles all admin functionality (setting max reserve/creditline, whitelisting etc). Espiecially whitelisting is not working correctly yet with the UI (it does though throuch etherscan).
See e.g. error below:
![image.png](https://images.zenhubusercontent.com/5c922180cf9c5c1a350a748b/463c24c6-07d8-4f0d-9729-0ce99898518b)

At the moment all Maker integrated pools (NS2, CF4, FF1, HTC2) have the pool admin contract plus the newer pools (BR3, GIG1, UP1, PZ1). BL1 and DBF1 have not yet

**Comment by onnovisser** [comment]
Closed by #335
