### ISSUE TITLE
Creating pool with EVM wallet doesn't go to step 2/2

### ISSUE THREAD

**Issue by hieronx** [centrifuge/apps#2375]
When creating a pool using an EVM wallet, the first transaction `Create pool 1/2` is successfully submitted, but 2/2 never starts.

Looking at the logs, it seems `events[0]` here is `undefined`: https://github.com/centrifuge/apps/blob/main/centrifuge-app/src/pages/IssuerCreatePool/index.tsx#L315

**Comment by 0x4Graham** [comment]
@onnovisser @hieronx I've tested this, and the second pool create TX is created. However always fails. 

Not sure if related to this ticket but something to investigate regardless

**Comment by hieronx** [comment]
Just tested this, for me it actually created the pool correclty (including the 2nd step), it is just not triggering the redirect.

**Comment by 0x4Graham** [comment]
Going to move back to Ready for Dev, 

@onnovisser let's make sure it triggers the re-direct.

**Comment by 0x4Graham** [comment]
Working 👏
