### ISSUE TITLE
Bug: Purchase button is not automatically updating

### ISSUE THREAD

**Issue by mustermeiszer** [centrifuge/apps#2403]
## Description
The `Purchase` (probably also the finance flow has the same problem) does not update its colour and clickability automatically after switching the source.

### Examples
**Old Source has not enough balance, new one does &rarr; Button stays gray**
Steps: 
1. Input quantity and price that exceeds balance
2. Switch to source with enough balance
3. Button stays gray and un-clickable

**New Source has not enough balance, old one did &rarr; Button stays blue**
Steps: 
1. Input quantity and price that does not exceed balance
2. Switch to source with insufficient balance
3. Button stays blue and clickable

**Comment by 0x4Graham** [comment]
Tested this, and cannot recreate the original flow. So will mark as passed 👍
