### ISSUE TITLE
Feat: Cross-chain Token Transfers + Token Variant Amalgamation

### ISSUE THREAD

**Issue by mustermeiszer** [centrifuge/apps#2405]
## Goal
Allow users to send tokens 
* from Centrifuge to other EVM chains
* from other EVM chains to Centrifuge
* Amalgamate all USDC variants into a single holding section
   * Do the underlying token-muxing and swapping implicitly - including for investing

## UI
*NOTE: ONLY show other networks IF the user is using an EVM-compatible wallet*
*NOTE: Sending to other networks MUST still be possible*

**[Design Figma Files](https://www.figma.com/design/egKzXqF777A35BZMzPcoYD/Portfolio?node-id=1119-10873&m=dev)**

## Actions
*NOTE: The UI can freely decide which underlying assets of an AMALGAMATED_ASSET to use for all `tokenMux`-actions*

### Token Balance Queries
*ON Centrifuge Chain*

* Retrieve the metadata of all assets the user is holding 
* Check if any metadata of those assets have `localRepresentation` set
* Add all assets balances with the same `localRepresentation` + the actual `LocalAsset(id)` balance together into one balance - as a name use the name of the `LocalAsset(id)`
  *NOTE: We call these assets AMALGAMATED_ASSET in the following spec.*
* All other balances should be shown as separate balances

*ON EVM Chain*

* query erc20 contract for balances

### Send Actions
This action needs to select two networks `SendingNetwork` and `ReceivingNetwork`. The `SendingNetwork` is implicitly chosen by the user, depending on which account on which network the user chooses to click the CTA for. The `RecivingNetwork` can be chosen in the dialog.

*ON Centrifuge Chain*

IF AMALGAMATED_ASSET
* Check if balance of `LocalAsset(id)` is sufficient for transfer 
* IF NOT 
   &rarr; add `tokenMux.deposit(asset, REMAINING_AMOUNT)` before the transfer
* IF `destination == CentrifugeChain` 
   &rarr;  add `tokens.transfer(..)`
* IF `destination == EVM Chain` 
   &rarr; add `liquidityPools.transfer(..)`
* IF `destination == Polkadot Parachain`
  &rarr;  add `xtokens.`

ELSE
* IF `token == TrancheToken`
   * IF `destination == CentrifugeChain` 
      &rarr;  add `tokens.transfer(..)`
   * IF `destination == EVM Chain`
     &rarr; add `liquidityPools.transferTrancheTokens(..)`
   * IF `destination == Polkadot Parachain`
     &rarr; NOT POSSIBLE!
* ELSE
   * IF `destination == CentrifugeChain` 
      &rarr;  add `tokens.transfer(..)`
   * IF `destination == EVM Chain`
     &rarr; add `liquidityPools.transfer(..)`
   * IF `destination == Polkadot Parachain`
     &rarr; add `xtokens.transfer(..)`

*ON EVM Chains*
* IF `token == TrancheToken`
   * IF `destination == CentrifugeChain || other EVM Chain` 
      &rarr; call `poolManager.transferTrancheTokens(..)`
   * IF `destination == current EVM Chain` 
      &rarr;  call`erc20.transfer(..)`
* ELSE 
  &rarr; call `erc20.transfer(..)`

### Receive Actions
Receiving will only display the current address the user is connected with. The network and hence the account representation is implicitly chosen by the user, depending on which account on which network the user chooses to click the CTA for.

### Redeem Actions
This action selects the network depending on which account on which network the user chooses to click the CTA for. It is important to show the user that he is redeeming in USD-Value. Highlight, that this is an approximate amount depending on the last token price and how many tranche tokens will be used for that.

*ON Centrifuge Chain*
   &rarr; call `investments.update_redeem_order(..)`

*ON EVM Chains*
   &rarr; call `erc7540.requestRedeem(..)`

### Investment Actions
This action selects the network depending on which account on which network the user chooses to click the CTA for.

*ON Centrifuge Chain*

Currently, the user needs to have the pool currency to invest. But there are special currencies called `CurrencyId::LocalAsset(id)` that can 
* be pool currencies
* users can swap into without overhead 

IF a pool has a `LocalAsset(id)` as its currency the UI MUST
* retrieve the metadata of all assets the user is holding 
* check if any metadata of those assets have `localRepresentation == id`
* show the possible balance for investing as sum of the above assets and the holdings of `LocalAsset(id)`

For investing the UI needs to generate a batch of 
* `tokenMux.deposit(asset, amount)` per asset
followed by the actual 
* `investments.update_invest_order()` tx  

*ON EVM Chains*
  &rarr; call `erc7540.requestDeposit(..)`

**Comment by mustermeiszer** [comment]
The MVP of this ticket should be 

* NO UI changes besides adding a `Send` button to tranche tokens
  *THis also means ONLY display holdings from the network a user is connected to*
* Implement sending for tranche tokens shown below below

ON Centrifuge Chain
* IF `destination == CentrifugeChain`
   → add `tokens.transfer(..)`
* IF `destination == EVM Chain`
   → add `liquidityPools.transferTrancheTokens(..)`
* IF `destination == Polkadot Parachain`
    → NOT POSSIBLE!
    
ON Evm Chains
* IF `destination == CentrifugeChain || other EVM Chain`
   → call `poolManager.transferTrancheTokens(..)`
* IF `destination == current EVM Chain`
   → call `erc20.transfer(..)`

**Comment by hieronx** [comment]
> IF destination == CentrifugeChain || other EVM Chain
> → call poolManager.transferTrancheTokens(..)

Best to do this after https://github.com/centrifuge/apps/issues/2331 is done, and use `CentrifugeRouter.transferTrancheTokens`.
