### ISSUE TITLE
Fix YoY growth on website

### ISSUE THREAD

**Issue by sophialittlejohn** [centrifuge/apps#2458]
YoY growth on centrifuge website is currently showing 0%. The value is still retrieved from the old goldsky subgraph we should fetch the data from the subquery instead is it was done for cent-app

**Comment by kattylucy** [comment]
Is this applicable anymore since we are now removing YoY from the website ? 

see here
https://kflabs.slack.com/archives/C06JDEJB31C/p1727365021729639

**Comment by sonam-jo** [comment]
No longer relevant, we will remove all YoY growth % from the UI for now. Will close this ticket.
