### ISSUE TITLE
Issue with deploying Tranche & Liquidity pool on a new chain

### ISSUE THREAD

**Issue by 0x4Graham** [centrifuge/apps#2517]
There is a bug when trying to deploy the liquidity pool and tranche tokens on a new chain. See errors below: 

![image](https://github.com/user-attachments/assets/da2086b2-817b-4f48-a832-debf46932c9d)
![image](https://github.com/user-attachments/assets/99cf500f-ab21-4b45-af94-2453a607386d)

**Comment by mustermeiszer** [comment]
Solved. Indexing catches some internal logic as a revert. But all is good. Logic works
