### ISSUE TITLE
Incorrect CTA for certain actions. Missing Reject option

### ISSUE THREAD

**Issue by 0x4Graham** [centrifuge/apps#2542]
See discussion here for context: 

https://kflabs.slack.com/archives/C063K04K1F0/p1730820355691169

as the originator I shouldn’t be able to approve but should be able to reject. There is no longer a reject button. Also There should likely be a reject button for the other signers as well. Current options are sign or just leave it

**Comment by onnovisser** [comment]
Can't reproduce the bug, the UI looks right to me when connected with the mentioned account. Also Substrate doesn't allow approvers to cancel. Only the creator of the multisig transaction can cancel it.
