### ISSUE TITLE
Claim CFG reward: Display remaining days of minimum holding period

### ISSUE THREAD

**Issue by denniswell** [centrifuge/apps#256]
#### Background
Currently users just know that they can't claim CFG rewards yet, because they haven't passed the min holding period, but they don't know whether they have to wait another 24 or 2 days.

#### Approach
- The system informs users upfront about the minimum holding period
- If users can't claim CFG rewards yet, the system informs users about the remaining duration till claiming is possible.

#### Text changes to "How Rewards Work"
The minimum holding period is added to the instruction card "**How Tinlake Works**":
`CFG rewards are earned on Ethereum based on your Tinlake investments, but are claimed on Centrifuge Chain. The Tinlake investment account requires to be linked to a Centrifuge Chain account. Rewards for investment can be claimed after a minimum holding period of 30 days.`

Before:
`CFG rewards are earned on Ethereum based on your Tinlake investments, but are claimed on Centrifuge Chain. To claim your rewards you need to link your Tinlake investment account to a Centrifuge Chain account receiving and holding your CFG.`

##### Case conditions
- Ethereum account is connected
- Centrifuge Chain account is linked
- User has invested

Until the minimum holding period has been completed, the system shows an **alert message** (feat. an info icon) in the case defined above. The button `Claim CFG` is **disabled**.

Message:
`Minimum holding period pending — 2 days remaining...`
`You can clain your rewards once the minimum period of 30 days holding your tokens has passed.`

![image](https://user-images.githubusercontent.com/23652850/128198271-f0d1b07d-f82b-41cd-8dad-7460b976e59f.png)

[Figma](https://www.figma.com/file/EWziKt1qCFdHGhWdnkrcKf/Tinlake-UI?node-id=5236%3A10536)

#### System feedback of complete minimum holding period
After the minimum holding period has passed, the system shows a confirmation feedback informing that rewards are ready to be claimed. The button `Claim CFG`is **enabled**.

Message:
`Minimum holding period passed` 
`You can now claim your earned reward of 41 CFG.`

![image](https://user-images.githubusercontent.com/23652850/128198469-ea6b30bb-d8d6-4f80-aadd-98f02b67b2a9.png)
[Figma](https://www.figma.com/file/EWziKt1qCFdHGhWdnkrcKf/Tinlake-UI?node-id=5253%3A10608)

**Comment by armandomistral** [comment]
Idea: Can we show the accrued and unclaimed amount of rewards of a connected account on the homepage?

**Comment by armandomistral** [comment]
@denniswell, do you have a screenshot of the current implementation?
