### ISSUE TITLE
Display daily pool update in Slack

### ISSUE THREAD

**Issue by denniswell** [centrifuge/apps#268]
The bot similarly gives a daily epoch summary per pool in each of the pool channels (or when an epoch was closed). It would be nice to also get one daily overview of all pools in the #pool-management channel, similar to lucas output, 
e.g. showing
- Locked transactions
- Current reserve/Maxreserve
- Epoch status (Ongoing, Min duration passed, Submission period)

![image.png](https://images.zenhubusercontent.com/5c922180cf9c5c1a350a748b/5a769425-cc
0e-426b-904f-50b93dfff4cb)

**Comment by onnovisser** [comment]
Closed by #324
