### ISSUE TITLE
Token prices on investor Dashboard off

### ISSUE THREAD

**Issue by denniswell** [centrifuge/apps#269]
Token prices on Investor Dashboard are still completely off sometimes confusing users. See also #157
![](https://storage.googleapis.com/centrifuge-hackmd/upload_d0b17d77c309f2764ada4dd1bfa00da8.png)

![](https://storage.googleapis.com/centrifuge-hackmd/upload_5f048eb44c51e442d7576bef43c0305d.png)

**Comment by jpangelle** [comment]
Queries to the staging graph `jennypollack/tinlake-rewards-staging` is responding with possibly incorrect values:

<img width="811" alt="Screen Shot 2021-07-02 at 12 29 31 PM" src="https://user-images.githubusercontent.com/28536523/124271180-c1a27880-db02-11eb-9968-61e57cfde645.png">

Need to test on a `mainnet` subgraph

**Comment by jpangelle** [comment]
Seems to be intermittent issue with responses from the subgraph 😞

**Comment by onnovisser** [comment]
Fixed by #316
