### ISSUE TITLE
Investor portfolio: Show also when empty (not invested)

### ISSUE THREAD

**Issue by armandomistral** [centrifuge/apps#288]
As a consequence of always showing the portfolio menu item in the app toolbar (see [App toolbar: Add menu items (rewards, portfolio) and responsive support#286](https://app.zenhub.com/workspaces/centrifuge-applications-5fa29e924059e5001625e2a3/issues/centrifuge/apps/286)), the portfolio view must also show an empty state. The empty state is presented when a user has connected a wallet, but has not made any investment yet.

Instead of the list of invested pools the system shows a message (similar to the type on the dashboard, just not expandable; is there a component for it?):

**Message**:
`You do not have any investments. 
[Browse pools] to invest in`

Since the Portfolio has become a first-level navigation item, the back-link to home (Tinlake dashboard) is no longer needed and can be removed. Instead of the arrow icon, the DAI token icon is shown.

![image](https://user-images.githubusercontent.com/23652850/127635231-7bfaf8ce-bd0c-4ff8-8ab3-50dc0ced6317.png)

[Figma mockup] (https://www.figma.com/file/EWziKt1qCFdHGhWdnkrcKf/Tinlake-UI?node-id=5613%3A18910)

**Comment by lucasvo** [comment]
I don't think the language on this is very good. `You do not have any investments. Browse all pools.` feels less clunky.

**Comment by armandomistral** [comment]
Yeah, I think the message should communicate three things:
1. The current state: "You do not have any investments"
2. The future state / What investors can expect once they are invested
3. What to do next / how to get started: "Browse all pools" / "Go to the Dashboard to browse for pools"
