### ISSUE TITLE
Discourse Link Improvements

### ISSUE THREAD

**Issue by lucasvo** [centrifuge/apps#298]
Two small changes:
* Hover should make the icon blue as well
* We don't call it "discourse" anywhere else, on gov.centrifuge.io we call it *Centrifuge Governance Forum!*. Perhaps the link should be called *Forum Discussion*

![2021-07-29-153828_1117x277_scrot](https://user-images.githubusercontent.com/31727/127524740-4f7c4a38-2b37-416d-abf5-02ab2059247d.png)

**Comment by jpangelle** [comment]
@offerijns fixed with this pr: https://github.com/centrifuge/tinlake-pools-mainnet/pull/44
