### ISSUE TITLE
Some loans cannot be repaid on Kovan

### ISSUE THREAD

**Issue by denniswell** [centrifuge/apps#38]
So, I was always wondering who owns e.g. Asset ID 15, because I wasn’t able to repay it with either my borrower nor the master admin (=don’t see the components). I was always too lazy to check the proxy, but did now and turns out it belongs to my borrower. Is it possible that if a loan is past the due date (and it falls out of the NAV), the UI also doesn’t catch anymore that it can and should still be repaid? Because I see the components for the loan I just borrowed. May also be other reasons...
![image.png](https://images.zenhubusercontent.com/5c922180cf9c5c1a350a748b/8f7a81bb-d735-4ef9-b890-f36b8bc5ec27)

**Comment by offerijns** [comment]
I think this might be fixed already.
