### ISSUE TITLE
Repaid/closed financing details cannot be loaded anymore

### ISSUE THREAD

**Issue by denniswell** [centrifuge/apps#382]
When I want to access the financing details of a repaid/closed financing it is not loading anymore. Instead I see `Could not find asset x`.

Some examples below

https://tinlake.centrifuge.io/pool/0x0CED6166873038Ac0cc688e7E6d19E2cBE251Bf0/bling-series-1/assets/asset?assetId=58
![image.png](https://images.zenhubusercontent.com/5c922180cf9c5c1a350a748b/880dec11-d44c-4e18-9a73-736cd339e4aa)

https://tinlake.centrifuge.io/pool/0xdB3bC9fB1893222d266762e9fF857EB74D75c7D6/consolfreight-4/assets/asset?assetId=106
![image.png](https://images.zenhubusercontent.com/5c922180cf9c5c1a350a748b/d669564b-2cec-4efa-8f2c-44c769c28730)

**Comment by onnovisser** [comment]
Fixed by #383
