### ISSUE TITLE
Fix 0.00% DROP return bug

### ISSUE THREAD

**Issue by denniswell** [centrifuge/apps#529]
On the Cauris Pool we currently display 0.00% DROP APY on the dashboard. This is technically correct (there are no DROP investments so DROP price is still 1.0000 so DROP return is 0.00%), but in this case we should show the `Expected APR: x.xx%` as we do for other upcoming pools.

I am not sure what is causing this, because on the pool overview and investment page we correctly show only the 8.50% APR it seems. Perhaps the condition in the UI from which point onwards the real DROP APY is shown is based on the first investment or financing or sth like this. Ideally it should be shown based once two conditions are true:
(i) The first asset was financed
(ii) The DROP tranche value is > 0 for more than 30 days

Before that we should always show the `Expected APR: x.xx%`. While we are at it, could the `Expected APR: x.xx%` always be shown with two digits?

![image.png](https://images.zenhubusercontent.com/5c922180cf9c5c1a350a748b/23942fc2-0da4-4656-a9d4-eb8f66af82e0)

**Comment by onnovisser** [comment]
Closed by #533
