### ISSUE TITLE
Tinlake: AO logo updates

### ISSUE THREAD

**Issue by armandomistral** [centrifuge/apps#534]
## Background
Some AO logos used by Tinlake are not up to date.

## AO logo updates
* Gig pool – Badge (logo)
* Gig pool – Large logo
* FF1 badge logo
* FF2 badge logo

### Reference
[Tinlake specs - Fixing pool logos](https://centrifuge.hackmd.io/XWLg1b4dQty_yOT-5A-rSw)

**Comment by techgirlonlinee** [comment]
![FF1.svg](https://images.zenhubusercontent.com/6107b1cbfd1a371eb8f3ae2b/0939fc97-4cc2-4ff0-a26a-7505ec672b3a)![ff2.svg](https://images.zenhubusercontent.com/6107b1cbfd1a371eb8f3ae2b/690fbf77-5b23-411d-b282-6d444d8f92d2)![gigBadge.svg](https://images.zenhubusercontent.com/6107b1cbfd1a371eb8f3ae2b/c821a567-f4b2-4a18-a4fd-49774c682579)![gigLargeLogo.svg](https://images.zenhubusercontent.com/6107b1cbfd1a371eb8f3ae2b/8bd8b3a0-fed8-4701-85d5-d8845d0fbc6f)

**Comment by armandomistral** [comment]
Closed because replaced by another ticket...
