### ISSUE TITLE
Bug in TIN onboarding flow

### ISSUE THREAD

**Issue by denniswell** [centrifuge/apps#540]
When I try to onboard to TIN behind the feature flag`onboarding?tranche=junior`  e.g. https://tinlake.centrifuge.io/pool/0x53b2d22d07e069a3b132bfeaad275b10273d381e/new-silver-2/onboarding?tranche=junior`, while being connected with an account that is already whitelisted, I see the right state but can't do anything...
![image.png](https://images.zenhubusercontent.com/5c922180cf9c5c1a350a748b/45c43d57-db2f-48f4-a1d6-c16cee792367)

**Comment by onnovisser** [comment]
did you see the Sign in with Securitize button and is it the Sign Agreement button that's not showing or did you not see that either?
