### ISSUE TITLE
Export token balances by account

### ISSUE THREAD

**Issue by lucasvo** [centrifuge/apps#552]
We need a way to manually export token balances as a CSV for a specified account.

```
{
  dailyInvestorTokenBalances (where: {account: "$ADDR"}) {
    day {
      id
    }
    pool {
      id
    }
   seniorTokenAmount
   seniorTokenValue
   seniorSupplyAmount
   seniorPendingSupplyCurrency
   juniorTokenAmount
   juniorTokenValue
   juniorSupplyAmount
   juniorPendingSupplyCurrency
  }
}
```

Less simple but probably still worth to add would be the amount of CFG earned by day for each investor. Unfortunately we do not have this in the graph yet.

**Comment by denniswell** [comment]
Closed here for now, moved to subgraph backlog
https://centrifuge.hackmd.io/UJUJyF16Q9uQO1zAg44mXA?view
