### ISSUE TITLE
Out of gas: proxyTransferIssue

### ISSUE THREAD

**Issue by bitwiseguy** [centrifuge/apps#556]
I kept getting a tx out of gas error when trying to issue a loan against my NFT. The latest version of @centrifuge/tinlake-js that gets installed by npm install is "3.0.0-develop.35" but the code that is installed sets a gas limit of 300000 for the proxyTransferIssue tx whereas the code on the main branch of the centrifuge/apps repo shows a limit of 400000 for the same [line of code](https://github.com/centrifuge/apps/blob/main/tinlake.js/src/actions/proxy.ts#L91). By editing the source code of @centrifuge/tinlake-js in my node_modules directory to increase the gas limit to 400000 I was able to get the transaction to execute successfully.

Side note:  the way the Object.assign statements are written in the installed version of tinlake-js, the user is not able to pass in a gasLimit to override the default value. If we re-write the Object.assign statements such that the default gasLimit is the left-most argument, it would allow the user to override the default

[Here](https://kovan.etherscan.io/tx/0x11ad885acf1bbd8c863beb32426fad5504da400600a21140642b1f80d391cbc3) is the failed tx with a gasLimit of 300000.

[Here](https://kovan.etherscan.io/tx/0x577c4495bf684981d1e30645c8bdfcdf319e70fbd3bcda6dc3627b76ec399433) is the successful tx with a gasLimit of 400000.

Suggestion: perhaps we could use ethers.js `estimateGas` method instead of passing a `gasLimit` by default?

**Comment by bitwiseguy** [comment]
I believe this would be fixed if a new version of the `@centrifuge/tinlake-js` package was pushed to `npm`, assuming that the package was sourced from the `centrifuge/apps/tinlake.js` code and not from the `centrifuge/tinlake.js` repo

**Comment by denniswell** [comment]
Closing for now, we have little usuers running into this, gas limits are a bit variable and can be manually increased if necessary
