### ISSUE TITLE
display of pool overview stats

### ISSUE THREAD

**Issue by charleenfei** [centrifuge/apps#56]
<img width="498" alt="Screenshot 2020-12-15 at 16 51 36" src="https://user-images.githubusercontent.com/16255463/102238364-f39d1600-3ef5-11eb-9a0f-6d5971d62e25.png">

these two stats could be in a drop down, since it is a bit confusing that the pool value is the sum of them but they are displayed as three separate items

**Comment by lucasvo** [comment]
The reserve is an important metric, it shows how much cash drag is in the pool. @philipstanislaus is reviewing how we can show better though which pools need liquidity and which ones don't.
