### ISSUE TITLE
Bug: Error when claiming CFG rewards

### ISSUE THREAD

**Issue by armandomistral** [centrifuge/apps#576]
When claiming an earned reward of 0.570 CFG to address `4f1nGaMQSZStX16DyaAVpY13p996Yp3CkC2D8aQtAjxRk5R5`, the claiming does not finish. 

* The address exists and has a balance greater than 0. 
(see https://centrifuge.subscan.io/account/4f1nGaMQSZStX16DyaAVpY13p996Yp3CkC2D8aQtAjxRk5R5)
* The invested amount is 20 DAI
* This is the first claiming, and the minimum holding period has ended

The console shows the following error:
`Uncaught Error: findMetaError: Unable to find Error with index 0x1e01/[{"index":30,"error":1}]`

Screenshot:
![Error - Claim rewards.png](https://images.zenhubusercontent.com/6090f1ca0d0c23544195c7ec/ff916611-3a36-44aa-9561-2e2c3e57c16f)

**Comment by AStox** [comment]
A lot has changed with claiming, and I doubt this bug is still relevant. Going to close for now but feel free to re-open if this bug persists after claiming is back online
