### ISSUE TITLE
Close epoch button not displayed in "Minimum duration ended - no orders locked" state

### ISSUE THREAD

**Issue by denniswell** [centrifuge/apps#591]
I am connected with my pool admin address which should usually allow me to close epochs. It seems that in state "Minimum duration ended - no orders locked" we don't display the button in the UI. Generally makes sense as there is no reason to execute Except if you want to make repaid funds available for origination.
So we should also display the button in this state.

![image.png](https://images.zenhubusercontent.com/5c922180cf9c5c1a350a748b/447809dd-03f9-471c-aee9-f7b1ad4c9ddb)

**Comment by denniswell** [comment]
Alessio looked into it. The underlying issue seems to be with the different admin set-ups as the button is visible for admins with pools with the new admin contract. Let's revisit once the big spell is in and all pools are on the latest admin contract...

**Comment by annamehr** [comment]
@denniswell is this ticket still up-to-date and important to fix before blocktower pool launch?
