### ISSUE TITLE
Utlity to create calldata for Tinlake Reward Address Link

### ISSUE THREAD

**Issue by lucasvo** [centrifuge/apps#607]
Users who hold tokens in BitGo for custody will need to submit a manual transaction in the BitGo UI to link their address. They do this by pasting the contract address (TinlakeClaimRAD contract) and the calldata in their UI. We need a very simple tool (hidden behind a feature flag) that allows users create this calldata for the following transaction:

Example TX: https://goerli.etherscan.io/tx/0x06a893ee845959ee8850f8bcc9e81143e549b870b33f6fdd106d920758525cf4
Place where we trigger this transaction for users who use metamask/other wallet via web3 provider: https://github.com/centrifuge/apps/blob/cb157ad1bbc4fea231be9ad810e84b8b98470550/tinlake-ui/containers/SetCentAccount/index.tsx

The UI should show a simple form with one input asking for a Centrifuge address. We should validate that the input is a valid centrifuge address and encode it the same way we do in the above linked page. The calldata should be then be shown to the user.

We can use the following helper in ethers.js: https://github.com/ethers-io/ethers.js/issues/478

**Comment by AStox** [comment]
Finally starting to get some time to get to this. This is still a priority right @lucasvo?

**Comment by denniswell** [comment]
Closed here for now, moved to subgraph backlog
https://centrifuge.hackmd.io/UJUJyF16Q9uQO1zAg44mXA?view
