### ISSUE TITLE
Add a discord link for each pool (AO)

### ISSUE THREAD

**Issue by ImdioR** [centrifuge/apps#610]
![image](https://user-images.githubusercontent.com/90972248/152857021-3b9a8fe1-08e7-4ce0-97d2-e237a72b61e0.png)
![image](https://user-images.githubusercontent.com/90972248/152860883-1d56fb85-7aed-4614-b370-2f00fec5b927.png)

**Comment by denniswell** [comment]
Moving to apps repo
