### ISSUE TITLE
Set max reserve not working for CF4

### ISSUE THREAD

**Issue by denniswell** [centrifuge/apps#64]
My address`0x71d9f8CFdcCEF71B59DD81AB387e523E2834F2b8` is admin on the Assesor Wrapper for CF4, check here https://etherscan.io/address/0x533ea66c62fad098599de145970a8d49d6b5f9c4#readContract

When I want to change the max reserve amount, I get the error message: `Cannot estimate gas`... 
Setting the max reserve amount for PC3 with the same address worked though

![image.png](https://images.zenhubusercontent.com/5c922180cf9c5c1a350a748b/8bb84559-2ea9-4940-85bc-3d42da54bfc6)

**Comment by charleenfei** [comment]
@denniswell I checked the assessor wrapper for cf4, your address is not admin, this is probably why you get the error message

**Comment by charleenfei** [comment]
@denniswell  I just checked the assessor contract, the maxReserve amount is indeed 500000000000000000000000 (500000000000000000000000 / (10 * 10 ^18) = 50,000) so i think your update worked... not sure why this failed on metamask. can you see if it throws another error on another pool?

**Comment by charleenfei** [comment]
I will put the UI update in another ticket, since this is unrelated to the bug.

**Comment by charleenfei** [comment]
bug is due to using an admin address which is not whitelisted, closing for now
