### ISSUE TITLE
Bug - Collection description not displayed on collection page 

### ISSUE THREAD

**Issue by tsx49** [centrifuge/apps#640]
**Scenario executed**
Given a user is browsing NFT collections
When the user selects a collection
Then the collection page should load
And it should display the NFTs within the collection, the collection name and the Collection description

**Steps to reproduce the bug**

1. Navigate to create collection screen
2. Add a name and description
3. Create collection and sign transaction
4. Navigate to newly created collection

**Expected result**
Collection description that was entered should be displayed

#### Design
* If set, the collection description paragraph is placed at the position of the first NFT cards. 
* Text style is Body 1
* Min-width is 330 px, max-width is 448px

[Figma frame](https://www.figma.com/file/4P9h3fF0oDI5U72ghXovdk/Altair-NFT-Studio?node-id=738%3A5983)

###### Empty collection
* If the collection does not contain any NFT, a message is shown: `The collection does not contain any NFT`

[Figma frame](https://www.figma.com/file/4P9h3fF0oDI5U72ghXovdk/Altair-NFT-Studio?node-id=740%3A6284)

**Actual result**
No collection description is being displayed

- Alessio to change to new version

**Comment by armandomistral** [comment]
Hey @tsx49, I've updated the specs adding the design definition. It's already discussed and being implemented with @alessioscalici
