### ISSUE TITLE
Tranches pool creation/management - MVP v1

### ISSUE THREAD

**Issue by EstherCentrifuge** [centrifuge/apps#645]
[Specis in HackMD](https://centrifuge.hackmd.io/1OiMlCCWTL2YwUN8c_sFnA?both#Tranches)
[Figma node Junior Tranche](https://www.figma.com/file/d1bEBkwllUQe27nQM6VlJu/Centrifuge-app?node-id=1971%3A54008)
[ Figma node mutiple Tranches](https://www.figma.com/file/d1bEBkwllUQe27nQM6VlJu/Centrifuge-app?node-id=1985%3A53974)
[Figma node for Tranches inside the pool management/settings](https://www.figma.com/file/d1bEBkwllUQe27nQM6VlJu/Centrifuge-app?node-id=1971%3A54531)

**Open points:**
Visuals on Figma might get updated within the first 2 das of ticket creation

**Summary**
in this section 1 tranche is predefined see Junior Tranche the user has the option to add more tranches and edit the details/values of these tranches.
Within the pool management/settings/configurations the issuer/admin can add, edit and remove tranches.
The Junior tranche can be renamed but never removed. 

Note that the for any new tranche the are validation logics on the values:
- The Minimum protection needs to be equal or higher then a previous created tranches
- Fixed interest rate needs to be equal or lower then a previous created tranches

Tranches fields:
- Seniority number
- Token name
- Token symbol
- Minimum protection 
- Fixed Interest rate (APR)

**Comment by onnovisser** [comment]
@EstherCentrifuge
- Is there a maximum number of tranches that can be added?
- The design shows a "min investment amount" input, but the spec doesn't mention it. Are we omitting that for this version?
