### ISSUE TITLE
Bug - Issuer can't claim rewards on Tinlake

### ISSUE THREAD

**Issue by annamehr** [centrifuge/apps#649]
* Issuer can't claim rewards
* Incorrect amount of CFG rewards shown

* New whitelisted ETH address which has been connected to the Centchain account: 0x4AD53C582492a69cA912D998d7d3FDaF5D99a110  
* CF ID: 0x09e43329552c9d81cf205fd5f44796fbc40c822e

![image (4)](https://user-images.githubusercontent.com/31280003/156157773-776d6797-72e9-4b2a-9a60-751ff5b9782e.png)

**Comment by AStox** [comment]
I was able to claim the rewards for the user via the UI, but as for the wrong rewards shown, what amount of rewards were they expecting? Lower or higher than what was shown to them?
