### ISSUE TITLE
Improvement - Ability to add an image as a collection logo

### ISSUE THREAD

**Issue by tsx49** [centrifuge/apps#656]
**User Story**

As a user
I want to add a logo when creating a collection
So that my collection can be distinguishable 

**Background**
This aim of this story is to enable users to add a logo/image when creating a collection. The image will display as the the collection cover on the home page, instead of displaying the NFTs within the collection - which is what we currently display. The image will also be displayed within the collection view page. This change should improve performance, as one image is displayed instead of up to four (Alessio/ Onno).
**Maximum file size** = **1mb** Onno/Alessio: Anything over 1mb may lead to issues loading images
**Supported files types** = SVG, PNG, JPEG, GIF, BMP, ICO, WebP, AVIF

**Questions?**
?N/A

**User Journey**

1. User connects wallet
2. User selects 'Create collection'
3. UI displays 'Create new collection' modal
4. User selects and uploads image
5. User enters collection name
6. User enters collection description
7. User clicks ‘Create’ button
8. User signs transaction (JS Wallet pop-up)
9. UI provides transaction pending confirmation (notification toast)
10. Transaction confirmed on-chain - Purchase successful 
11. UI provides action confirmation (notification toast)
12. Collection opens: the collection name, description and logo are displayed

#### Mockups
**To be added**

**Acceptance Criteria**

**Scenario 1 -  User clicks create collection**
Given a user is on the homepage
When they select the ‘create collection’ button
Then a modal should be displayed
And it should allow them to select an image to upload, enter a description and a name

**Scenario 2 -  (Success) User uploads a supported file type under limit**
Given a user is attempting to create a new collection
When the a user selects a  file to import that is either: SVG, PNG, JPEG, GIF, BMP, ICO, WebP, AVIF
And the file size is 1mb or below
Then the file should be uploaded successfully 

**Scenario 3 - User uploads an unsupported file type**
Given a user is attempting to create a new collection
When the a user selects a  file to import that is not either: SVG, PNG, JPEG, GIF, BMP, ICO, WebP, AVIF
Then the file should be not be uploaded
And the user should be presented with the following error 'File format not supported'
And the user should be able to close the error message to return to the upload screen.

**Scenario 3 - User uploads a supported file type that exceeds file size limit**
Given a user is attempting to create a new collection
When the a user selects a  file to import that is either: SVG, PNG, JPEG, GIF, BMP, ICO, WebP, AVIF
And the file size is above 1mb
Then the file should be not be uploaded
And the user should be presented with the following error 'File size exceeded'
And the user should be able to close the error message to return to the upload screen.

**Scenario 4 -  Happy path 1 - User creates a collection with image**
Given a user is attempting to mint an NFT
And they have successfully uploaded an image
And they have entered a collection name
And they have entered a collection title
When they select the 'create' button
And the transaction is confirmed on-chain
Then the logo that was uploaded should be displayed on collection page
And on the homepage as the collections cover art

**Scenario 5 -   Happy path 2 - User creates a collection with no image**
Given a user is attempting to mint an NFT
And they have not uploaded an image
And they have entered a collection name
And they have entered a collection title
When they select the 'create' button
And the transaction is confirmed on-chain
Then a the Altair logo should be displayed on collection page
And on the homepage as the collections cover art

**Comment by techgirlonlinee** [comment]
Upload file form is added to the modal below Description form. See https://www.figma.com/file/4P9h3fF0oDI5U72ghXovdk/Altair-NFT-Playground?node-id=991%3A9487. The file label copy is "Upload collection logo (JPEG, SVG, PNG, or GIF up to 1 MB)" The error state corresponds to the form design in Fabric. 

If the user does not upload a collection image, the altair logo mark is displayed instead. See https://www.figma.com/file/4P9h3fF0oDI5U72ghXovdk/Altair-NFT-Playground?node-id=969%3A8728 for how it looks for the collection page. See https://www.figma.com/file/4P9h3fF0oDI5U72ghXovdk/Altair-NFT-Playground?node-id=833%3A6884 for how the card is displayed for the homepage. The background is centrifuge black and the altair logo mark is displayed in the center with the 80px width.

**Comment by alessioscalici** [comment]
Closed by https://github.com/centrifuge/apps/pull/717
