### ISSUE TITLE
Improvement - Ability to change the uploaded image (before minting )

### ISSUE THREAD

**Issue by tsx49** [centrifuge/apps#657]
Nico to add remove image button

**Comment by techgirlonlinee** [comment]
The uploaded image gets dimmed and the default cursor changes to pointer cursor. When the user clicks the image, the whole page gets dimmed and the native image selection appears. 
https://www.figma.com/file/4P9h3fF0oDI5U72ghXovdk/Altair-NFT-Playground?node-id=979%3A9130
