### ISSUE TITLE
Improvement - Move the ‘Description’ section above the ‘Source’

### ISSUE THREAD

**Issue by tsx49** [centrifuge/apps#658]
#### Background
The aim of this improvement is to move the 'Description' label and text above the 'Source' label and text. The description is the most important information on this page, and it should be displayed first.

**As-is**
![image](https://user-images.githubusercontent.com/95627013/156275037-46c1b6fe-abe1-4b7a-a01c-cf2dabe6844e.png)

**To-be**
![image](https://user-images.githubusercontent.com/95627013/156274951-de5ace15-be20-4360-b022-2fe533849269.png)

**Dev Notes**
-
-

**Comment by alessioscalici** [comment]
Closing as already fixed
