### ISSUE TITLE
Improvement - Display amount of NFTs in collection

### ISSUE THREAD

**Issue by tsx49** [centrifuge/apps#660]
**Araya to do mock-up** 

**User Story**

**As a** user
**I want** to see the amount of NFTs within a collection
**So that** I can determine the scarcity 

**Questions?**
?N/A

#### Background
 The aim of this ticket is to display the amount of NFTs contained with a collection, this will be displayed on Collection view page, and on the Collection page . This counter will update each time an additional NFT is minted within the collection. 

Outside collection
![image](https://user-images.githubusercontent.com/95627013/156995174-c5f73b2e-c895-4927-bd82-791569f1a8c8.png)
Inside collection
![image](https://user-images.githubusercontent.com/95627013/156976011-03e00996-a9e1-4929-9d7c-1f9bde84fb6c.png)

#### Mockups
-To be added

**Scenario 1 -  Home page collection with 1 or more NFTs **
Given at least 1 NFT have been minted within a collection
When a user lands on the NFT playground homepage
Then the collection card  should display the current total amount of NFTs minted as 'x items'

**Scenario 2 -  Home page collection 0 NFTs**
Given no NFTs have been minted within a collection
When a user lands on the NFT playground homepage
Then the collection card  should display the current total amount of NFTs minted as '0 items'

**Scenario 3 -  Collection page collection with 0 NFTs**
Given no NFTs have been minted within a collection
When a user enters a collection 
Then the collection should display as '0 items'

**Scenario 4 -  Collection page collection with 1 or more NFTs**
Given at least 1 NFT have been minted within a collection
When a user enters a collection 
Then the collection should display the current total amount of NFTs minted as 'x items'

**Comment by techgirlonlinee** [comment]
<img width="996" alt="Screenshot 2022-03-08 at 13 03 09" src="https://user-images.githubusercontent.com/49897854/157237873-3cedc00a-1d8f-432c-afda-6ed4aaadfd6a.png">
Semi-transparent box with a label on the bottom right of the image. It is right-aligned so when the digit numbers increase within the box, the label still sticks to the right part of the card with 8px padding (on the right and bottom).

**Comment by techgirlonlinee** [comment]
The number of items within the collection is on the left side, top of the first card rows. See https://www.figma.com/file/4P9h3fF0oDI5U72ghXovdk/Altair-NFT-Playground?node-id=972%3A8877
