### ISSUE TITLE
Prevent borrower from Locking NFT that is not in his wallet

### ISSUE THREAD

**Issue by denniswell** [centrifuge/apps#67]
This is important and should be fixed soon.

We currently allow the borrower to try to lock any existing NFT regardless of it being in his wallet or not. This leads to failed transactions (without appropriate error message) for the borrower. This happens regularly, when the subgraph is not quick enough to update the asset list, the borrower can't see the financing after locking the NFT, tries again and it fails because it was already removed from the wallet.

Currently the 'Lock NFT' button is activated once NFT registry and NFT ID are entered in the correct format. We should also add a check whether the NFT is actually held by the account that wants to finance it. If the NFT ID has the correct expected format but is not held by the account/address then we should show an error message (we have the input component that shows errors subline) `NFT not held in your wallet`.

**Comment by offerijns** [comment]
Integrate multicall and grab owner of NFT instead of using the subgraph.
