### ISSUE TITLE
Improvement - Add a way to return the NFT playground homepage from collection

### ISSUE THREAD

**Issue by tsx49** [centrifuge/apps#682]
**Background**
Now that the sidebar has been removed, we no longer have a way to navigate back to the NFT Playground homepage. Alessio suggested using the Altair logo ( Already implemented).  

**Back button**
We are going to add a back button, when selected it will return the user to the previous screen.
The back button will be added to the following pages:
- Mint NFT page
- NFT detail page

**Home button**
We are going to add a Home button, when selected will return the user to the NFT Playground homepage.
Home button to be added to the following pages:
- Collection page

**NFT Playground**
- 'NFT Playground' header will be selectable ( variant text button) on every page, and when selected it will take the user back to the NFT Playground homepage.

**Comment by techgirlonlinee** [comment]
Home button on collection page
https://www.figma.com/file/4P9h3fF0oDI5U72ghXovdk/Altair-NFT-Playground?node-id=972%3A8877

Back button
https://www.figma.com/file/4P9h3fF0oDI5U72ghXovdk/Altair-NFT-Playground?node-id=953%3A9569
https://www.figma.com/file/4P9h3fF0oDI5U72ghXovdk/Altair-NFT-Playground?node-id=138%3A2167
