### ISSUE TITLE
Improvement - Update wording on 'Remove listing' modal

### ISSUE THREAD

**Issue by tsx49** [centrifuge/apps#689]
**Background**
On the Remove listing modal we would like to change the wording that is displayed

**Changes required:**
Change text from 'Remove listing' to 'Are you sure about removing this listing?'

**Figma Mock up**
https://www.figma.com/file/4P9h3fF0oDI5U72ghXovdk/Altair-NFT-Playground?node-id=734%3A6012

**Comment by onnovisser** [comment]
Fixed by #721
