### ISSUE TITLE
Improvement - Remove '+ Mint NFT' button when no NFTs exist within a collection

### ISSUE THREAD

**Issue by tsx49** [centrifuge/apps#690]
**Background**
When a user is within a collection - which does not contain any NFTs, we would like to remove the mint NFT button that is displayed, and turn the text into the call to action. The text displayed is also to be updated.

![image](https://user-images.githubusercontent.com/95627013/157350416-e11c6b5f-49c2-4287-9bdc-dcdb3933380c.png)

**Changes required:**
1. Remove '+ Mint NFT' button
2. Text: change 'This collection does not contain any NFT.' to 'The collection does not contain any NFT. Click here to mint.' 
3. The text ' 'The collection does not contain any NFT. Click here to mint.' will become clickable, and will open the 'Mint NFT' page when clicked.

**Figma Mock up**
https://www.figma.com/file/4P9h3fF0oDI5U72ghXovdk/Altair-NFT-Playground?node-id=991%3A12028

**Comment by alessioscalici** [comment]
@tsx49 @armandomistral @techgirlonlinee the ticket and the provided design (and the comments on the provided design) contradict each other.

<img width="828" alt="Screenshot 2022-03-14 at 10 51 47" src="https://user-images.githubusercontent.com/8630331/158096829-138a5807-39bf-4e70-9f5e-49515bb7741f.png">

It's better to agree to a solution **before** opening a ticket. Taking no action on this one.
