### ISSUE TITLE
spare ticket

### ISSUE THREAD

**Issue by tsx49** [centrifuge/apps#693]
**Background**
Aim is to remove the component on the notification toasters, which leads to the transaction detail on Subscan, and replace it with a hyper link that says 'view on subscan'. The rationale is that it be more intuitive for users.  When a user clicks on 'view on subscan' they are directed to subscan, in a new tab, as per usual.

**Comment by armandomistral** [comment]
@tsx49, this change affects the [Toast notification component](https://www.figma.com/file/TPFzwr1VVtg7MZlRVwMKvS/Fabric-design-system?node-id=713%3A2976) in Fabric. I suggest we change the component as follows:
- Do not show a Subscan link until the transaction has completed
- Show Subscan link as confirmation of transaction success (or if failed, as a way to investigate further)
