### ISSUE TITLE
List of Assets - Public Pools -> Assets page MVPv1

### ISSUE THREAD

**Issue by EstherCentrifuge** [centrifuge/apps#704]
[Specs ](https://centrifuge.hackmd.io/MSB1Ll8IRfeXPmukXMeBtw#List-of-Assets)
### List of Assets
Lists all assets within this pool.
The list can be sorted by any column within the table
Each asset shows 
- Dimond shaped icon with asset order number
- Asset Name
    [- Set during asset creation](https://centrifuge.hackmd.io/2NJLoV7yRXSOC2YrrImXCg)
- Maturity
    - maturity date - origination date = Maturity
- Maturity date
    - [Set during asset creation](https://centrifuge.hackmd.io/2NJLoV7yRXSOC2YrrImXCg)
- Amount
     - Collateral value [Set during asset creation](https://centrifuge.hackmd.io/2NJLoV7yRXSOC2YrrImXCg)
- Status of the asset
[See Specs here](https://centrifuge.hackmd.io/sUnY0kNoQamfj9I_IFquoQ)

**Comment by sophialittlejohn** [comment]
@EstherCentrifuge should this list only display assets of type `CreditLineWithMaturity`?

**Comment by sophialittlejohn** [comment]
resolved: it should display all asset with all status', thanks @EstherCentrifuge

**Comment by EstherCentrifuge** [comment]
closed as there are updaets in a seperate ticket but the feature it self works
