### ISSUE TITLE
Liquidity summary -  -> public liquidity details - Altair

### ISSUE THREAD

**Issue by EstherCentrifuge** [centrifuge/apps#710]
[Figma](https://www.figma.com/file/d1bEBkwllUQe27nQM6VlJu/Centrifuge-app?node-id=4415%3A118419)

- Available liquidity (Current)
    - Show current available liquidity,[ see this doc for details](https://docs.centrifuge.io/learn/terms/#liquidity-available)
- Total invested (30d)
    - Total amount invested to this pool in the past 30 Days
- Total redeemed (30d)
    - Total amount tokens redeemed from this pool in the past 30 Days
- Pool repayments (30d)
    - Total amount of the sum of repayments made to this pool in the past 30 Days
- Upcoming repayments (30d)
    - total amount of payments due in the next 30d

**Comment by EstherCentrifuge** [comment]
This is depending on subgraph but data should be available

**Comment by sophialittlejohn** [comment]
Moved back to backlog since most of the values are not yet retrievable in subquery yet
