### ISSUE TITLE
Use proxies for asset originator access - Access tab

### ISSUE THREAD

**Issue by offerijns** [centrifuge/apps#718]
[Specs](https://centrifuge.hackmd.io/vyVkZaFwRfKs_8DsiQMiXA)
[Figma Design](https://www.figma.com/file/9iwvzHuvbjlHXRWlPWRxxc/Centrifuge-app---Version-2-(Branch)?node-id=7260%3A48633&t=VJedrF4Mnd3gVuC1-0)

## Background
This is part of a bigger initiative to standardize the operational security of Pools. Read more [here](https://centrifuge.hackmd.io/Zaru4qweSXiVIgKPROgLdg?both).

Proxies allow users to use an account (it can be in cold storage or a hot wallet) less frequently but actively participate in the network with the weight of the tokens in that account. Proxies can be viewed as a more powerful and flexible version of a controller account, i.e. proxies are allowed to perform a limited amount of actions related to specific substrate pallets on behalf of another account.

We want to use proxies for asset originators, to:

- Increase operational security
- Reduce the impact of lost keys
- Tie together borrowers with their "skin in the game" through junior tranche holdings
- future: Guarantee that funds cannot be sent to arbitrary accounts

### Asset originator proxy

* There can be multiple AOs. Each of these is an anonymous proxy with multiple proxied accounts on it.
    * derive the document collection ID from the account ID of the AO proxy
    * add a new property in the pool config like
```
assetOriginators: {
  [anonProxyAccountId]: {
    collectionId: "xxx"
  }
}
```
Must-have is that the UI can initiate actions from other accounts that they have proxy access on. If an anonymous proxy was created, called account Asset Originator Proxy, and account AOHotWallet1 has delegated access on this proxy to be able to invest from account Asset Originator Proxy, then it should be possible for AOHotWallet1 to use the Centrifuge App to invest using account Asset Originator Proxy.

The UI should initially:
- Create an anonymous proxy.
   - Call `api.tx.proxy.anonymous` with `proxy_type=Any`
- Assign the `Borrower` and `TrancheInvestor` for all tranches roles to this anonymous proxy.
- Send some funds to the AO proxy.
- Make it easy to add the AO proxy to the polkadot.js extension.
- add `Borrow` and `Invest` proxy types, which will restrict the calls that the accounts can make
- setup identities for these anonymous proxies to identify these accounts on chain (as these are the accounts that are creating loans, holding funds, investing in the junior tranche, etc.)

The UI should also allow adding more accounts and removing them to this proxy, by calling `api.tx.add_proxy` or `api.tx.remove_proxy`.
- `api.tx.proxy(ao_proxy_account, api.tx.add_proxy(new_account, proxy_type, 0))`
- `api.tx.proxy(ao_proxy_account, api.tx.remove_proxy(new_account, proxy_type, 0))`

The advantage of this is that when borrowing, the loan NFTs will be held by the proxy. This means that once multiple borrower accounts have been added, all of these can manage the loans. If the key to one of the accounts was lost, the access to the loan NFTs isn't lost.

It also ties together the borrowing and tranche investing transactions, which means that other investors can verify that the borrowers have skin in the game in the junior tranche.

```mermaid
classDiagram
    AssetOriginatorProxy <|-- AOHotWallet1
    AssetOriginatorProxy <|-- AOHotWallet2
    AssetOriginatorProxy <|-- AOProxyManager1
    class AOHotWallet1{
      Proxy type: Borrow,Invest,RestrictedTransfer
    }
    class AOHotWallet2{
      Proxy type: Borrow,Invest,RestrictedTransfer
    }
    class AOProxyManager1{
     Proxy  type: Any
     Multisig 3/4
    }
```
The setup for the asset originator proxy could then look something like this:

`AOHotWallet1` and `AOHotWallet2` can both invest in tranches, borrow and send funds to the off-ramp. An identity can be added to the `AssetOriginatorProxy`, identifying who this is associated with in the real world.

### Future improvements
In the future, this set up can be used to provide additional protections. The steps would be:
1. We will create a `RestrictedTransfers` proxy type. This can be used to restrict which addresses funds can be sent to, e.g. borrowed funds can only be sent to the off-ramp account. `RestrictedTransfers` proxy type doesn’t exist on chain yet. Will be built in the next few months.

### UI
For this to be used effectively we are building a UI which can be accessed by `PoolAdmins`

![](https://storage.googleapis.com/centrifuge-hackmd/upload_2e33c94a98f4085ac7f3ecd9402e42d4.png)

**Comment by EstherCentrifuge** [comment]
Why is this re-opened? and if it needs to be open can you please add a description and add it to the correct epic @offerijns @denniswell 

do we need it for first pool? -.>V1
do we need it before migration? -> v2
If no -> filler

**Comment by offerijns** [comment]
I'm not sure what you mean by "please add a description", there's plenty of content in there already? This has partially been implemented, namely the ability to submit proxy transactions, but the next step is actually creating an anonymous proxy and being able to configure this in the UI. I'd consider this a V2 feature.

**Comment by EstherCentrifuge** [comment]
sorry it was empty when i loaded the ticket, i see it now added it to V2 thanks

**Comment by onnovisser** [comment]
Also update the `View pool account` button with the AO proxy address

**Comment by annamehr** [comment]
Updated specs can be found [here](https://centrifuge.hackmd.io/Zaru4qweSXiVIgKPROgLdg?both).
