### ISSUE TITLE
Token list / overview page - MVPv1

### ISSUE THREAD

**Issue by EstherCentrifuge** [centrifuge/apps#732]
[Specs](https://centrifuge.hackmd.io/m4QFRZzoQs-h7P7qcMzC_w)
[Figma frame - Token overview/list](https://www.figma.com/file/LCbVWH8fXPkXMbLpC3VZtx/Centrifuge-app---Altair?node-id=3692%3A83628)

- A user can view tokens
- A user does not have the be an investor, it can be a guest user.

When a token is selected the user redirects to the token details page
The list can be sorted by values (most to least and visa versa, for **Yield**, **Protection** and **Capacity**)

- Show list of live tokens
    - Displaying their **Token Name and Icon**
        - Selected during tranche creation; [Specs](https://centrifuge.hackmd.io/1OiMlCCWTL2YwUN8c_sFnA#Tranches)
    - **Asset class**
        - Selected during pool creation; [Specs](https://centrifuge.hackmd.io/1OiMlCCWTL2YwUN8c_sFnA#Pool-details)
    - Values for each token
        - **Yield**
            - 30D for Senior; [calculation](https://docs.centrifuge.io/learn/terms/#30d-drop-yield)
            - 90D for Junior; [Calculation](https://docs.centrifuge.io/learn/terms/#90d-tin-yield)
            
        - **Protection**
            - Display the actual protection
                - [See this document on risk and protectionlevel details and calculations](https://docs.centrifuge.io/learn/terms/#tin-risk-buffer)
        - **Capacity**
            - How much Capacity is available for investment.
                -  Spec; [How investment capacity is calcualted](https://centrifuge.hackmd.io/B-i5X31FSdSOglkh1J-vVg?view#How-investment-capacity-is-calculated)

**Comment by sophialittlejohn** [comment]
Hey @EstherCentrifuge I have a few questions regarding the calculations on the overview page:

1. I'm struggling to understand the capacity calculations for the overview page. I'm not sure how to handle the different tranches and how to apply the formula to multiple tranches (instead of just 2). I also heard that that column may be removed. Can you please confirm (or deny 😅)?
2. For yield calculations, just want to check that I chose the right formula. Since I don't have the current token prices I was told that dividing `interestPerSec` by `secondsPerYear` would do the same (and a few extra steps, see here: [feeToApr](https://github.com/centrifuge/apps/blob/c9b4d88df72b9380053416e6c22fa7609087eebd/centrifuge-js/src/utils/index.ts#L38))

**Comment by EstherCentrifuge** [comment]
1. A token is a Tranche, so the capacity per tranche is what i am looking for. does that help? I'm not sure about the question sorry. 
2. I'm pretty sure we need history for it. so I am not too sure maybe @onnovisser knows. 
3. The thumbnails, sorry it wasn't clear before:
a.  For the NFT and the Pool we should always show the uploaded image as the thumbnail (in the future we won't have an image on the NFT, we'll just have a square stating NFT). the pool image should be mandatory i'll update the specs for @onnovisser to ensure that. 
b. Assets have an "order number" meaning the first asset connect to the pool is #1, the 2nd is #2 etc. when we list the assets the thumbnail is a dimond shape with the order number of that asset in it.
c. Tokens will have a cirlce tumbnail and for now NOT have a custom image upload. we'll display the token symbols (max 6 characters) inside the circle.

please see the design here: https://www.figma.com/file/d1bEBkwllUQe27nQM6VlJu/Centrifuge-app?node-id=2091%3A45246

**Comment by EstherCentrifuge** [comment]
Hi, sorry for the Confusion.
small changes:
Header with 2 values
1. Total Vue Locked (TVL) = sum of all value locked from all tokens 

2. Number of tokens in the list (example = 5)

Also the columns changed there is no longer a column for "Capacity" this is now replaces with Value locked

**Comment by EstherCentrifuge** [comment]
hi @sophialittlejohn I need some changes as their both my mistake

1. Can we list the pool name  + token name in the list not just the pool name so it will always be 
Awesome Pool Senior tranche 
Awesome Pool junior tranche 
peed in  Pool Senior tranche 
peed in  Pool junior tranche 

2. Protection = minimum protection. not actualy protection. 
I think ti's the value on chain " Min risk buffer"

**Comment by EstherCentrifuge** [comment]
Moving it back to NOW so i can see when it moves back to QA

**Comment by armandomistral** [comment]
@sophialittlejohn, here's my UI findings from testing https://pr-793--dev-nft-studio.netlify.app/tokens:

#### Issue: Connect button component
<img width="150" alt="image" src="https://user-images.githubusercontent.com/23652850/166648779-14fd6d5b-0224-4498-a619-ba171c5b89c1.png">

- **Is**: The Connect button uses the primary style 
- **Target**: Create** and use a dedicated component for the Connect button: `button-wallet`. See [spec](https://www.figma.com/file/TPFzwr1VVtg7MZlRVwMKvS/Fabric-design-system?node-id=2426%3A19940)

#### Issue: Label component
<img width="193" alt="image" src="https://user-images.githubusercontent.com/23652850/166648942-0394bc7c-b916-43c0-849b-012c933fb5b0.png">

- **Is**: The summary label-value pair does not use a component, and the styling is not correct (OMG label is even using Arial)
- **Target**: Create and use a label-value pair component with two variants: _default_ and _summary_, and use the summary variant for summary sections, incl. applying color `backgroundSecondary`. See [spec](https://www.figma.com/file/d1bEBkwllUQe27nQM6VlJu/Centrifuge-app?node-id=5912%3A124942)

#### Feature request: Layout maximum width
<img width="2558" alt="image" src="https://user-images.githubusercontent.com/23652850/166678572-0fb84e8f-0c97-4c70-954b-68aa0c6b4d27.png">

- **Is**: The layout does not use a maximum width, which makes the content "fall apart" somehow
- **Target**: Designers to define a maximum width for the 3-column layout, and layout-behavior (breakpoints) for different screen sizes
(Note to @EstherCentrifuge: let's discuss when to add this, I think this could go in Version 1)

**Comment by sophialittlejohn** [comment]
@EstherCentrifuge 

> 1. Can we list the pool name + token name in the list not just the pool name so it will always be
Yep we're actually already doing that, but we have some pool without names on the dev chain. The UI form should enforce  a pool name but I don't think the polkadot interface does

> 2. Protection = minimum protection. not actualy protection.
Thanks! Will be fixed in an upcoming PR

**Comment by armandomistral** [comment]
@sophialittlejohn, I've created a ticket for the buttons here: https://app.zenhub.com/workspaces/centrifuge-applications-5fa29e924059e5001625e2a3/issues/centrifuge/apps/807. It's assigned to @EstherCentrifuge, so you can acknowledge/plan/prioritize, etc. Let me know if you have questions...

**Comment by EstherCentrifuge** [comment]
it makes sense (sorry was checking this to close) but I suppose I can't see an example of how it would look?

**Comment by sophialittlejohn** [comment]
the 30d/90d yield is not yet implemented. As far as I know, we're still waiting on subquery for it
