### ISSUE TITLE
pool summary within tokens - Altair

### ISSUE THREAD

**Issue by EstherCentrifuge** [centrifuge/apps#736]
[Specs](https://centrifuge.hackmd.io/m4QFRZzoQs-h7P7qcMzC_w#pool-summary-within-tokens)
[Figma](https://www.figma.com/file/LCbVWH8fXPkXMbLpC3VZtx/Centrifuge-app---Altair?node-id=4440%3A100305)

- Image and Name of the pool to identify the pool
- Value locked shows the current pool value 
- Age (*this is based on the creation date of the pool*)
- Average asset maturity
    - Average maturity is the average maturity of all outstanding assets weighted by the outstanding amount. (so not remaining maturity, from financing date till expected repayment date)
    ```
    Asset 1: 90d, 100DAI outstanding
    Asset2: 180d, 400DAI outstanding
    Average maturity = (90d * 100 + 190d * 400) / (100 + 400) = 170d

**Comment by EstherCentrifuge** [comment]
This item was still in the "specing" status please make sure this is also "done" :)

**Comment by armandomistral** [comment]
@sophialittlejohn, here's the findings from testing https://dev.app.centrifuge.io/:

### Issue: Embedded card component

#### Is
Embedded card is missing the interactive drop-shadow, and the chevron. The summary section does not stretch to the entire width.
<img width="716" alt="image" src="https://user-images.githubusercontent.com/23652850/166704485-a4132af8-8023-45d7-8a40-f7b28a57d6ef.png">

#### Target
- Please apply definitions of embedded card component: [spec](https://www.figma.com/file/d1bEBkwllUQe27nQM6VlJu/Centrifuge-app?node-id=5988%3A125442)
- Add `shadowInteractive` to card
- Add chevron to card header

![image](https://user-images.githubusercontent.com/23652850/166898045-b4a1b946-41e9-455a-93eb-78d7f398a967.png)

##### Issuer section
- Apply full width to summary section
- Use small configuration of link component for issuer links [spec]
(https://www.figma.com/file/TPFzwr1VVtg7MZlRVwMKvS/Fabric-design-system?node-id=913%3A2469)
- Modify into 2-column layout to better host short descriptions [spec](https://www.figma.com/file/d1bEBkwllUQe27nQM6VlJu/Centrifuge-app?node-id=4375%3A109583) _Apologies for the change_
