### ISSUE TITLE
Tooltips Altair

### ISSUE THREAD

**Issue by EstherCentrifuge** [centrifuge/apps#780]
Please see Column D for the tooltip texts for all Altair tooltips

https://docs.google.com/spreadsheets/d/1wuAE_94QZ-9L7Q7uwFsTBtnmoiUnRbDm89icsW9YYdM/edit#gid=0

**Comment by armandomistral** [comment]
@sophialittlejohn, there's a change in the tooltip `Average asset maturity`. The word `expected` is to be removed. The target text is: `This indicates the range of maturities of the pool's underlying assets, i.e. the time period after which the financing of this assets matures and will be paid back.`
