### ISSUE TITLE
Asset portfolio - Pool overview - Altair

### ISSUE THREAD

**Issue by EstherCentrifuge** [centrifuge/apps#783]
[Specs](https://centrifuge.hackmd.io/K2KYOmgASMqW---8helRWA#Asset-Portfolio) 
[Figma](https://www.figma.com/file/LCbVWH8fXPkXMbLpC3VZtx/Centrifuge-app---Altair?node-id=3964%3A95833)

Pie chart showing the assets within the pool by risk Group.
Table:
- Risk group name 
    - set at group creation
- amount 
    -  the total of current assets financed/total debt/ amount outstanding per risk group.
- Share in % 
    - How much % of the NAV
- Financing fee 
    - set at group creation
- Risk Adjustment
    - set at group creation `PD * LGD`

**Comment by EstherCentrifuge** [comment]
Why is there no pie chart? L:(

**Comment by armandomistral** [comment]
@sophialittlejohn, I tested the risk group table on https://dev.app.altair.cntrfg.com/, and I suggest a change to the case when no risk group name is set: 
### Is
* The risk group name is optional when defining the risk groups in the pool creation form, and the risk groups are numbered. In the **Asset portfolio table**, however, no number is shown.
* The color legends are shown in the table even if no pie chart is displayed

![image.png](https://images.zenhubusercontent.com/6090f1ca0d0c23544195c7ec/305d77fd-81a2-4a43-bd5f-fd5db11fe9b2)

###Target 
* Show the pie chart in empty state, e.g. with label `Asset amount is 0`. Alternatively, hide the color legends in the table in case the pie is not shown in empty state
* Show the risk group number in case no risk group name is set.

**Comment by sophialittlejohn** [comment]
@armandomistral happy to add the numbers when no name is provided. I can't think of how an empty piechart would look. What were you thinking? Removing the color label on empty state would definitely be an option. Please let me know what you decide.

**Comment by armandomistral** [comment]
@sophialittlejohn, I was thinking of showing an empty pie with a label, e.g. `Amount empty`. Like so: 
![image](https://user-images.githubusercontent.com/23652850/174551620-54daaab0-7851-4d85-b847-40afc92794ea.png)
But this is not informative. I think we can simplify the target defined above (therefore rendering it obsolete):
- If the locked amount is 0, no pie chart is shown, and no color label is shown
- The risk group number is always shown; if set, the group name is appended in quote. E.g. `4 "High risk"`
![image](https://user-images.githubusercontent.com/23652850/174552530-caa26183-406d-4896-b3db-61863b121494.png)
WDYT?

**Comment by armandomistral** [comment]
…When is the`Amount` field filled? This pool shows a 0 amount, but there are two assets with a collateral value of 5 kUSD each. Can you check [Balance pool](https://dev.app.altair.cntrfg.com/issuer/1156368133)?

**Comment by sophialittlejohn** [comment]
> If the locked amount is 0, no pie chart is shown, and no color label is shown
The risk group number is always shown; if set, the group name is appended in quote. E.g. 4 "High risk"

⬆️  perfect, lets do it!

> …When is theAmount field filled? This pool shows a 0 amount, but there are two assets with a collateral value of 5 kUSD each. Can you check [Balance pool](https://dev.app.altair.cntrfg.com/issuer/1156368133)?

the problem here is that neither of the assets in Balance pool are ongoing. The amount shows the value of the nft. The pie chart shows how much has actually been financed. If you'd like to see the pie chart then you need to finance one of your assets (and don't repay it)
