### ISSUE TITLE
Create assets (From existing NFT)  and price the asset - Altair

### ISSUE THREAD

**Issue by EstherCentrifuge** [centrifuge/apps#804]
[Specs](https://centrifuge.hackmd.io/LvPUF72_SlSt-pqMJN5rzA?both)
[Figma Borrower view](https://www.figma.com/file/LCbVWH8fXPkXMbLpC3VZtx/Centrifuge-app---Altair?node-id=3446%3A86211)
[Figma price asset](https://www.figma.com/file/LCbVWH8fXPkXMbLpC3VZtx/Centrifuge-app---Altair?node-id=3486%3A150690) 

# Background
A user may create a create an asset if he/she has the borrower rights.
Note that on Altair the Assets are pre-existing NFT's purchased from or minted on the NFT playground

# Flow structure
This spec will describe a flow which is not only on one page
![](https://storage.googleapis.com/centrifuge-hackmd/upload_ee1f2d7df0235953731a377be2eea90b.jpeg)

## Flow description
1. Any user can view NFT details
2. A user who owns the NFT and has the borrower rights can perform the action "Create asset"
    - User selects a pool in which this asset will be created.
        - Only pools the user has borrower rights in are shown.
    - User signs for asset creation
3. After creation the asset is visible in the asset list of the pool
    - The original owner can not yet finance the asset. The asset needs to be priced first
    - The "pricing admin" can see the asset in the pool in status `Created` as has the option to price the asset
4. The pricing admin adds a price to the asset
    - A choosen collateral value in kUSD
    - A risk group from within the pool needs to be selected
    - The pricing admin needs to sign to confirm pricing.
5. Once priced the asset details are updated with the pricing details and visable for any user and status is updated to `Ongoing`
6. The original owner now has to option to (partially) finance the NFT.
    - The maximum amount to finance is the set collateral value.
    - To finance the NFT the borrower needs to sign
7. Once the NFT is financed the user can make repayments
    - Selecting an amount
    - sign to confirm
9. When the financed amount is fully repaid status updates to `Repaid`
    -  depends on the loan type we allow a new financing
        -    Bullet loan = Once repaid, you are done, no more borrowing.
        -    Credit line loan types = Yes, as long as the expected repayment/date is still in the future
        -    Interest bearing loans = Once repaid, you are done

## Statuses on Assets
[See full details here in assets statuses page](https://centrifuge.hackmd.io/@Dxpi1Nh-QfKSPMGa0tQRJQ/rJ7uEnRNc?type=view)

**Created**
A user created an asset from one of his/her owned NFT. Assigned to a pool he/she has the borrower rights in. 
- Any user can now see it in the asset list
- A pricing admin can now set a collateral value and risk group for it.

**Ready**
The pricing admin has set the collateral value and the borrower/owner can now finance the asset if he/she wishes to do so. 

**Ongoing**
The borrower financed the asset for any amount up to the maximum set collateral value.
The borrow now has the option to "repay" Or repay fully
If the borrower has only partily financed the asset they can finance more within this step. 

**Repaid**
sed, like been fully repaid with a bullet or interest bearing loan
The borrower can close the asset once it's fully replaid (either via the fully repay and close action or manual close after repaid fully)
The NFT will be returned to the borrowers wallet (unlocked from the pool)

## Loan types dependency for re-financing 
 depends on the loan type we allow a new financing
 - **Bullet loan** = Once repaid, you are done, no more borrowing.
 - **Credit line loan** types = Yes, as long as the expected repayment/date is still in the future
     - Without maturity
     - With  maturity -> **All NFT's are on this loantype**
 - **Interest bearing** loans = Once repaid, you are done, no more borrowing.

**Comment by armandomistral** [comment]
@onnovisser & @EstherCentrifuge, what's the intention of the "=" operator before the discount rate? 

![image.png](https://images.zenhubusercontent.com/6090f1ca0d0c23544195c7ec/e9fa4957-4839-4600-82b1-3b8277f6d390)

I don't think the formula is clear just because of this character, and I'm not sure where to find the spec for it. It's not in the [mockup](https://www.figma.com/file/LCbVWH8fXPkXMbLpC3VZtx/Centrifuge-app---Altair?node-id=3486%3A150690).

If we are to show the discount rate as the result of the risk group calculation, I think we should show all operators of the formula.

What do you think?
