### ISSUE TITLE
Fabric buttons: Updates to primary button, color styles, wallet button

### ISSUE THREAD

**Issue by armandomistral** [centrifuge/apps#807]
## Background
The button types were reworked so that there is only one primary button, the solid button with the yellow background. Because of this change, the color styles got adjusted so that the blue primary accent color is not used for the primary and secondary button any more. In addition, the a specific implementation of the secondary button got created for the so-called "wallet button".

### Acceptance criteria
- There is only one primary button implementation, and the background is yellow
- The color styles are adjusted according to the spec
- A wallet button exists
- The button component is updated in Fabric
- The component is released to storybook (https://centrifuge-fabric.netlify.app/?path=/story/components-button--button&args=variant:contained)

### Specification
- button spec: https://www.figma.com/file/TPFzwr1VVtg7MZlRVwMKvS/Fabric-design-system?node-id=8%3A24
- wallet button spec: https://www.figma.com/file/TPFzwr1VVtg7MZlRVwMKvS/Fabric-design-system?node-id=2426%3A19940
- target preview (types & states): https://www.figma.com/file/TPFzwr1VVtg7MZlRVwMKvS/Fabric-design-system?node-id=2213%3A10493

https://app.zenhub.com/workspaces/centrifuge-applications-5fa29e924059e5001625e2a3/issues/centrifuge/apps/470

**Comment by EstherCentrifuge** [comment]
@sophialittlejohn I'll assign it to you, you stated you rather do all buttons on the end once it's finalized which is fine for me. also this gives Nico and Araya a moment to make updates if they have any. this ticket can be done in the end with the tooltip ticket. 
Thank :)

**Comment by EstherCentrifuge** [comment]
Maybe i wasn't clear, but please check ALL bottons, also on what ever pages or features Onno made ok?
Any question about the design please check with Nico :)

**Comment by armandomistral** [comment]
@onnovisser, is this ready to be reviewed? There's no preview link here... Where am I supposed to check?

**Comment by onnovisser** [comment]
@armandomistral Yes, it can be viewed on https://dev.app.cntrfg.com/ and in the deployed Storybook
https://centrifuge-fabric.netlify.app/?path=/story/components-button--wallet-button

**Comment by armandomistral** [comment]
Thanks @onnovisser! I checked https://centrifuge-fabric.netlify.app/?path=/story/components-button--button. Here's my findings:
- Theme altairDark: ✅
- Theme altairLight: ⚠️ (the blue colors of tertiary buttons should be replaced by the yellow of the Altair accent color scale; see https://www.figma.com/file/Xbfgir0ZyOjgteEftT8sxY/?node-id=3781%3A672)
- Theme centrifugeDark: ⚠️ (the yellow colors of tertiary buttons should be replaced by the blue of the Centrifuge accent color scale; see https://www.figma.com/file/TPFzwr1VVtg7MZlRVwMKvS/Fabric-design-system?node-id=2712%3A13192)
- Theme centrifugeLight: ✅

... will move this to ready anyhow since altairDark and centrifugeLight are both ok, and what we'll start with
