### ISSUE TITLE
Bug - Link to creator's address opens the Owner's address for sold NFT's

### ISSUE THREAD

**Issue by tsx49** [centrifuge/apps#813]
**Scenario executed**
Given user is on the NFT detail page
And viewing an NFT that has been sold or transferred
When the user has selects the 'by' link
Then it should a new tab should be opened in Subscan
And it should display the NFT creator's wallet address

**Questions**
n/a

**Steps to reproduce the bug**

1. Navigate to https://app.altair.network/
2. Create a collection
3. Mint an NFT
5. Transfer the NFT to another wallet ( via transfer or by selling NFT)
6. Navigate to NFT detail page
7. Click 'by' address link

**Expected result**
 Subscan.io will display the wallet address of the NFT creator

**Actual result**
Subscan.io  opens and displays the current NFT owner's wallet address

**Comment by onnovisser** [comment]
Fixed in Pools UI

**Comment by armandomistral** [comment]
Hi @onnovisser, I've tested the steps above on https://dev.app.cntrfg.com/. Here's the test protocol (used `Alice` address)
1. Create a collection ✅
2. Mint an NFT ✅
3. Transfer the NFT via transfer ✅  / sell NFT ✅
4. Click 'by' address link:  **Works for me** (The click copies the creator's address to the clipboard, but does not open subscan.io)
![image](https://user-images.githubusercontent.com/23652850/179169225-e9593480-5e07-4d78-825b-2214c80e422b.png)
