### ISSUE TITLE
Bug - Addresses are displayed in Kusama format

### ISSUE THREAD

**Issue by tsx49** [centrifuge/apps#814]
**Scenario executed**

Given user is on the on the NFT Playground site
When a user navigates to an NFT Playground homepage,  Collection page or NFT detail page
Then addresses should be displayed in Altair format

**Questions**
n/a

**Steps to reproduce the bug**

1. Navigate to https://app.altair.network/
2. Navigate to any page where an address is displayed (NFT Playground homepage,  Collection page or NFT detail page)
3. View the wallet address

**Expected result**
 Wallet addresses should be displayed in Altair format (KA.....)

**Actual result**
Wallet addressees are displayed in Kusama format
<img width="1511" alt="Screenshot 2022-05-18 at 12 46 56" src="https://user-images.githubusercontent.com/95627013/169138013-99cf2de1-c4f4-4c95-86ca-7e8dda2274bf.png">

**Comment by EstherCentrifuge** [comment]
note from Onno: Kusama addresses usually start with an 5 H or F I think. the Old Cent Chain ones started with a 4. Not sure what the dev runtime addresses start with, it looks like they all start with a 4 too

**Comment by onnovisser** [comment]
@tsx49 The UI now uses the chain ID of the chain that it's talking to. For the deployed dev environment, this ID is different that the Altair one. When I manually change it to the Altair ID, the Addresses are formatted as "kA...". So once it's live on Altair, the addresses should display correctly
