### ISSUE TITLE
Testing UX fixes: pool detail issues

### ISSUE THREAD

**Issue by armandomistral** [centrifuge/apps#831]
### Pool detail: Parent link missing in header
- **Is**: On the pool detail, the parent link `Pools` is shown on the *Overview* tab, but not on the other tabs
![](https://storage.googleapis.com/centrifuge-hackmd/upload_903ad9da05eec7e346ecd27d4eee9874.png)
![](https://storage.googleapis.com/centrifuge-hackmd/upload_f9c0f831b98a52737f878d0d69966d39.png)

- **Target**: The pool header needs to be identical across all tabs of a detail view. Show the parent link on all tabs

### Pool detail: Progress indication 
![](https://storage.googleapis.com/centrifuge-hackmd/upload_f6f3b74d97b23099f94a406357bd6936.png)
- **Is**: Upon clicking `Done`, the system shows activity feedback. But there is no label shown, and since the process takes many seconds, there is no explanation of what's going on.
- **Target**: Add label to spinner animation, e.g. `Processing transaction...`

### Pool detail: Remove search input
![](https://storage.googleapis.com/centrifuge-hackmd/upload_ee9737bc40e63f12c794d12b7e95c664.png)
- **Is**: The investor search field uses the browser native icon to remove the entered input
- **Target**: use the custom remove icon from Fabric library (https://www.figma.com/file/TPFzwr1VVtg7MZlRVwMKvS/Fabric-design-system?node-id=2082%3A7981)

**Comment by armandomistral** [comment]
@sophialittlejohn, is this ready to be reviewed? There's no preview link here... Where can I check?

**Comment by sophialittlejohn** [comment]
Hi @armandomistral as this is an issue and not a pull request there is no dedicated preview link. But you can use our dev and demo environments for testing:
https://demo.app.cntrfg.com/ (https://demo.app.altair.cntrfg.com/)
https://dev.app.cntrfg.com/ (https://dev.app.altair.cntrfg.com/)

**Comment by armandomistral** [comment]
@sophialittlejohn, here's my findings of testing https://demo.app.cntrfg.com/:

## Pool detail: Parent link missing in header
The parent link is set, but it's pointing to the wrong location:
-  Is: The label is called `Investments` and points to the `Tokens` menu
  - Target: The label should be called `Pools` and point to the `Pools` menu
(Note 1: Investments will only be used for version 1, when the token and pool menu are combined)
(Note 2: the parent link on the token detail also needs fixing: It leads to the pool, but should point to the `Tokens` menu instead). So the basic rule of the parent link on any given detail view header should be that it leads to parent in the navigation hierarchy.

## Remove search input
The custom remove input icon is shown, but in focus and hover state the native remove icon shown as well, resulting in a redundancy? Can the native remove icon be suppressed? If not, let's just fall back to the browser native icon.
<img width="461" alt="image" src="https://user-images.githubusercontent.com/23652850/171994278-d9bb1b1d-595e-42fb-b37b-3837f12cd35e.png">

**Comment by armandomistral** [comment]
What's the purpose of the "=" character between Expected loss and Discount rate?
![image.png](https://images.zenhubusercontent.com/6090f1ca0d0c23544195c7ec/b60f2f56-ddc2-4d39-b536-d4e957000abc)

**Comment by armandomistral** [comment]
@sophialittlejohn, the back link in the pool detail header is not correct:
- The label says `Investments`, but it should say `Pools`
- The link leads to `Tokens`, but it should lead to `Pools`

Similarly, the backlinks on the token detail are wrong:
- The labels says the pool name, but it should say `Tokens`
- The link leads to the pool, but it should lead to `Tokens`

Can you please fix those?

**Comment by armandomistral** [comment]
Thanks for fixing, @sophialittlejohn! Looks good to me on https://dev.app.cntrfg.com/investments..,.
