### ISSUE TITLE
UX testing: Asset detail issues

### ISSUE THREAD

**Issue by armandomistral** [centrifuge/apps#832]
### Asset detail: Label style
![](https://storage.googleapis.com/centrifuge-hackmd/upload_c9b01aff53d335d4dfcc968accd86cc8.png)
![](https://storage.googleapis.com/centrifuge-hackmd/upload_67d18dd4523c2e92c0ca8c0d03e85a38.png)
![](https://storage.googleapis.com/centrifuge-hackmd/upload_581a97d9a130422ec837ee52f851308a.png)
- **Is**:
    - The font-style of labels is Arial (`Asset class`. `Average asset maturity`) if it is underlined
    - Inconsistent writing: Some labels are title case (Asset Class), other sentence case (Value locked)
- **Target**: 
    - Use Inter font for all text (no Arial, pls)
    - Apply sentence case to labels and headings
    - Apply Fabric specs:
        - [Label component](https://www.figma.com/file/TPFzwr1VVtg7MZlRVwMKvS/Fabric-design-system?node-id=3071%3A11071)
        - [Label hierarchy](https://www.figma.com/file/d1bEBkwllUQe27nQM6VlJu/Centrifuge-app---Version-1?node-id=6640%3A119910)

### Asset detail: Status chip
![](https://storage.googleapis.com/centrifuge-hackmd/upload_f0b63870fc2b5dc01f9647ad5ec2fc39.png)
- **Is**: The status chip is set in 14px font size, which is too big
- **Target**: Use 12px font size for status chips - see [component spec](https://www.figma.com/file/TPFzwr1VVtg7MZlRVwMKvS/Fabric-design-system?node-id=173%3A4094)

### Price asset
![](https://storage.googleapis.com/centrifuge-hackmd/upload_b40790f3883cdc674ffc5bbcf56ff3f3.png)
- **Is**: The risk group detail properties depend on the chosen risk group, but there is no heading to the properties indicating the cascade
- Mandatory fields are not marked
- **Target**:
  - Add a heading on top of the risk group properties to explain and bundle them together
  - Mark mandatory fields with "*" character
 - Provide error feedback upon submitting erroneous or incomplete form
 - [Mockup](https://www.figma.com/file/LCbVWH8fXPkXMbLpC3VZtx/Centrifuge-app---Altair?node-id=3486%3A150690)

### Asset detail: NFT card
![](https://storage.googleapis.com/centrifuge-hackmd/upload_fb4a338bbd18d26bbd07394c5d13316c.png)
- **Is**: The label component is using the NFT playground style
- **Target**:
  - Apply [spec](https://www.figma.com/file/d1bEBkwllUQe27nQM6VlJu/Centrifuge-app---Version-1-(Master)?node-id=6248%3A106124) to card
   - Criteria:
      - Use hexagon shape for NFT thumbnail (see https://www.figma.com/file/TPFzwr1VVtg7MZlRVwMKvS/Fabric-design-system?node-id=2722%3A13101)
      - Use Fabric style of label and value (see [label-value pair example](https://www.figma.com/file/TPFzwr1VVtg7MZlRVwMKvS/Fabric-design-system?node-id=3071%3A11071))
      - Remove redundant `Owner` property from body
      - Apply [spec](https://www.figma.com/file/d1bEBkwllUQe27nQM6VlJu/Centrifuge-app---Version-1-(Master)?node-id=7069%3A121547) to image "lightbox" masque sqare (add border apply right `backgroundSecondary` background color

**Comment by EstherCentrifuge** [comment]
I'll make a seperate ticket for the more "logic" changes @sophialittlejohn

**Comment by EstherCentrifuge** [comment]
Few extra changes @sophialittlejohn 

1. Please remove the 2nd "owner" on the asset details page we keep the one on top -> Remove on the right
![image](https://user-images.githubusercontent.com/98879480/170256871-be4d8573-d960-4c50-b571-04ee20a6bafd.png)

2.Please add the address of the user who created the asset on top of the page.

Example in V1: [Figma](https://www.figma.com/file/d1bEBkwllUQe27nQM6VlJu/Centrifuge-app---Version-1-(Master)?node-id=6689%3A123274)

![image](https://user-images.githubusercontent.com/98879480/170256706-2c25d15c-ae2f-408f-a26a-85a5eb082e73.png)

**Comment by armandomistral** [comment]
@ I tested the ticket items on https://dev.app.cntrfg.com/:
* **Asset detail: Label style**: OK ✅
* **Asset detail: Status chip**: OK ✅
* **Asset detail: NFT card**: OK ✅
* **Asset detail: Price**: Not tested (Creating a new pool failed) ![image.png](https://images.zenhubusercontent.com/6090f1ca0d0c23544195c7ec/c1414eb6-23d7-43f5-8f30-6c953c2bcd1c)

**Comment by armandomistral** [comment]
@sophialittlejohn, there is a glitch in the navigation when navigating from the asset list to the asset detail:
* The asset list shows the issuer pool as selected menu item
![image.png](https://images.zenhubusercontent.com/6090f1ca0d0c23544195c7ec/d19b76cc-c49a-4473-a6cf-04fadf98d9fd)
* When opening the asset detail, the `Pools` menu is selected
![image.png](https://images.zenhubusercontent.com/6090f1ca0d0c23544195c7ec/a1490eec-eba3-46d2-9815-50ec5667000f)
I think an Issuer user should stay in the same pool when navigating the pool. So navigating from the asset list to the asset detail should select the same pool in the menu sidebar.

**Comment by EstherCentrifuge** [comment]
@armandomistral why is this assigned to me? its' in review if you're happy with the new results please close :) thanks

**Comment by armandomistral** [comment]
@sophialittlejohn, tested on https://dev.app.altair.cntrfg.com/:
- Asset detail: Label style: OK ✅
- Asset detail: Status chip: OK ✅
- Asset detail: NFT card: OK ✅
