### ISSUE TITLE
UX testing issues: NFT tab

### ISSUE THREAD

**Issue by armandomistral** [centrifuge/apps#833]
### NFT collection: Main content padding

![](https://storage.googleapis.com/centrifuge-hackmd/upload_6257fedf1e56b642b80ec6a54ec0549c.png)
- **Is**: The collections are missing a left and right padding
- **Target**: Apply main content's left and right padding to collection card group

### NFT collection: NFT playground layout legacy mismatch
![](https://storage.googleapis.com/centrifuge-hackmd/upload_3c17d027bf07099f6c9a5fb9b86a2306.png)
- **Is**:
    - The NFT cards are missing a left and right padding
    - NFT tab is not selected
    - The header does not have a backlink
    - The information `collection name` and `owner` is redundant (shown both in header and centered in content)
- **Target**:
    - Apply main content's left and right padding to NFT card group
    - Mark NFT tab as selected
    - Add link back to NFTs
    - Remove redundant information, move the collection image in the header

## NFT detail: NFT playground layout legacy mismatch
![](https://storage.googleapis.com/centrifuge-hackmd/upload_a82df1fa5919d582e44db722a09b9006.png)
- **Is**:
    - The information `NFT name` and `owner` are redundant
    - The back to parent is missing in the header
    - The content area is missing a left and right padding
- **Target**:
    - Remove redundant information, move the back link to the collection into the header
    - Apply main content paddings

**Comment by armandomistral** [comment]
@techgirlonlinee, please add the specs to the NFT collection target to this ticket...

**Comment by EstherCentrifuge** [comment]
we prioritized other items and did small "fixes" we'll go live with the as is design. any updates can be made in Cent chain V1.
