### ISSUE TITLE
Support of proxy addresses to wallet [Must have]

### ISSUE THREAD

**Issue by armandomistral** [centrifuge/apps#834]
## Background 
_to be defined_

## Acceptance criteria
> For V1, we don’t necessarily need to be able to create anonymous proxies within the UI. The only thing that’s an absolute must-have is that the UI can initiate actions from other accounts that they have proxy access on. Meaning, if an anonymous proxy was created, called account A, and account B has delegated access on this proxy to be able to invest from account A, then it should be possible for B to use the Centrifuge App to invest using account A.

## Solution idea
> The way I think this would work, is that in the wallet component, besides listing the connected accounts, we also list the proxied accounts. These would somehow need to be visually separated from the “normal” accounts. The user can then select one of these proxied accounts, and then any transactions submitted through the UI going forward will be submitted through the proxied account.

### Design spec
[Figma](https://www.figma.com/file/d1bEBkwllUQe27nQM6VlJu/Centrifuge-app---Version-1-(Master)?node-id=6864%3A114348)

* System shows connected address in wallet button
* ~~Proxy addresses are marked with label of “main address” on top of button~~
* Wallet menu:
  * Menu items are grouped by “main“ address with proxy address listed as subgroup
  * Proxy address shows "parent" address
  * Proxy address shows access rights of proxy address, e.g. Any/Investor/Borrower

#### Related resources
* https://centrifugehq.slack.com/archives/C033T5YUX0W/p1652808438153949
* https://centrifuge.hackmd.io/fBHMpQJWQJiAQiUYkofFDQ?view#18-May

**Comment by armandomistral** [comment]
@offerijns, I created this ticket so there is a "public" place for the spec. Feel free to groom the ticket body.
@onnovisser, I think you might already be working on this.
@EstherCentrifuge, this is for you to acknowledge. Not sure how this ticket needs to be labeled, etc.

**Comment by armandomistral** [comment]
@onnovisser, let's not show the "parent" address of a selected proxy address on top of the button. Users can see it in the menu. And I think we could set a name which indicates that, right?

**Comment by onnovisser** [comment]
@armandomistral Could you update Figma to show what you mean?

**Comment by armandomistral** [comment]
Yes, it's already updated here: https://www.figma.com/file/d1bEBkwllUQe27nQM6VlJu/Centrifuge-app---Version-1-(Master)?node-id=6864%3A114348 (moved the previous version out of the frame)

**Comment by onnovisser** [comment]
Ah okay 👍

**Comment by EstherCentrifuge** [comment]
This keeps disconnecting on the "investments" page, can we fix that?
