### ISSUE TITLE
Asset financing

### ISSUE THREAD

**Issue by EstherCentrifuge** [centrifuge/apps#844]
## Is
* The input amount does not show a balance
* The max button fills the available financing amount

![image](https://user-images.githubusercontent.com/23652850/170032882-e18bf220-ecf7-4f08-a711-0996573f68fd.png)

## Target
> And for the borrow component, the subtext should just show the minimum of the available financing and the available reserve.
> [Slack](https://centrifugehq.slack.com/archives/C033T5YUX0W/p1653165833003329)

* Available amount: minimum value of `available financing`, `available reserve`
    * Available pool reserve - my (the issuer) pending repayments (in epoch)= available reserve for the issuer
        * After Epoch is closed/executed my pending repayments = 0 (as nothing is pending) 
* Max: enters available amount
* Show the balance amount depending on available financing and available reserve:
    * Show the minimum of the `available financing` and the `available reserve`

Example: `589 kUSD available`

[Figma: part - finance asset - exception](https://www.figma.com/file/d1bEBkwllUQe27nQM6VlJu/Centrifuge-app---Version-1-(Master)?node-id=7075%3A115344)

![image](https://user-images.githubusercontent.com/98879480/170258412-de77cdfe-8a87-49dd-808d-22d5fa712854.png)

#### The max amount 
The max amount to finance is “flexible” please update to exact with 2 decimals
Example in total I can borrow 140 against my asset, i borrow 100, now 5 min later i can not borrow 40 becuase of the maturity and interest, this is logic and works well.
However the “available financing” states 40 but then when i fill 40 it says it exceeds the available financing. hwne you press the “max” option it gives the correct amount. Digets behind comma for “max amount” always roundned down (so 97,8767654 = 97,87)

![image.png](https://images.zenhubusercontent.com/61fa54b8b520bc58fd924e32/0a5a63e5-3ac5-41af-8e6e-c6c5adbc1dc1)

**Comment by EstherCentrifuge** [comment]
@onnovisser  see my comment above, , I know i wrote it somewhere :)

**Comment by sophialittlejohn** [comment]
@EstherCentrifuge @armandomistral regarding the available amount
>The max amount to finance is “flexible” please update to exact with 2 decimals
Example in total I can borrow 140 against my asset, i borrow 100, now 5 min later i can not borrow 40 becuase of the maturity and interest, this is logic and works well.
However the “available financing” states 40 but then when i fill 40 it says it exceeds the available financing. hwne you press the “max” option it gives the correct amount. Digets behind comma for “max amount” always roundned down (so 97,8767654 = 97,87)

I took this to mean that the form title `Available Financing` should also display 2 decimal points so it's not deceiving the user (who may think more is available if it's rounded). Please let me know if I misunderstood
