### ISSUE TITLE
Asset Ready status

### ISSUE THREAD

**Issue by EstherCentrifuge** [centrifuge/apps#845]
On altair we don't use bullet loans, but can we have the same status-> Ready when an asset is priced but no loan have been taken out (instead of the current on going) [see status overview ](https://centrifuge.hackmd.io/sUnY0kNoQamfj9I_IFquoQ)

**Comment by EstherCentrifuge** [comment]
I'm pretty sure this is done... @onnovisser @sophialittlejohn ?

**Comment by sophialittlejohn** [comment]
@EstherCentrifuge yes, looks like it was done 👍
