### ISSUE TITLE
Asset repayment

### ISSUE THREAD

**Issue by armandomistral** [centrifuge/apps#846]
## Is
> Currently, the subtext of the repayment input shows the pool currency balance. Instead, it should the minimum of the pool currency balance and the outstanding amount (i.e. if outstanding < balance, then the subtext should just show the outstanding, as this is the max that can be repaid)
[Slack](https://centrifugehq.slack.com/archives/C033T5YUX0W/p1653165813582759)

![image](https://user-images.githubusercontent.com/23652850/170033650-c1780cfc-fcfc-4be4-9977-87c739719fa8.png)

## Target
* Available amount in currency input field: minimum value of `wallet balance` and `outstanding amount`
* Max: enters available amount
* Repay all: disabled if available < outstanding
* Show info message if `wallet balance` is shown

Example: `Your wallet balance (589 kUSD) is smaller than the outstanding`

[Figma](https://www.figma.com/file/d1bEBkwllUQe27nQM6VlJu/Centrifuge-app---Version-1-(Master)?node-id=7063%3A120062)

![image](https://user-images.githubusercontent.com/23652850/170266029-79d03eaa-425e-4172-ad5b-995674373a26.png)

#### Related ticket
https://github.com/centrifuge/apps/issues/844

**Comment by EstherCentrifuge** [comment]
It should show the issuers wallet balance.
Ticket will be updated by @armandomistral with the new design :) 
Thank!

**Comment by armandomistral** [comment]
Done, @EstherCentrifuge

**Comment by EstherCentrifuge** [comment]
@onnovisser 
We should add thousand separators to the currency inputs. -> comma thousand, point decimal

Quickly checked, we used to use this library for it in Tinlake UI: https://github.com/s-yadav/react-number-format#readme. But there’s probably simpler ways to implement it, e.g.: https://stackoverflow.com/questions/63091317/thousand-separator-input-with-react-hooks

**Comment by sophialittlejohn** [comment]
An issue that came up during testing: it appears that outstanding value doesn't include accrued interest, I will double-check
