### ISSUE TITLE
UI fixes to table component: Row height

### ISSUE THREAD

**Issue by armandomistral** [centrifuge/apps#852]
#### Is
The row-height of table rows (both table header rows and table body rows) is not consistent, and too low.

![image.png](https://images.zenhubusercontent.com/6090f1ca0d0c23544195c7ec/6701418e-1c16-47fa-a941-d145d8e24bfd)

![image.png](https://images.zenhubusercontent.com/6090f1ca0d0c23544195c7ec/b616276e-5363-474c-872b-3296b1a43f58)

#### Target
* Apply consistent height of 48px to both header and body rows
* Make table rows consistent in height across instances, i.e.:
  * Token menu
  * Pool menu
  * Investment tokens (in pool detail)
  * Tokens (in Portfolio)
* [Component spec](https://www.figma.com/file/TPFzwr1VVtg7MZlRVwMKvS/Fabric-design-system?node-id=988%3A3649)
* [Token menu spec](https://www.figma.com/file/LCbVWH8fXPkXMbLpC3VZtx/Centrifuge-app---Altair?node-id=3692%3A83628)

![image.png](https://images.zenhubusercontent.com/6090f1ca0d0c23544195c7ec/6624f4d0-2de2-4596-b8f6-610ab01c3629)

![image.png](https://images.zenhubusercontent.com/6090f1ca0d0c23544195c7ec/0e1ca0b9-dc11-4ba2-b38c-589232ab6981)

**Comment by sophialittlejohn** [comment]
@armandomistral how should we handle words that are too long? Currently, they wrap lines. We could add an ellipsis (...) or a scroll overflow. Please let me know 🙏

**Comment by sophialittlejohn** [comment]
yeah, let's go with an ellipsis 🙌  and yep, you can always zoom out to see the full content

**Comment by armandomistral** [comment]
Thanks for the fixes, @sophialittlejohn! Tested on https://dev.app.altair.cntrfg.com/:
- Table row height fixed to 48px: ✅
- Preventing cell text from wrapping: ✅
- Ellipsing content:
   * Token name column of token table: ✅
   * Asset class column of token table: ⚠️ Not set
… Do you have an idea on how we might standardize the ellipsing of content so that it's applied to all columns? So we don't need to it manually on a case-by-case basis...
