### ISSUE TITLE
Manage pools [ Nice to have]

### ISSUE THREAD

**Issue by EstherCentrifuge** [centrifuge/apps#858]
We moved this out of Altair, we want to allow users with correct admin rights to configure the pool after created.
We discussed this in the past, let me know if there are any questions. 

[Figma](https://www.figma.com/file/d1bEBkwllUQe27nQM6VlJu/Centrifuge-app---Version-1-(Master)?node-id=6398%3A117770)
[Specs](https://centrifuge.hackmd.io/1OiMlCCWTL2YwUN8c_sFnA)

It's understood that once a change is made there is a delay period (not sure of the official term before the change can be executed and once the time is passed it can only be excuted if no redemption orders are outstanding 

Minimum time period Iwill be different per runtime (i.e. different on Altair vs Cent Chain). Will likely be 7 days, but whoever implements this should just retrieve the period from chain

New items after "createpool"
1.  Checkbox to display this pool in the list of pools (investment menu item) yes/no

2.  Schema's -> new ticket for this.
[Figma](https://www.figma.com/file/d1bEBkwllUQe27nQM6VlJu/Centrifuge-app---Version-1-(Master)?node-id=6398%3A117770)

**Comment by onnovisser** [comment]
@EstherCentrifuge 
I doubt we can change to pool currency, can we?
I don't think all changes will take 7 days to take effect, like things that just change metadata.
But not sure exactly which changes do. Is it the Tranche en Epoch settings that have this?
/cc @offerijns

**Comment by EstherCentrifuge** [comment]
#1000 is related / duplicate
