### ISSUE TITLE
Investment menu item (Pools & Token list in 1)  [Must have]

### ISSUE THREAD

**Issue by EstherCentrifuge** [centrifuge/apps#860]
## Background
We're merging `Pools` and `Tokens` into one main menu item called `Investments` in order to offer one single entry point for investors to discover and screen investment opportunities. In order to be clearly distinguishable from the tabular token list, pools are represented as cards arranged in a flow layout.

## Acceptance criteria
* Pools and tokens are merged in one main navigation item called `Investments`
* Users can switch between the pools and tokens view
* Pool items are represented as cards

## Behavior
* The Pools view is selected by default (it's the "easier" entry point as this list contains fewer items than the token list)
* The summary section is independent of the selected view (i.e. the information shown does not change)
* Clicking the backlink `Investments` on a pool detail leads to the pool view of the Investments page (i.e. we don't store whether you came from the pool or the token menu view)

![image.png](https://images.zenhubusercontent.com/61fa54b8b520bc58fd924e32/df400642-78bc-4aff-b648-81038fdac037)

### Mockups
* [Pool menu](https://www.figma.com/file/d1bEBkwllUQe27nQM6VlJu/Centrifuge-app---Version-1-(Master)?node-id=5244%3A78031)
* [Token menu](https://www.figma.com/file/d1bEBkwllUQe27nQM6VlJu/Centrifuge-app---Version-1-(Master)?node-id=617%3A7168)

**Comment by armandomistral** [comment]
Thanks, @sophialittlejohn! Looks good to me.

**Comment by EstherCentrifuge** [comment]
one tiny UI comment: can you make the clickable area in the switch as large as possible? For the active option (Pools here), it’s the entire white button. For the inactive option (Tokens here), it’s only the text, while ideally it should be most of the gray area. ![image.png](https://images.zenhubusercontent.com/61fa54b8b520bc58fd924e32/ebd6c58b-d54e-41bb-bd63-94d45e6b6bd1)

**Comment by armandomistral** [comment]
Good catch, @EstherCentrifuge, I will add this requirement to the ticket of adding the toggle group to Fabric...
