### ISSUE TITLE
Disallow orders during epoch submission: Show system feedback

### ISSUE THREAD

**Issue by armandomistral** [centrifuge/apps#870]
### Background
> One small technical, temporary change we need to make to the UI: we’ll need to disallow new orders while a pool is in a submission period. In the future we can support this again, but currently we have to block this on chain for security reasons.
> I think we should just show a warning / info box in the invest component if the pool is in a submission period, explaining that orders are temporarily blocked.

[Slack](https://centrifugehq.slack.com/archives/C033T5YUX0W/p1653408649402229) 

### Acceptance criteria
* The system prevents submitting orders while in submission period
* The system presents system feedback in the context of investments, and the epoch

### Solution
During submission period, the system reacts to the case as follows:
* **Investment component:** The `Invest` action is disabled
   * The `Redeem` action is disabled
* **Epoch summary**: The state label says `Calculating orders...`
   * A timer of the remaining submission duration in minutes is shown
* **Epoch detail**:
   * The state label says `Calculating orders...`
   * A timer of the remaining submission duration in minutes is shown
   * The `Close` button is presented in progress state

[Figma spec](https://www.figma.com/file/d1bEBkwllUQe27nQM6VlJu/Centrifuge-app---Version-1-(Master)?node-id=7080%3A115466)

**Comment by EstherCentrifuge** [comment]
I am not sure how easy this is but let us know. @onnovisser

**Comment by armandomistral** [comment]
@onnovisser, I understand that there is currently no way to show the remaining submission duration dynamically. Yet I think it's important for the system to show a time duration. What's the standard/default submission duration – is it 30 min? We might show a static duration information, which should be a conservative estimation, e.g. `This takes about 30 min`. WDYT?

**Comment by EstherCentrifuge** [comment]
This is becuase we don't have a solver. this will be solved for V1 so don't worry about it for Altair

**Comment by EstherCentrifuge** [comment]
@armandomistral please do the folowwing:

- Create a new pool :Limit 2000
- Invest Junior 500 -> close epoch
- Invest senior 1000 -> close epoch
- Now you should be able to redeem 1000 if you want. (check but don't redeem)
- Invest 1000 Senior -> This will overlimit the limt -> close epoch
Now the epoch is stuck! -> should say something like "Calculating orders..." 

Try tio redeem -> should not be possible.

**Comment by armandomistral** [comment]
@EstherCentrifuge & @onnovisser, if I follow exactly the steps above, the console shows the message "Epoch closed successfully" (see screenshot). But the UI displays the status "Calculating orders".  Why is this mismatch … is this a bug? See https://dev.app.cntrfg.com/issuer/4185558569/liquidity
 ![image.png](https://images.zenhubusercontent.com/6090f1ca0d0c23544195c7ec/e1ae8ec0-fb9c-48fd-b51a-140f7eef3a45)

**Comment by armandomistral** [comment]
Ok, @onnovisser, let's pass this one, since there is no solver in place yet. The main bulk of work for epoch detail feedback will be covered by ticket https://app.zenhub.com/workspaces/centrifuge-applications-5fa29e924059e5001625e2a3/issues/centrifuge/apps/940 in Version 1...
