### ISSUE TITLE
BUG: Can't re-finance after partial repayment

### ISSUE THREAD

**Issue by EstherCentrifuge** [centrifuge/apps#886]
1. I borrowed the full amount, which hid the finance form.
2. I repaid part of the asset.
Now the label Available Financing  shows a positive number but as a user I can't finance more.

**It should be available 
Spec:** 
It is depending on the loan type we allow a new financing:
**Credit line loan types** = Yes, as long as the expected repayment/date is still in the future
_All NFT’s are on this loantype_

![image.png](https://images.zenhubusercontent.com/61fa54b8b520bc58fd924e32/89fcebd9-2cdd-4c4c-a4b2-dee9bbccfb45)

**Comment by EstherCentrifuge** [comment]
I made a new asset, fully financed, payed back 100 and now have "available" but not the acctual option to get it out 
Maturity date is in the future..

so failed in my understanding
![image.png](https://images.zenhubusercontent.com/61fa54b8b520bc58fd924e32/6e95919b-7d13-4498-9119-5c1aed4cc7de)

**Comment by sophialittlejohn** [comment]
another bug, unrelated but here for documentation: routing between issuer --> token detail --> back to token is broken. It leads to `issuer/tokens` instead of `investment/tokens`
