### ISSUE TITLE
Asset list: Dynamic value specific to status

### ISSUE THREAD

**Issue by armandomistral** [centrifuge/apps#889]
## Background
When viewing the asset list, I want to see the asset's amount and the associated state, so I know the next action without opening the detail view.

## Approach
The `Amount` column shows the amount and action specific to the status.

### Asset list sort order
The asset list is sorted on the `Asset number` column, in descending order (i.e. the latest asset is shown first).

### Status and display in `Amount`column
* **Created** –  empty column
* **Ready** – Priced, nothing financed: `<Available financing amount>` & `available`
* **Ongoing** – One financing transaction: `<Outstanding amount>` & `outstanding`
* **Repaid** –  Fully repaid: `<Repaid amount>` & `repaid`
* **Closed** – Closed: `<Repaid amount>` & `repaid`

### Mockups
[Asset list example (Figma)](https://www.figma.com/file/9iwvzHuvbjlHXRWlPWRxxc/Centrifuge-app---Version-2-(Branch)?node-id=7239%3A74252)
![image.png](https://images.zenhubusercontent.com/61fa54b8b520bc58fd924e32/537077ff-3fdd-4142-a1a3-4ea2bf93a1a2)

**Comment by EstherCentrifuge** [comment]
Duplicates https://github.com/centrifuge/apps/issues/946
