### ISSUE TITLE
BUG: Rounding error?

### ISSUE THREAD

**Issue by EstherCentrifuge** [centrifuge/apps#893]
I think there is a rounding issue.

I miss 6 cents, i think it should be 149.66 available financing. 

No?

![image.png](https://images.zenhubusercontent.com/61fa54b8b520bc58fd924e32/5f6c22d5-ec20-4164-b419-092ef7bb0640)

**Comment by offerijns** [comment]
Maybe the difference is that we only allow borrowing up to slightly less than the available amount, as a buffer between submitting the finance transaction and it being executed (as the debt keeps accruing).

**Comment by onnovisser** [comment]
Yes, as Jeroen says, when there's outstanding debt, we add a little buffer. currently it's one day of accrual, but we could make that a little less
