### ISSUE TITLE
Altair: Establish shoulder height for menu items and toolbar content in app layout

### ISSUE THREAD

**Issue by armandomistral** [centrifuge/apps#897]
## Background
The menu items in the left sidebar and the toolbar content on the left are vertically not aligned. The header row content across rows (i.e. logo, main header, wallet button) is not perceived as one row.
![image.png](https://images.zenhubusercontent.com/6090f1ca0d0c23544195c7ec/81c44162-ad5f-4265-9bb8-6eccd6243b43)

The notification toast covers part of the toolbar content
![image.png](https://images.zenhubusercontent.com/6090f1ca0d0c23544195c7ec/4acddca3-aa8a-4ea0-af68-068fd98b93cc)

## Approach
To establish a top header row appearance, menu items and toolbar content is aligned at the same vertical position (the shoulder height), adding whitespace between header row and body content. The notification toast fits in between wallet button and toolbar content, so that nothing gets hidden behind. To achieve this grid layout, the three first parts of each column (menu, main, toolbar) has a fixed height of 80px.

## Acceptance criteria
* The logo area has a fixed height of 80px, with the logo in fixed size inside
  * ![logo-centrifuge.svg](https://images.zenhubusercontent.com/6090f1ca0d0c23544195c7ec/9bb15a54-78cc-4502-8071-82aa21164838)
  * ![logo-altair.svg](https://images.zenhubusercontent.com/6090f1ca0d0c23544195c7ec/07ac2d5d-e88d-4bc5-904f-e341586aa01c)
* The shoulder height is positioned at y:120px
* **Menu**: The margin between logo and first navigation item is 40px
* **Toolbar**: The margin between wallet button and toolbar components is 40px (with the 80 px height of the wallet button area) 
* **Toast**: The absolute position of the toast notification is top: 64px, left: 16px

[App layout (Figma)](https://www.figma.com/file/d1bEBkwllUQe27nQM6VlJu/Centrifuge-app---Version-1-(Master)?node-id=7555%3A117241)

**Comment by armandomistral** [comment]
Thanks, @sophialittlejohn!! I've tested on https://dev.app.cntrfg.com/ and https://dev.app.altair.cntrfg.com/, and I've found two things:
- The shoulder height seems to depend on the logo (the Altair logo is higher), which may result in a misaligned shoulder-height.

![image.png](https://images.zenhubusercontent.com/6090f1ca0d0c23544195c7ec/9f6dfc24-65a0-4edd-a606-c65ac9b57750)

![image.png](https://images.zenhubusercontent.com/6090f1ca0d0c23544195c7ec/cece68b9-52e1-44da-92c9-c9baa3748e0b)

- The toast is too low, and it overlaps with the investment component.
![image.png](https://images.zenhubusercontent.com/6090f1ca0d0c23544195c7ec/b21ba6e0-22ec-436c-97cc-5bdb4f189961)

### Target:
* The shoulder height should work regardless of the logo
* Position toast notifications at 64px top, so that toolbar content is not covered.

@sophialittlejohn, do you see a way how we can establish the shoulder-height irrespective of the logo set?

**Comment by armandomistral** [comment]
Thanks, @sophialittlejohn. I checked https://dev.app.altair.cntrfg.com and https://dev.app.cntrfg.com. And compared the two themes (see attached image). Here's what I've found:
- The shoulder height is not consistent across apps
- The Centrifuge logo is too small. It is 82.59px x 24.47px but should be 107.76 x 32px. (The svg{max-width: 50%;} declaration scales it down).
![shoulderheight-comparison](https://user-images.githubusercontent.com/23652850/178209486-0ef5d3ce-0bd4-4612-a4a7-b309b19a3a1a.png)

#### Target
- Use fixed logo area of 124 x 80px across themes
- Shoulder-height should be fixed and agnostic to used logo/applied theme.
![logo-altair](https://user-images.githubusercontent.com/23652850/178210493-37153940-9fd0-42c9-bfe8-766ad99e81c3.svg)
![logo-centrifuge](https://user-images.githubusercontent.com/23652850/178210496-7a3854c9-fdc9-4439-8ed2-f3b205798411.svg)

Attached SVGs use a fixed size of 124x80px size.

**Comment by sophialittlejohn** [comment]
thanks for the logos @armandomistral! I think we got it right this time 🤞

**Comment by armandomistral** [comment]
Thanks, @sophialittlejohn! It works!! Until we touch it again to make it responsive...
