### ISSUE TITLE
Altair – Pool's Investor tab: Wording improvements

### ISSUE THREAD

**Issue by armandomistral** [centrifuge/apps#901]
## Background
The term `member list` is not consistent with the already established term `whitelist`:
* If an address exists and at least one token is whitelisted, the feedback expression is `Address In member list`
* If an address exists and no token is whitelisted, the feedback expression is `Address not in member list`

![image.png](https://images.zenhubusercontent.com/6090f1ca0d0c23544195c7ec/cfab39ce-346d-4cf0-b55a-553537b9362c)

The action of removing and adding a token to the whitelist is not symmetrical: while _Remove_ uses an icon, _Add_ uses the label `Add token`.

![image.png](https://images.zenhubusercontent.com/6090f1ca0d0c23544195c7ec/315937e3-bda3-4ae7-b46a-4c6fdca133c9)

## Target
* Change feedback expression from `Address In member list` to `Address whitelisted`
* Change feedback expression from `Address not in member list` to `Address not whitelisted`
* Change label of `Add token` action to `Add to whitelist`
* Change label of _Remove_ action to `Remove from whitelist`

[Spec (Figma)](https://www.figma.com/file/LCbVWH8fXPkXMbLpC3VZtx/Centrifuge-app---Altair?node-id=5630%3A97778)

![image.png](https://images.zenhubusercontent.com/6090f1ca0d0c23544195c7ec/69c99bf6-71e4-4e51-a82c-1e0d744053a6)

**Comment by EstherCentrifuge** [comment]
Failed 

![image.png](https://images.zenhubusercontent.com/61fa54b8b520bc58fd924e32/47d14e9a-7a2f-43c5-ad49-b48685ae5fe1)

**Comment by armandomistral** [comment]
Thanks, @sophialittlejohn!! I've tested both https://dev.app.cntrfg.com/ and https://dev.app.altair.cntrfg.com/. Here's what I've found:
* **Is**: The button `Remove from whitelist` uses the large button size
  * **Target**: Use the small button size for the action `Remove from whitelist` (like the action `Add to whitelist`)
* **Is**: The remove action uses the icon `minus-circle`
  * **Target**:  Use the icon `Minus`, without a circle (like the add action)
* **Is**: On screen size 1280px wide and smaller, the remove icon gets truncated
  * **Target**: Prevent the remove icon from truncation – truncate the button label at the end instead
* **Is**: The Investor table uses a font-size of 16px, which is not consistent with other tables (and the [table component](https://www.figma.com/file/TPFzwr1VVtg7MZlRVwMKvS/Fabric-design-system?node-id=988%3A3649) in general)
  * **Target**: Apply font style `body2` in size 14px – apply the general table style

## Screenshots
![image.png](https://images.zenhubusercontent.com/6090f1ca0d0c23544195c7ec/e11664d2-17ce-4adf-8c90-8eae35ead2ad)
![image.png](https://images.zenhubusercontent.com/6090f1ca0d0c23544195c7ec/b7630ff9-17a3-450e-90cd-27e57e721a73)
![image.png](https://images.zenhubusercontent.com/6090f1ca0d0c23544195c7ec/6031e1ae-4b4e-4575-91b5-6708492bf25c)
![image.png](https://images.zenhubusercontent.com/6090f1ca0d0c23544195c7ec/9bf4bb55-8365-4885-aa74-0adda525b718)

**Comment by armandomistral** [comment]
Thanks, @sophialittlejohn!! 

> I've addressed everything in this ticket except optimization for smaller screen sizes. I agree it's important and it may sound trivial... but this is not an "easy fix" because it will affect all tables and because we need to truncate from right to left. Let's save this and batch it together with other responsive optimization tasks,
Ok. Will take a note for the spec of the table responsiveness..

* Target: Use the small button size for the action Remove from whitelist (like the action Add to whitelist): ✅
* Target: Use the icon Minus, without a circle (like the add action): ✅
* Target: Apply font style body2 in size 14px – apply the general table style: ✅

**Comment by armandomistral** [comment]
@sophialittlejohn, flagging the issuer here – as agreed – so it does not get forgotten:
* **Is**: The font-size of the address table cell is too large, 16px:
![image.png](https://images.zenhubusercontent.com/6090f1ca0d0c23544195c7ec/d63c40c0-5e47-45cf-baf9-31c99f19eff0)
![image.png](https://images.zenhubusercontent.com/6090f1ca0d0c23544195c7ec/2cb39d22-e9bf-4d21-96b7-ab4c4bf449bc)
* **Target**: Apply font-size 14px (Body 2) to address

**Comment by armandomistral** [comment]
Thanks, for font size correction, @sophialittlejohn! LGTM...
