### ISSUE TITLE
Altair – Pool's configuration tab: Improve add admin label

### ISSUE THREAD

**Issue by armandomistral** [centrifuge/apps#902]
## Background
* In the Admins section, the placeholder label `Enter address...` is not fully clear that it is for adding an address to the admin list.

![image.png](https://images.zenhubusercontent.com/6090f1ca0d0c23544195c7ec/d0cb4da3-ca96-4214-9f9b-6ff0829c263b)

* The column is called `Memberlist`, but the UI should consistently use the term `Whitelist`. (see also [ticket #901](https://app.zenhub.com/workspaces/centrifuge-applications-5fa29e924059e5001625e2a3/issues/centrifuge/apps/901))

![image.png](https://images.zenhubusercontent.com/6090f1ca0d0c23544195c7ec/e2ce28b2-a9aa-4171-b133-5d99ab4c0575)

* The role names (Pool, Borrower, etc.) are not entirely clear just by the name, which is why we're adding a tooltip to each role.

## Target
* Change the placeholder label `Enter address...` to `Search to add address...`
* Change the column header from `Memberlist`, to `Whitelist`. 
* Add tooltip to each role in the table (shown both in read-only and edit state). See rows 65-70 in [Centrifuge App tooltips](https://docs.google.com/spreadsheets/d/1wuAE_94QZ-9L7Q7uwFsTBtnmoiUnRbDm89icsW9YYdM/edit?usp=sharing)

[Spec (Figma)](https://www.figma.com/file/d1bEBkwllUQe27nQM6VlJu/Centrifuge-app---Version-1-(Master)?node-id=6398%3A117961)

![image.png](https://images.zenhubusercontent.com/6090f1ca0d0c23544195c7ec/6e40a279-c311-448b-afc9-846a3bf1ad7e)

**Comment by EstherCentrifuge** [comment]
please also  renaming `Risk `admin to `Loan`. admin

See discussion here: https://github.com/centrifuge/centrifuge-chain/issues/799

**Comment by sophialittlejohn** [comment]
@EstherCentrifuge according to this [thread](https://centrifugehq.slack.com/archives/C033T5YUX0W/p1656404897785169) `Loan` seems inaccurate. What else would be appropriate?

**Comment by armandomistral** [comment]
Thanks @sophialittlejohn for adjusting the role label to `Asset`!
