### ISSUE TITLE
Close ready assets

### ISSUE THREAD

**Issue by EstherCentrifuge** [centrifuge/apps#903]
I got an asset: https://dev.app.cntrfg.com/issuer/4177718755/assets/4
This asset is "ready" meaning it has a price and money "Available financing"
But i left the asset alone for a while and now the maturity date is passed.
I can not finance this asset as the maturity date is past, GREAT!
Added improvment ticket for V1 #869

But how can i now get my NFT back? I can't close the asset as there is 0 outstanding...

**Please add Close option on Ready assets!** 
Note from Jeroen: I just checked the chain logic, the loan should be close’able. We just need to add the option in the UI for this case to actually close the loan.

**Comment by EstherCentrifuge** [comment]
hi sending this back based on our chat.

please allow "close"
for created and ready tickets, 
No relation to maturity date.
If it's my asset i should be allowed to close it at any point as long ast there is 0 currency outstanding 

thanks!

**Comment by armandomistral** [comment]
Thanks, @onnovisser! Could you please apply the button style `Secondary` to the `Close` action? There should ideally be only one primary button on a screen at a given point in time... See [Loan statuses (Figma)](https://www.figma.com/file/d1bEBkwllUQe27nQM6VlJu/Centrifuge-app---Version-1-(Master)?node-id=6398%3A138246)

**Comment by onnovisser** [comment]
@armandomistral done

**Comment by armandomistral** [comment]
Thanks, @onnovisser!!
