### ISSUE TITLE
Centrifuge app: Include democracy vote hash in `createPool()` on prod

### ISSUE THREAD

**Issue by sophialittlejohn** [centrifuge/apps#912]
On Cent Chain, we will need to submit a democracy vote to create the pool. This will look something like:
```js
democracy.note_preimage(
  utility.batch(
    pools.create(),
    loans.initialise_pool(...)
  )
)

democracy.propose(preimage_hash)
```

We don’t necessarily need to build this into the app. The alternative would be to just build the UI such that we can return the hash of the pool creation call (see the createPoolPreimageHash variable above).

But I think ideally we would add a `propose?: boolean` argument to `createPool`, which is set to `true` whenever the app is connected to the live environments (Altair/Cent Chain). If set to true, the above would be submitted, rather than the direct `batchAll(createPool, …)` extrinsic.

**Comment by EstherCentrifuge** [comment]
works!
