### ISSUE TITLE
Env flag for public pools (permission for create pool button)

### ISSUE THREAD

**Issue by sophialittlejohn** [centrifuge/apps#913]
On altair and centrifuge mainnets we should hide the create pool button, as this is not a public action.

Some testnets will also follow the same scheme as above, some however should have open access to create pools (and the create pool button). 

We should add an env variable that will indicate whether the net is public or not and adjust the button hiding logic.

**Comment by EstherCentrifuge** [comment]
I can still see the create pool with every user
 ![image.png](https://images.zenhubusercontent.com/61fa54b8b520bc58fd924e32/2c1290b8-67fa-44e1-8a2f-8bca05b93be5)
