### ISSUE TITLE
Altair - Update data after tx

### ISSUE THREAD

**Issue by sophialittlejohn** [centrifuge/apps#915]
If you do things like set a new max reserve or close an epoch the data in the UI should update without having to refresh the page. Currently, the UI only updates for tx's on loans.

**Comment by armandomistral** [comment]
* Tested change of maximum reserve in `Test` pool from 2,000 to 2,222: Page auto-refreshed upon transaction ✅
* Tested closing of epoch in `Jays Properties` pool: Page auto-refreshed upon transaction ✅
