### ISSUE TITLE
CentrifugeJS: Setup GH actions to publish to npm

### ISSUE THREAD

**Issue by sophialittlejohn** [centrifuge/apps#938]
> Jeroen 2:18 PM 14 July
 this isn’t particularly high urgency, but just to flag it, maybe could be picked up in between some other work: at some point we should set up a Github Action to actually publish centrifuge.js to npm.
Let’s make sure we initially publish it as v0.1.x or something like that, and not use v1.x just yet

**Comment by EstherCentrifuge** [comment]
can you please add this to the appropriate epic @sophialittlejohn?

do we need it for first pool? -.>V1
do we need it before migration? -> v2
If no -> filler
