### ISSUE TITLE
Provide system feedback for epoch status

### ISSUE THREAD

**Issue by armandomistral** [centrifuge/apps#940]
## Goal
Centrifuge app shows the current state of the epoch, so users can see the progress (of the epoch duration), and whether orders are executable.

The epoch status should allow users to decide whether they want to wait for the epoch to close automatically, or to close it manually.

## Specification
[Epoch status - Centrifuge App V1
](https://centrifuge.hackmd.io/UkgOXautQI2E3pG7idKcsQ?view)

**Comment by EstherCentrifuge** [comment]
the feedback looks good! 
I got some none solvable scenario's but the feedback given is good so i'll pass this.
