### ISSUE TITLE
Use currencies registered in the asset-registry

### ISSUE THREAD

**Issue by offerijns** [centrifuge/apps#943]
- Add `centrifuge.tokens.getCurrencies()` method which is the list of harcoded variants + the list of assets registered in the asset-registry pallet. The latter can be retrieved using `ormlAssetRegistry.metadata.entries()`.
> I'm suggesting to create a new `tokens` module, so we can also add methods here in the future such as `transfer`, `mint`, `burn`, etc.
- Add `interface Currency { id, name, symbol, decimals }` to centrifuge.js and return this object from methods like `getPool` and `getPools` instead of the current currency id. Name/symbol/decimals can be retrieved from `ormlAssetRegistry.metadata(id)`.
- The UI should use the symbol property from the `Currency` interface as the symbol for each currency in the UI.
- The UI should use the decimals property from the `Currency` interface to determine how to convert it into a float value (e.g. USDC has 6 decimals, this means it should be divided by `10**6` rather than `10**18`).

**Comment by EstherCentrifuge** [comment]
correct epic @offerijns  @sophialittlejohn 

do we need it for first pool? -.>V1
do we need it before migration? -> v2
If no -> filler

**Comment by offerijns** [comment]
I'd consider this a very nice to have for V1. It's partially already been implemented by @onnovisser during the work for fixing the decimals on Altair.

**Comment by annamehr** [comment]
@onnovisser should we add this to v1 again?
