### ISSUE TITLE
Pool detail's asset list: Changes to 'Outstanding` column

### ISSUE THREAD

**Issue by armandomistral** [centrifuge/apps#946]
## Background
The `Oustanding` column in the pool' details asset list currently only shows the outstanding amount of the loan. However, while the outstanding amount is relevant in the `Ongoing` status, other statuses don't show any value. This does not give users the full of the asset status at the overview level.

![image.png](https://images.zenhubusercontent.com/6090f1ca0d0c23544195c7ec/b1eed5b6-59b7-4114-aa7c-ebb57146f1aa)
![image.png](https://images.zenhubusercontent.com/6090f1ca0d0c23544195c7ec/ef54e4af-a7eb-4a94-9a3b-fc5dba455381)

## Solution
The asset list shows an amount which is specific to the given status. Since this amount does not always represent the outstanding, the designated amount is shown next to the value. The column is renamed from `Outstanding` to `Amount`.

Each asset is shown with the specific value amount depending on the status. The rules are:

| Status | Schema | Example |
| -------- | -------- | -------- |
| Created     | `<collateral amount>` & `collateral`     | 10,000 kUSD collateral   |
| Ready | `<available financing amount>` & `available` | 10,000 kUSD available  |
| Ongoing | `<outstanding amount>` & `outstanding` | 10,000 kUSD outstanding |
| Repaid | `<repaid amount>` & `repaid` | 10,000 kUSD repaid |
| Closed | `<repaid amount>` & `repaid` | 10,000 kUSD repaid  |

### Specs
* [Pool detail > Assets (Figma)](https://www.figma.com/file/d1bEBkwllUQe27nQM6VlJu/Centrifuge-app---Version-1-(Master)?node-id=4196%3A98830)
* [Asset status during loan life cycle (Figma)](https://www.figma.com/file/d1bEBkwllUQe27nQM6VlJu/Centrifuge-app---Version-1-(Master)?node-id=7572%3A117322)

#### Note
This ticket replaces the ticket https://github.com/centrifuge/tinlake-subgraph/issues/178

**Comment by EstherCentrifuge** [comment]
Duplicates https://github.com/centrifuge/apps/issues/889

**Comment by annamehr** [comment]
Completed https://github.com/centrifuge/apps/issues/889
