### ISSUE TITLE
Set meta title to `Altair App` for altair network and `Centrifuge App` for centrifuge network

### ISSUE THREAD

**Issue by offerijns** [centrifuge/apps#957]

**Comment by EstherCentrifuge** [comment]
looks good thanks

**Comment by EstherCentrifuge** [comment]
actually, @sophialittlejohn it still shows the centerifuge icon, can this be altair?

**Comment by EstherCentrifuge** [comment]
Also please rename the "siubtitle" on the altair version to remove "of real-world assets" and keep only "Pools and tokens"


![image.png](https://images.zenhubusercontent.com/61fa54b8b520bc58fd924e32/c96c0a53-23c8-40fc-b442-3d030a2c98ec)
