### ISSUE TITLE
Connect onboarding app to database

### ISSUE THREAD

**Issue by tsx49** [centrifuge/apps#986]
**Background**

When Pools are launched on the Centrifuge chain, the database will need to be able to store the relevant investor information from the Centrifuge app. The aim here is to connect the onboarding app fork to our exisiting database, ensure it supports Centrifuge app, and save the same data that is stored today.

**The necessary updates in the table:**

- Add a new 'Blockchain' column to 'investments', 'agreements' and 'user pool' table
- Need to support the string in 'tranche' column

**Updates required to address table:**

- ‘Address’ should be saved in Centrifuge format: 4c2MFfj7j1v6bSvMWiboqAnnyqsmZ1ZcvUtxZFBsiEyLPwUV
- ‘Blockchain’ should be saved as ‘Centrifuge’

**Questions**
 - How about the mapping of the other fields? Are all the field from Centrifuge app the same as Tinlake?

**Comment by annamehr** [comment]
not needed anymore
