### ISSUE TITLE
Integrate Sengrid Onboarding emails for Centrifuge app

### ISSUE THREAD

**Issue by tsx49** [centrifuge/apps#989]
**User Story**

As a user
I want to receive an email notification when there has been a change in my onboarding status
So that I can complete any outstanding actions

**Background**
To keep investors who utilise Centrifuge app updated on their onboarding status, emails notifications will be sent out via Sendgrid when:

- A user signs a subdoc agreement
- A user has been whitelisted to invest
- A user's KYC has been rejected
- A user's KYC is under manual review
- A user's KYC has expired
- A users subscription agreement has declined 
- A users subscription agreement has been voided 
**[Documentation](https://docs.google.com/spreadsheets/d/1aPyWR0nc7gcyyuBielRM7z0Zlyrlnf418A0dCC6JUGM/edit#gid=189665312)**

**Questions?**

**Acceptance Criteria**

**Scenario 1 -  Ready to invest**
Given a Subscription agreement has been created for a user
And the pool for the subscription agreement is still active
When the investments table 'is_whitelisted' is updated with a  'True' value
Then the 'Ready to invest' template should be sent with their details via SendGrid to the latest whitelisted wallet address
And the 'Invest now' button should open the investment page for the token they have been whitelisted for

**Scenario 2 -  KYC rejected**
Given a user has submitted their KYC 
When the KYC table receives a 'rejected' status
Then the 'KYC Rejected ' email template should be sent with their details via SendGrid
And the 'Start verification' button should open the Securitize login page

**Scenario 3 -  KYC manual review**
Given a user has submitted their KYC
When the KYC table receives a 'manual-review' status
Then the 'KYC: requires manual review' email template should be sent with their details via SendGrid

**Scenario 4 -  KYC expired**
Given a user has submitted their KYC
When the KYC table receives a 'expired' status
Then the 'KYC: expired ' email template should be sent with their details via SendGrid
And the 'Start verification' button should open the Securitize login page

**Scenario 5 -  Subdoc Agreement Signed**
Given a Subscription agreement  has been created for a user
When the Agreements table receives a 'signed_at' value
Then the 'Subscription agreement signed' email template should be sent with their details via SendGrid

**Scenario 6 -  Subdoc Agreement declined**
Given a Subscription agreement  has been created for a user
When the Agreements table receives a 'declined_at' value
Then the 'Subscription agreement declined' email template should be sent with their details via SendGrid
And the 'Review and sign' button should direct the user to onboarding page for the declined token

**Scenario 7 -  Subdoc Agreement voided**
Given a Subscription agreement  has been created for a user
When the Agreements table receives a 'voided_at' value
Then the 'Subscription agreement voided' email template should be sent with their details via SendGrid
And the 'Review and sign' button should direct the user to onboarding page for the voided token

**Comment by annamehr** [comment]
Archived
