### ISSUE TITLE
Onboard as investor

### ISSUE THREAD

**Issue by denniswell** [centrifuge/apps#993]
When becoming an investor in a Centrifuge Pool, I want to onboard, so I can invest in the token.

## Acceptance criteria
A connected address can invest in a token if the following conditions are met:
* The address holder is KYC verified by Securitize
* The address holder is not a resident of an excluded country (see https://docs.centrifuge.io/use/onboarding/#excluded-countries)
* US investors are an `Accredited investor`
* The subscription document of the token has been signed both by the investor and the issuer
* The address is whitelisted to the token

## Spec
[Investor Onboarding - V1 (HackMD)](https://centrifuge.hackmd.io/H5y15LhKRRmSRp9o8M4epg?view)

**Comment by annamehr** [comment]
Archived since we do not use Securitize for Centrifuge App any longer
