### ISSUE TITLE
Claim rewards

### ISSUE THREAD

**Issue by denniswell** [centrifuge/apps#994]
## Acceptance criteria
Pools on Centrifuge Chain will offer investment rewards in CFG. The UI needs to be able to display an investor their earned and claimable rewards and allow them to claim their rewards.

## Specification
[Centrifuge App - Claim CFG rewards (version 1)](https://centrifuge.hackmd.io/UMKhn5oTTaGzST4R6IxG4Q?both)

**Comment by annamehr** [comment]
replaced by #1141
